### PR TITLE
OS X 64-bit Tribler builder

### PR DESCRIPTION
**Pull request by devos50**
This PR will contain the bash script to build a 64-bit version of Tribler on the Mac Mini. The script will be based on the current available script (`makedistmac.sh`). The current builder script should be replaced by this new script somewhere during the 6.5.x or 6.6 release cycle.

This version bundles Wx3 instead of Wx2.8. Also, the newest version of libraries are bundled (for instance, a newer version of libtorrent).

### CODE REVIEW

**Comment by whirm** [comment]
add to whitelist

**Comment by devos50** [comment]
It is creating a `.dmg` file now, still have to verify the correctness of the file.

**Comment by devos50** [comment]
The binary is confirmed to work on OS X 10.11, OS X 10.10 gives an error: `illegal operation: 4`.

**Comment by devos50** [comment]
Got an new error (probably due to some missing files):

```
Jan 10 22:21:12 MacBook-Pro-van-Martijn.local Tribler[15074] <Notice>: Traceback (most recent call last):
Jan 10 22:21:12 MacBook-Pro-van-Martijn.local Tribler[15074] <Notice>:   File "Tribler/dispersy/dispersy.pyo", line 1723, in _update
Jan 10 22:21:12 MacBook-Pro-van-Martijn.local Tribler[15074] <Notice>:   File "Tribler/community/tunnel/tunnel_community.pyo", line 982, in on_create
Jan 10 22:21:12 MacBook-Pro-van-Martijn.local Tribler[15074] <Notice>:   File "Tribler/community/tunnel/crypto/tunnelcrypto.pyo", line 47, in generate_session_keys
Jan 10 22:21:12 MacBook-Pro-van-Martijn.local Tribler[15074] <Notice>:   File "cryptography/hazmat/primitives/kdf/hkdf.pyo", line 112, in derive
Jan 10 22:21:12 MacBook-Pro-van-Martijn.local Tribler[15074] <Notice>:   File "cryptography/hazmat/primitives/kdf/hkdf.pyo", line 95, in _expand
Jan 10 22:21:12 MacBook-Pro-van-Martijn.local Tribler[15074] <Notice>:   File "cryptography/hazmat/primitives/hmac.pyo", line 32, in __init__
Jan 10 22:21:12 MacBook-Pro-van-Martijn.local Tribler[15074] <Notice>:   File "cryptography/hazmat/backends/multibackend.pyo", line 101, in create_hmac_ctx
Jan 10 22:21:12 MacBook-Pro-van-Martijn.local Tribler[15074] <Notice>: UnsupportedAlgorithm: sha256 is not a supported hash on this backend.
```

**Comment by devos50** [comment]
@whirm it seems that the EULA shown when opening the `.dmg` file is very large which causes the screen to take a long time (around 20 seconds) to respond. Do we really need a license file here and if so, can we use a shorter one?

**Comment by devos50** [comment]
Fixed the `UnsupportedAlgorithm` error by bundeling the right files (the old builder script was based on an older version of the Python `cryptography` package).

I've uploaded a license file in #1867. When the fixes in the `next` branch are merged into the `devel` branch, I will fix https://github.com/Tribler/tribler/issues/1864.

@whirm I'm done with this PR and the builder is working well. Can this one be merged? After merge, I can incrementally improve and adjust the builder to make it better, based on any new errors we encounter.

**Comment by devos50** [comment]
retest this please

**Comment by whirm** [comment]
Ok, let's merge this one, can you squash the fix commits to the broken commits?

**Comment by devos50** [comment]
@whirm I've grouped and squashed the commits together :+1:

**Comment by whirm** [comment]
Have you tested both builders or only the mac mini?

**Comment by devos50** [comment]
Only on the mac mini, will test the old builder now.

**Comment by devos50** [comment]
@whirm the old builder is also still working with this PR.

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Pull request merged**
