### PR TITLE
READY: Correct variable name

### LINKED ISSUE #5050: Wrong variable passed to function
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
devel
##### Operating system and version: #####
All
##### Expected behavior: #####
`fileindex` should be passed into a function.
##### Actual behavior: #####
`filename` is passed into the function.

https://github.com/Tribler/tribler/pull/5043#issuecomment-572079210
https://github.com/Tribler/tribler/blob/devel/src/tribler-core/tribler_core/modules/libtorrent/download_config.py#L132
https://github.com/Tribler/tribler/blob/devel/src/tribler-core/tribler_core/modules/video_server.py#L156

### PR DESCRIPTION
**Pull request by Solomon1732**
Correct variable name. In addition rename functions to avoid future confusion with their usage. Closes #5050

### CODE REVIEW

**Comment by Solomon1732** [comment]
Since I'm not succeeding at getting any further with this PR I think I should close it.

**Comment by devos50** [comment]
@Solomon1732 what's the problem?

**Comment by Solomon1732** [comment]
In this case a Java `NullPointerException`. That aside, my code seem fine, but it doesn't pass some of the tests for some reason, and I can't pinpoint why

**Comment by Solomon1732** [comment]
https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_async_mac/206/

These failing tests seem to fail in other PRs, making me suspect it's not a problem with my own PRs. See also the Mac tests of #5052, #5055, #5056, and #5059 
https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_async_mac/203/
https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_async_mac/202/
https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_async_mac/201/
https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_async_mac/205/

Same for the windows tests. All the failings in https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_async_win64/204/ can be seen in #5059's windows tests
https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_async_win64/201/

**Comment by devos50** [comment]
Our tests are very flaky after a sequence of invasive changes recently, especially the tests on Mac and Windows. I think we should prioritize getting *all* tests stable across all platforms. I'm currently investigating the anonymous downloading test to see why it fails on Mac. Hopefully I can fix that one and address #5058 in the process.

@xoriole @ichorid do we have any ETA on when these tests will be stable again?

**Comment by ichorid** [comment]
> @xoriole @ichorid do we have any ETA on when these tests will be stable again?

These tests never were stable. They were just disabled on the platforms where they would fail. In short, the problem is a race condition between Libtorrent and Tunnels initialization sequences. It depends on both OS, Libtorrent version and PC performance in an unpredictable way. Moving to asyncio changed the timings.

I guess @egbertbouman is now working on this.

**Comment by ichorid** [comment]
@Solomon1732 , also, please next time squash your commits yourself into one if all of those are interdependent and solve the same problem.

**Pull request merged**
