### PR TITLE
Fix add to channel error

### LINKED ISSUE #5498: 'ChannelMetadata' object has no attribute 'torrent_exists'
On trying to add a download from Downloads list into a channel or a channel folder.

### PR DESCRIPTION
**Pull request by ichorid**
fixes #5498

### CODE REVIEW

**Comment by ichorid** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
Seems like `Test completely re-commit your channel ... ` is stuck...

**Comment by ichorid** [comment]
retest this please

**Pull request merged**
