### PR TITLE
Root state directory and version support

### PR DESCRIPTION
**Pull request by xoriole**
Introducing `.Tribler` as root state directory to support multiple tribler version. Now each new version will have a separate state directory located inside `.Tribler` directory with the same name as the version.

### CODE REVIEW

**Comment by xoriole** [comment]
retest this please

**Comment by devos50** [comment]
Is this a known test error?

```
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/asynctest/case.py", line 297, in run
    self._run_test_method(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/asynctest/case.py", line 352, in _run_test_method
    result = method()
  File "/Users/tribler/Documents/workspace2/workspace/GH_Tribler_PR_Tests/PR_async_mac/tribler/src/tribler-core/tribler_core/tests/tools/test_as_server.py", line 56, in check
    result = fun(*argv, **kwargs)
  File "/Users/tribler/Documents/workspace2/workspace/GH_Tribler_PR_Tests/PR_async_mac/tribler/src/tribler-core/tribler_core/modules/metadata_store/tests/test_store.py", line 154, in test_squash_mdblobs_multiple_chunks
    for d in self.mds.process_compressed_mdblob(chunk2, skip_personal_metadata_payload=False)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1058, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1040, in assertSequenceEqual
    self.fail(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
Lists differ: [b"\x[792 chars]RK\t', b'#d\x9eB\x1a\x97S\xa0\xc5:MwS\xd0H\x89[124 chars]x0f'] != [b"\x[792 chars]RK\t']
```

**Comment by xoriole** [comment]
@devos50 it is failing for some reason, not sure if this is related to this PR. I'm looking into the issue with long path windows now.

**Comment by xoriole** [comment]
retest this please

**Pull request merged**
