### PR TITLE
Implemented endpoint to edit channel properties

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by devos50** [comment]
@lfdversluis can you review?

**Comment by lfdversluis** [comment]
You just moved stuff?

**Comment by devos50** [comment]
@lfdversluis no, I also added a `render_POST` in `my_channel_endpoint.py` (see commits).

**Comment by lfdversluis** [comment]
Looks ok

**Comment by devos50** [comment]
@whirm ready for your review

**Pull request merged**
