### PR TITLE
Remove redundant logic from LibtorrentDownloadImpl.network_stop

### PR DESCRIPTION
**Pull request by vandenheuvel**
This method appears to contain useless statements.

### CODE REVIEW

**Comment by vandenheuvel** [comment]
@devos50 Do you think this is a good change, or am I missing something?

**Comment by devos50** [comment]
I'm not 100% sure whether this code can be removed. The VCS annotations suggest that @egbertbouman created this code. I will ask about it on monday.

**Comment by egbertbouman** [comment]
It doesn't look like this is being used anymore. The pstate.set gets called, but nothing is being done with pstate. Feel free to remove!

**Comment by vandenheuvel** [comment]
@egbertbouman thanks, I'll update this branch and put it on `READY` for  @devos50 to review.

**Comment by devos50** [comment]
Thanks!

**Pull request merged**
