### PR TITLE
Fix unique infohash problem

### PR DESCRIPTION
**Pull request by LipuFei**

### CODE REVIEW

**Comment by LipuFei** [comment]
@whirm ready

**Comment by whirm** [comment]
Souldn't we see why are we getting dupes on the first place?

**Comment by LipuFei** [comment]
@whirm They came from the Channel community, but I haven't checked how this happened.

**Comment by whirm** [comment]
```channel/community.py:_disp_on_torrent()``` If we get a batch of messages in which there are repeated torrents we get in trouble. I guess the current solution is fine.

**Pull request merged**
