### PR TITLE
No blocking_call for TorrentChecking thread

### PR DESCRIPTION
**Pull request by LipuFei**
Option 2 for #1494

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
I don't like this either, just fix the shutdown method. Don't mess with the rest.

**Comment by LipuFei** [comment]
@whirm @NielsZeilemaker If I was thinking correctly, this should fix the dead lock.

**Comment by NielsZeilemaker** [comment]
This is a lot better, but still if we happen to be on the reactor thread already, then this thread.join might cause a deadlock.

**Comment by NielsZeilemaker** [comment]
It simply needs a timeout value there. You can even set a crazy high timeout, but it needs one.

**Comment by LipuFei** [comment]
@NielsZeilemaker Done

**Comment by NielsZeilemaker** [comment]
And log it as an error:
https://github.com/Tribler/tribler/pull/1493/files#diff-9c4b6475dbed144b806a02887d2e1cc3R132

**Comment by LipuFei** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by LipuFei** [comment]
@whirm @NielsZeilemaker Should be ready

**Comment by LipuFei** [comment]
@whirm @NielsZeilemaker And close #1494 if you merge this one

**Comment by NielsZeilemaker** [comment]
We should log if the join failed, like @whirm was doing here https://github.com/Tribler/tribler/pull/1493/files#diff-9c4b6475dbed144b806a02887d2e1cc3R132

**Pull request merged**
