### PR TITLE
Small updates to the Tribler documentation

### PR DESCRIPTION
**Pull request by devos50**
- Removed outdated Twisted tutorial.
- Updated the docs configuration file.
- Updated REST API introduction.

### CODE REVIEW

**Comment by qstokkink** [comment]
Yay the spellchecker was useful for once in two years! API should be capitalized.

**Comment by devos50** [comment]
@qstokkink uuuh I only use Api as part of `X-Api-Key`, which is intended?

**Comment by qstokkink** [comment]
😢

**Comment by qstokkink** [comment]
I'm sure the time to shine for the doc checker will come one day.

**Pull request merged**
