### PR TITLE
Fix some pydeadobjects during gui shutdown

### PR DESCRIPTION
**Pull request by lfdversluis**

### CODE REVIEW

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
@lfdversluis could you do a rebase of this too?

**Comment by lfdversluis** [comment]
Woo the new checkers \:octocat:/

**Comment by lfdversluis** [comment]
It doesn't auto-run? :(

**Comment by devos50** [comment]
retest this please

**Comment by lfdversluis** [comment]
ah ok, we have to force a retest atm

**Comment by devos50** [comment]
@lfdversluis my commits are triggering a build, let me check if you are on the whitelist.

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
retest this please

**Pull request merged**
