### PR TITLE
Remove unused stuff

### LINKED ISSUE #1097: Remove obsolete code in permid.py
Remove the internal functions in `permid.py`. They are not used any more.

### PR DESCRIPTION
**Pull request by LipuFei**
Fixes #1097

### CODE REVIEW

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
@NielsZeilemaker do you think this is OK to remove? (just to be sure)

**Comment by NielsZeilemaker** [comment]
@whirm seems fine, my guess is that was only supported by the old custom bittorrent engine

**Comment by whirm** [comment]
@NielsZeilemaker thx!

**Pull request merged**
