### PR TITLE
Fix None torrent_id problem

### PR DESCRIPTION
**Pull request by LipuFei**
Fix this backtrace:
```
File "/home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel/tribler/Tribler/community/channel/community.py", line 387, in _disp_on_torrent
  self._channelcast_db.on_torrents_from_dispersy(torrentlist)
File "/home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 1570, in on_torrents_from_dispersy
  torrent_ids, inserted = self.torrent_db.addOrGetTorrentIDSReturn(infohashes)
File "/home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 514, in addOrGetTorrentIDSReturn
  assert all(torrent_id for torrent_id in torrent_ids), torrent_ids
exceptions.AssertionError: [5200, 5201, 5202, 5203, 5204, None, 5205]
```

### CODE REVIEW

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
@whirm Let's merge this one first when it passes. A lot of PRs are failing because of this assertion error.

**Comment by LipuFei** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
@whirm ready

**Pull request merged**
