### PR TITLE
Added more details about the wx installation in the OS X guide

### PR DESCRIPTION
**Pull request by devos50**
The part about the manual installation was incomplete. I've added some more information about the installation process.

### CODE REVIEW

**Comment by devos50** [comment]
retest this please

**Comment by lfdversluis** [comment]
@whirm Do we still have weird behavior in tests after you disabled the hidden community tests? Also, these are doc changes, do we need the tests to run on these?

**Comment by whirm** [comment]
@lfdversluis I disabled the tunnel tests that would fail all the time. If you look at the logs you will see that we've got a segfault there, but I don't know to which of this entries on the kernel log it belongs:
`
[168267.001694] nosetests[19028]: segfault at 0 ip           (null) sp 00007fff81afd1c8 error 14 in python2.7[400000+2df000]
[168797.315705] nosetests[22347]: segfault at fffffffffffffff0 ip 00007fe254c37d00 sp 00007ffc4ad2fc50 error 5 in libwx_baseu-2.8.so.0.8.0[7fe254b7e000+151000]
[170631.469292] nosetests[34287]: segfault at 0 ip           (null) sp 00007ffc792e9f78 error 14 in python2.7[400000+2df000]
[177588.167881] nosetests[17163]: segfault at 0 ip           (null) sp 00007ffe66f8ac78 error 14 in python2.7[400000+2df000]
[345969.607707] nosetests[18237]: segfault at 8 ip 00007f72ff4c6fbf sp 00007f72f3333770 error 4 in libwx_baseu-2.8.so.0.8.0[7f72ff419000+151000]
[347780.316144] nosetests[22991]: segfault at 60 ip 00007fcc5a341555 sp 00007ffe14821828 error 4 in libpango-1.0.so.0.3800.1[7fcc5a330000+49000]
`

Let's wait until the wx3 stuff gets merged before trying to debug this.

**Comment by whirm** [comment]
And obviously we don't need to run the tests for doc updates, but jenkins doesn't know that :)

**Comment by lfdversluis** [comment]
@whirm why do PRs have to be aproved by an admin before jenkins runs on them anyway? In most open source projects I see that travis immediately runs so that when someone who can merge is on, it is most likely already done. Now (mostly you) have to approve, come back 10 min later and see if it broke something yes/no.

It could save you some time. I don't think Tribler is getting spammed with PR's anyway, so BBQ wont turn into a real one :)

**Comment by whirm** [comment]
Security, if all PRs where just run, anybody would have execution rights on the testing machines by just creating a PR.

Also, this should only happen the first time, as you can see in this PR, @devos50's pull request got tested right away.

**Comment by devos50** [comment]
@whirm can you enter IRC please? We have some questions

**Comment by whirm** [comment]
sure

**Pull request merged**
