### PR TITLE
Update Debian build

### PR DESCRIPTION
**Pull request by xoriole**
This PR updates the Debian build script to either user virtual env set via environment variable or create a new one. Using the existing venv leads to quicker build and using a new venv makes sure that there are no missing dependencies.

### CODE REVIEW

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Review by drew2a — APPROVED** [review]
👍

**Review by kozlovsky — APPROVED** [review]

**Pull request merged**
