### PR TITLE
Changed a print to log

### PR DESCRIPTION
**Pull request by lfdversluis**

### CODE REVIEW

**Comment by lfdversluis** [comment]
Lucky test run :D

**Comment by synctext** [comment]
add to whitelist

**Comment by whirm** [comment]
@lfdversluis: We want this to be printed to stderr, otherwise we will never see it, as the tests will time out because the thread is stuck and nose will never get the chance to flush the log buffers.

**Comment by whirm** [comment]
@synctext ignore the bot, it's the WIP QA job that keeps asking this for PRs to branches the job is not assigned to for some reason.

**Pull request closed without merging**
