### PR TITLE
Refactor structure of tribler communities

### PR DESCRIPTION
**Pull request by drew2a**
This PR contains refactoring of tribler's communities structure.

An attempt has been made to bring the structure to the following:

```python
modules
├my_community
  ├ tests
  | └test*.py
  ├ community.py
  └ settings.py
```

The core idea is to make communities more unified (by bringing them to a uniform structure) and more autonomous (by combining implementation with its settings definition)

## Implementation

For each Tribler community `settings` field  has been added by inheriting them from:

```python
class TriblerCommunity(Community):
    def __init__(self, *args, settings: TriblerConfigSection = None, **kwargs):
        super().__init__(*args, **kwargs)
        self.settings = settings
```

The settings set in `ipv8_module_catalog.py` for a normal Tribler's run: 

```python
class MyCommunityLauncher(IPv8CommunityLauncher):
    def get_kwargs(self, session):
        return {
            'settings': session.config.my_community,
        }
```

For tests it can be done by passing a settings object into community constructor:

```python
mock_ipv8.overlay.my_community = MyCommunity(settings=BandwidthAccountingSettings())
```

## Problems

I've encountered problems during refactoring the following entities:
1. TunnelCommunity
1. MetadataStore

### TunnelCommunity

Tribler's `TunnelCommunity` highly intertwined with Ipv8's `TunnelCommunity` and looks like hi-level "hack" or "patch" (I guess this is the result of an epic Dispersy refactoring).
Therefore it is hard to control and modify, for example, Community settings.

This PR leaves `TunnelSettings` as is, adding only the following logic in `TriblerTunnelCommunityLauncher`:

```python
class TriblerTunnelCommunityLauncher(IPv8CommunityLauncher):
    def get_kwargs(self, session):
        from ipv8.messaging.anonymization.community import TunnelSettings

        settings = TunnelSettings()
        settings.min_circuits = session.config.tunnel_community.min_circuits
        settings.max_circuits = session.config.tunnel_community.max_circuits
```

### MetadataStore

`MetadataStore` is a very special place in Tribler which is unlike anything else. It uses a special structure and special inner logic.
This unit contains two communities, ORM bindings, and REST-API.

It contains also `RemoteQueryCommunity` which is the base class for `PopularityCommunity` and `GigaChannelCommunity`. These dependencies make it difficult to isolate atomic settings for each community.

This PR leaves `MetadataStore` almost as-is, leaving refactoring to the author, except for:
1. `RemoteQueryCommunity` extracted from `MetadataStore` and placed to `modules`along with the rest communities.
2.  Has been added `rqc_settings` field to `RemoteQueryCommunity` class and all its successors.

```python
class RemoteQueryCommunity(TriblerCommunity, EVAProtocolMixin):
    def __init__(self, my_peer, endpoint, network, metadata_store, rqc_settings: RemoteQueryCommunitySettings = None,
                 **kwargs):
        super().__init__(my_peer, endpoint, network=network, **kwargs)
        self.rqc_settings = rqc_settings or RemoteQueryCommunitySettings()
```

Launcher: 
```python
class PopularityCommunityLauncher(IPv8CommunityLauncher):
    def get_kwargs(self, session):
        return {
            'settings': session.config.popularity_community,
            'rqc_settings': session.config.remote_query_community,
        }
```

### CODE REVIEW

**Comment by drew2a** [comment]
retest this please

**Comment by synctext** [comment]
Good initiative!
You are merging and unifying the coding practices of _several_ Tribler communities (e.g. Lab members). That's never going to be easy :clap:

**Comment by ichorid** [comment]
>This PR leaves MetadataStore almost as-is, leaving refactoring to the author ... 

“The proof is left up to the student” (c) Richard Feynman :rofl:

**Review by ichorid — APPROVED** [review]

**Comment by egbertbouman** [comment]
Looks like we just commited some test artifacts ([0.db](https://github.com/Tribler/tribler/blob/main/src/tribler-core/tribler_core/TestRemoteQueryCommunity_temp_568538d9489a4c6fa54814222f24e104/0.db) and [1.db](https://github.com/Tribler/tribler/blob/main/src/tribler-core/tribler_core/TestRemoteQueryCommunity_temp_a97dc47c569a46b99f11e914ca02cf1f/1.db)) to our main branch...

**Comment by drew2a** [comment]
@egbertbouman yes, you are right. Will fix it soon.
Related to #6158

**Pull request merged**
