### PR TITLE
Made tunnel remove notification candidate immutable

### LINKED ISSUE #2655: Issue when a tunnel is removed
```
RNING:TunnelLogger:Got pong (1949740343) from ('95.211.155.142', 49889),
I am <Member 90334 17a4a82c3fabd656074b9c83947e6695ce345b22>
WARNING:SearchCommunity:message from <Candidate 211.116.88.46:7759>
cannot be found in the request cache, skipping it
WARNING:TunnelLogger:Removing relay 1245271599 too old
WARNING:TunnelLogger:Removing relay 377303990 too old
Unhandled Error
Traceback (most recent call last):
 File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
   self._target(*self._args, **self._kwargs)
 File "/local/git/tribler-test/TriblerGUI/core_manager.py", line 65, in
start_tribler_core
   reactor.run()
 File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line
1195, in run
   self.mainLoop()
 File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line
1204, in mainLoop
   self.runUntilCurrent()
--- <exception caught here> ---
 File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line
798, in runUntilCurrent
   f(*a, **kw)
 File
"/local/git/tribler-test/Tribler/community/multichain/community.py",
line 414, in on_tunnel_remove
   if self._public_key > candidate.get_member().public_key:
exceptions.AttributeError: 'NoneType' object has no attribute 'public_key'
```

It seems like the candidate has been removed when the tunnel is closed.

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #2655.

Also fixes bug where RelayRoute mid initialization value was being ignored.

### CODE REVIEW

**Comment by devos50** [comment]
@qstokkink ignore sonarqube, it's a bit confused after the PR where I removed the wx GUI

**Comment by qstokkink** [comment]
This is ready for merging: marking this as `ON HOLD` though until #2655 can be reliably reproduced and shown to be fixed by this PR.

**Comment by devos50** [comment]
@qstokkink I don't mind to merge it if the bug is not easily reproduced but I would like to confirm that the code is doing what is it supposed to do and do not crash.

**Comment by qstokkink** [comment]
Marking this as READY, can confirm the added test case fires #2655 in the old code and works correctly in the new code.

RelayRoute removal remains unchecked still, I believe this test would be too ridiculously huge.

**Comment by devos50** [comment]
@qstokkink great! Please rebase your PR and I will merge 👍

**Pull request merged**
