### PR TITLE
Use libtorrent to create torrent files

### LINKED ISSUE #1462: Creating a new .torrent from your own channel (for hidden seeding)
To reproduce:
1) dd if=/dev/urandom of=RANDOMDATA.txt bs=1M count=165
2) create a new channel
3) goto "manage torrents" tab, press "+Add..." button
4) use the "create your own .torrents" by pressing "create"
5) browse files and add RANDOMDATA.txt

This will generate a .torrent, but it cannot be added to your channel.

This will generate error below:
```
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/vwxGUI/channel.py", line 991, in startDownload
    tdef = TorrentDef.load(torrentfilename)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/TorrentDef.py", line 87, in load
    return TorrentDef._read(f)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/TorrentDef.py", line 105, in _read
    return TorrentDef._create(data)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/TorrentDef.py", line 110, in _create
    validTorrentFile(metainfo)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Utilities/utilities.py", line 23, in validTorrentFile
    raise ValueError('metainfo misses key info')
ValueError: metainfo misses key info
WARNING 1433774408.58       community:1552  removing ('63.142.161.7', 23509) {192.168.0.19:7759 63.142.161.7:23509} in favor of ('63.142.161.7', 7759) {192.168.0.19:7759 63.142.161.7:7759}
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/Dialogs/AddTorrent.py", line 143, in OnBrowse
    self.__processPaths(filenames)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/Dialogs/AddTorrent.py", line 130, in __processPaths
    self.frame.startDownload(filename)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Main/vwxGUI/MainFrame.py", line 453, in startDownload
    tdef = TorrentDef.load_from_memory(torrent_data)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/TorrentDef.py", line 96, in load_from_memory
    return TorrentDef._create(data)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/TorrentDef.py", line 110, in _create
    validTorrentFile(metainfo)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Utilities/utilities.py", line 23, in validTorrentFile
    raise ValueError('metainfo misses key info')
ValueError: metainfo misses key info
```

### PR DESCRIPTION
**Pull request by LipuFei**
Closes #1462

### CODE REVIEW

**Comment by LipuFei** [comment]
@whirm Ready. Will remove the rest stuff in another PR.

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by synctext** [comment]
The unit tests got an error. Can we fix this?
```
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: [0x7fbc08001968] alsa audio output error: cannot open ALSA device "default": No such file or directory
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: [0x7fbc08001968] main audio output error: Audio output failed
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: [0x7fbc08001968] main audio output error: The audio device "default" could not be used:
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: No such file or directory.
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: [0x7fbc08001968] main audio output error: module not functional
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: Fontconfig warning: FcPattern object size does not accept value "0"
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: [0x7fbbec019ff8] xcb_xv vout display error: no available XVideo adaptor
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: ../../include/vlc_xlib.h:46:vlc_xlib_init: Xlib not initialized for threads.
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: This process is probably using LibVLC incorrectly.
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: Pass "--no-xlib" to libvlc_new() to fix this.
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: [0x7fbbec019ff8] xcb_glx vout display error: Xlib not initialized for threads
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: Fontconfig warning: FcPattern object size does not accept value "0"
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: Fontconfig warning: FcPattern object size does not accept value "0"
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: [0x7fbc18018a08] main decoder error: failed to create audio output
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: [0x7fbbec019ff8] main vout display error: Failed to resize display
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: [0x3b3e558] main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 1000 ms)
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: [0x3b3e558] main input error: ES_OUT_RESET_PCR called
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: Non-reference picture received and no reference available
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: [h264 @ 0x7fbc180167e0] decode_slice_header error
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: [h264 @ 0x7fbc180173e0] mmco: unref short failure
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: [h264 @ 0x7fbc180173e0] Missing reference picture
Build timed out (after 49 minutes). Marking the build as failed.
```

**Comment by synctext** [comment]
```
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: test_delay2 (Tribler.Test.test_gui_server.TestGUITaskQueue) ... ok
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: test_more (Tribler.Test.test_gui_server.TestGUITaskQueue) ... ok
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: test_simple (Tribler.Test.test_gui_server.TestGUITaskQueue) ... ok
Build timed out (after 50 minutes). Marking the build as failed.
Build was aborted
Archiving artifacts
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_n...] ERR: test_hidden_services (Tribler.Test.test_hidden_community.TestHiddenCommunity) ... python: Fatal IO error 11 (Resource temporarily unavailable) on X server :26584.
INFO:OneShotProcessProtocol:[wrap_in_vnc.sh run_nosetests_for_jenkins.sh] exit code None
INFO:ExperimentRunner:Syncing output data back from head nodes...
```

**Comment by LipuFei** [comment]
@rjruigrok Are the tunnel tests fine? It was passing yesterday and now it doesn't. Or maybe I broke something.

**Comment by LipuFei** [comment]
retest this please

**Comment by rjruigrok** [comment]
@LipuFei @synctext @whirm Tests are indeed failing. I'lll have a look at them tonight. Strange, yesterday it was passing. 
It's only the test that fails after I splitted up tunnel tests into 3 seperate files, I suspect it's the order in which the tunnel tests are executed is causing the trouble, it's closing the socks server in a few seconds after starting the test. The simple solution for fixing is to wrap around the tests until they're in a combination that passes. Not nice, but working for you guys now.

**Comment by LipuFei** [comment]
@whirm looks like increasing the timeout helps.

**Comment by whirm** [comment]
@rjruigrok ^

**Comment by whirm** [comment]
lets try a few more times

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
Looks fine to me, if it passes I'll merge.

**Comment by synctext** [comment]
uPNP never worked, wow.
```if self.upnp_mapper:```
That is quite a bug you caught! It never has a non-NULL value..

**Comment by LipuFei** [comment]
@synctext Turns out that although uPNP is supported according to `libtorrent` C++ documentation, the uPNP `add_port_mapping()` function is not exposed in the Python binding, so it still doesn't work. I disabled it for the moment.

**Pull request merged**
