### PR TITLE
Extended TradeChain in the market community

### PR DESCRIPTION
**Pull request by devos50**
This PR contains a major refactoring of the market community. Most important features:
- merged TradeChainCommunity and the MarketCommunity: every action in the market is now recorded on TradeChain.
- added a message to TrustChainCommunity that allows for sending a pair of half blocks to a specific candidate
- added functionality to TrustChainCommunity that allows for message broadcasting (using `NHopCommunityDestination`)
- fixed some minor bugs and removed unused code

TradeChain:

tradechain

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by devos50** [comment]
@qstokkink ready for review!

**Comment by qstokkink** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
Everything else looks good.

**Comment by devos50** [comment]
Created issue #3081

**Comment by devos50** [comment]
retest this please

**Pull request merged**
