### PR TITLE
Removed unused test files

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by devos50** [comment]
retest this please

**Comment by whirm** [comment]
This was used for the thumbnail tests, AFAIR, we will re-enable this feature in the future, so let's keep it.

**Comment by devos50** [comment]
@whirm we have the same video four times in the tests directory (`Tribler/Test/data/video.avi`, `Tribler/Test/API/video.avi`, `Tribler/Test/API/video2.avi` and `Tribler/Test/API/contentdir/video.avi`). I understand they are used for testing the creation of torrent files but having the same movie four times available in the test directory seems a bit too much for me.

**Comment by whirm** [comment]
ah, I didin't know that :D

**Comment by devos50** [comment]
I will create an issue for it :+1:

**Pull request merged**
