### PR TITLE
Various fixes for Tribler 7

### LINKED ISSUE #2668: [Enhancements] Feedback on GUI in Tribler-alpha1-47-gaa92b5f
Loving the new look, but got some proposed improvements for the future, Tested on windows 10.

* Remembering what the last download was.

At the moment of writing, batch adding torrents don't work, but i believe it is like i'm describing. When adding multiple torrents at once, the download confirmation dialog pops-up, and you get to pick a location. With 6.6.0 (and maybe some other versions, i can't remember) after picking the download location for the first torrent, the second torrent downloads window would keep that location. Thus, if all torrents were going to the same space, you'd only need to select the location once if it wasn't the default, whereas now, you need to change it for each torrent when adding them. 

This also applies to when single torrents are added, as it only uses default location each time, and does not remember what you selected prior. 

* Drop down menu with recently picked locations when selecting download.

The drop down option present in the old GUI made selecting a different common location easier, if it was a location that wasn't default, or wasn't the one you used last time. It provided a quick and easy functionality compared to navigating to the correct place with the browse option. 

* Longer "NAME" column in torrents section.

Well, the same with windows explorer(which never learns), the name column usually covers for a single word of the torrent name. Roughly 15 characters showing, is a little low. A option to change default length(preferred, to account for different screens) or a longer one in general. Used with a 1080p 27" monitor for reference. Right now for me, i got almost 30 of dead space on the right side, which could be used by making the torrent name column longer. 

* The ability to batch select torrents from a folder (without picking everything in the directory folder)

This functionality was in the former GUI, but does not seem to be in the new one. As when browsing you aren't allowed to select multiple objects anymore. 

* white border around torrent details, as well as the tab buttons "Details", "Files", "Trackers", and "Peers"

Well, i'm guessing it's in the works. But, it's currently a small inconsistency in the GUI style. I do love the new dark GUI though, much easier on the eyes, and much smoother and more reliable. Hope i don't sound like i complain to much. Just a bit eager on things. 

* Unable to see percentages on the with background, before the torrents download has gotten far enough to have orange behind it. 

Disclaimer, i'm red-green colorblind, but those are in a white/ very light grey color right? I need to get pretty close to the screen to see the percentage.

### LINKED ISSUE #2793: Trackers with an invalid port number should be removed/not being entered into the database
I received the following report:

```
Traceback (most recent call last):
File "TriblerGUI/event_request_manager.py", line 91, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.OverflowError'>: getsockaddrarg: port must be 0-65535.
twisted/internet/defer.py:651:_runCallbacks
twisted/internet/base.py:256:_checkTimeout
twisted/internet/defer.py:457:callback
twisted/internet/defer.py:565:_startRunCallbacks
--- <exception caught here> ---
twisted/internet/defer.py:651:_runCallbacks
Tribler/Core/TorrentChecker/session.py:477:on_ip_address_resolved
twisted/internet/posixbase.py:369:listenUDP
twisted/internet/udp.py:179:startListening
twisted/internet/udp.py:217:_connectToProtocol
twisted/internet/protocol.py:725:makeConnection
twisted/internet/protocol.py:689:doStart
Tribler/Core/TorrentChecker/session.py:380:startProtocol
twisted/internet/udp.py:340:connect
socket.py:228:meth
]
```

I guess the port is out of range of the specific tracker. We should not enter a tracker in our database that contains an invalid port number.

### LINKED ISSUE #2808: Tribler 7 stops working after one torrent gives 'File not found in torrent' error
##### Tribler version/branch+revision: #####
```
~/bin/tribler $ git show
commit 02b0cfa8a1556f2017b50157214c50ec123a9b90
Merge: f7779ba eaec7bb
Author: Martijn de Vos
Date:   Wed Feb 15 09:40:31 2017 +0100

    Merge pull request #2788 from qstokkink/fix_socks5_associate
    
    READY: Allow UDP associate without circuits

~/bin/tribler $ git status
On branch devel
Your branch is up-to-date with 'origin/devel'.
nothing to commit, working directory clean
```
##### Operating system and version: #####
```
~/bin/tribler $ uname -a
Linux 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
##### Expected behavior: #####
Tribler skips file, ignores error or removes torrent from download queue if it can't continue.

##### Actual behavior: #####
Tribler hangs/crashes and after closing Tribler also hangs/crashes during startup. Replacing the `return ValueError` in `Tribler\Core\TorrentDef.py:767` with `return i` skips this error and the torrent (seems to) start to download normally

##### Steps to reproduce the behavior: #####
Add the following magnet link to Tribler with 'Import torrent from URL':

##### Relevant log file output: #####
```
ERROR:RESTRequest:[Failure instance: Traceback: <type 'exceptions.TypeError'>: ValueError('File not found in torrent',) is not JSON serializable
/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py:571:dataReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:1657:lineReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:1736:allContentReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:762:requestReceived
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/web/server.py:183:process
/usr/lib/python2.7/dist-packages/twisted/web/server.py:234:render
/usr/lib/python2.7/dist-packages/twisted/web/resource.py:250:render
~/bin/tribler/Tribler/Core/Modules/restapi/downloads_endpoint.py:225:render_GET
/usr/lib/python2.7/json/__init__.py:244:dumps
/usr/lib/python2.7/json/encoder.py:207:encode
/usr/lib/python2.7/json/encoder.py:270:iterencode
/usr/lib/python2.7/json/encoder.py:184:default
]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "~/bin/tribler/Tribler/Core/Modules/restapi/downloads_endpoint.py", line 225, in render_GET
    return json.dumps({"downloads": downloads_json})
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ValueError('File not found in torrent',) is not JSON serializable```

### LINKED ISSUE #2810: Error not triggering bug report
v7.0.0-alpha3
See attached image

te

### LINKED ISSUE #2816: Tribler crashes when visiting Trust page
On 1b4f68beb6ce96ebd41e6b176cb82a2d4497042d.

##### Operating system and version: #####
Ubuntu 16.10. `~/.Tribler` didn't exist.

##### Expected behavior: #####
When clicking on the star in the top-right corner, the trust page is shown.

##### Actual behavior: #####
Crash with stack trace
```Traceback (most recent call last):
  File "/home/user/tribler/TriblerGUI/widgets/trustpage.py", line 104, in received_multichain_blocks
    self.plot_absolute_values()
  File "/home/user/tribler/TriblerGUI/widgets/trustpage.py", line 124, in plot_absolute_values
    self.trust_plot.compute_initial_figure()
  File "/home/user/tribler/TriblerGUI/widgets/trustpage.py", line 64, in compute_initial_figure
    self.draw()
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 158, in draw
    FigureCanvasAgg.draw(self)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 474, in draw
    self.figure.draw(self.renderer)
  File "/usr/lib/python2.7/dist-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1159, in draw
    func(*args)
  File "/usr/lib/python2.7/dist-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 2319, in draw
    a.draw(renderer)
  File "/usr/lib/python2.7/dist-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axis.py", line 1108, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axis.py", line 951, in _update_ticks
    tick_tups = [t for t in self.iter_ticks()]
  File "/usr/lib/python2.7/dist-packages/matplotlib/axis.py", line 898, in iter_ticks
    for i, val in enumerate(majorLocs)]
  File "/usr/lib/python2.7/dist-packages/matplotlib/dates.py", line 484, in __call__
    dt = num2date(x, self.tz)
  File "/usr/lib/python2.7/dist-packages/matplotlib/dates.py", line 419, in num2date
    return _from_ordinalf(x, tz)
  File "/usr/lib/python2.7/dist-packages/matplotlib/dates.py", line 271, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
ValueError: ordinal must be >= 1```

### LINKED ISSUE #2820: Tribler.Core.Utilities.sort_utils is not used
https://github.com/Tribler/tribler/commit/1b4f68beb6ce96ebd41e6b176cb82a2d4497042d

The module Tribler.Core.Utilities.sort_utils is not used. Should it be deleted?

### LINKED ISSUE #2821: Tribler.Core.Utilities.twisted_utils is not used
https://github.com/Tribler/tribler/commit/1b4f68beb6ce96ebd41e6b176cb82a2d4497042d

The module Tribler.Core.Utilities.twisted_utils is not used. Should it be deleted?

### LINKED ISSUE #2823: matplotlib is confused about the QT version
I run into this error on startup since the trust screen was added:
```
ERROR:root:Traceback (most recent call last):
  File "run_tribler.py", line 21, in <module>
    window = TriblerWindow()
  File "/home/quinten/tribler/tribler/TriblerGUI/tribler_window.py", line 101, in __init__
    uic.loadUi(get_ui_file_path('mainwindow.ui'), self)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/__init__.py", line 222, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/Loader/loader.py", line 72, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 980, in parse
    actor(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 787, in createUserInterface
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 765, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 249, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 765, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 462, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 765, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 505, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 765, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 462, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 765, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 505, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 765, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 249, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 765, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 240, in createWidget
    self.stack.push(self.setupObject(widget_class, parent, elem))
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/uiparser.py", line 204, in setupObject
    obj = self.factory.createQObject(clsname, name, args, is_attribute)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/objcreator.py", line 106, in createQObject
    factory = self.findQObjectType(classname)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/objcreator.py", line 131, in findQObjectType
    w = module.search(classname)
  File "/usr/lib/python2.7/dist-packages/PyQt5/uic/Loader/qobjectcreator.py", line 115, in search
    module = __import__(mname, {}, {}, (cls,))
  File "/home/quinten/tribler/tribler/TriblerGUI/widgets/trustpage.py", line 7, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvas
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 18, in <module>
    from .backend_qt5 import QtCore
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.py", line 27, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/qt_editor/figureoptions.py", line 17, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/qt_editor/formlayout.py", line 58, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/qt_compat.py", line 91, in <module>
    from PyQt4 import QtCore, QtGui
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
```

This can be solved by explicitly pointing matplotlib to QT5 in [`trustpage.py` line 2](https://github.com/Tribler/tribler/blob/devel/TriblerGUI/widgets/trustpage.py#L2):
```python
import matplotlib
matplotlib.use('Qt5Agg')
```

### PR DESCRIPTION
**Pull request by devos50**
Fixes #2810, fixes #2808, fixes #2793, fixes #2668, fixes #2816, fixes #2820, fixes #2821, fixes #2823 .

### CODE REVIEW

**Comment by qstokkink** [comment]
Could you refactor/move the inner function [`TriblerLaunchMany.init().load_communities()`](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/APIImplementation/LaunchManyCore.py#L219) to a class method `TriblerLaunchMany.load_communities()` in this PR as well?

This is related to https://github.com/Tribler/gumby/issues/300 .

**Comment by devos50** [comment]
@qstokkink please create a commit and I will cherry-pick it on this PR 👍

**Comment by qstokkink** [comment]
@devos50 Done! https://github.com/qstokkink/tribler/commit/3a29a8c3123e86803d03eaa3fb1f172029be2b12

**Comment by devos50** [comment]
Done and done

**Comment by vandenheuvel** [comment]
@devos50 Maybe you could have a look at `Tribler.Main.metadata-injector` and `Tribler.Core.Utilities.misc-utils` consider to delete those as well, or at least move this `compute_ratio` method in `metadata-injector`.

**Comment by devos50** [comment]
@vandenheuvel the metadata injector should be refactored to a twistd plugin.

**Pull request merged**
