### PR TITLE
WIP: remove wx gui from test_as_server.py

### PR DESCRIPTION
**Pull request by brussee**

### CODE REVIEW

**Comment by brussee** [comment]
Apparently some tests are failing that should not use wx...

**Comment by brussee** [comment]
Apparently some tests are failing that should not use wx...

@devos50 Are these on your radar?

**Comment by whirm** [comment]
retest this please

**Comment by devos50** [comment]
@brussee I think it's a bit too early to remove wx from `test_as_server.py` since there are many tests that needs to be written to not use the wx GUI.

**Comment by lfdversluis** [comment]
I would like to get rid of wx ASAP. I just found out it is conflicting with my storm work.

**Comment by brussee** [comment]
I think it is ridiculous that non gui tests use wx code. All gui tests were already removed, right?

**Comment by devos50** [comment]
@brussee no, they should be rewritten to not use a GUI first.

**Comment by brussee** [comment]
@devos50 Will #2422 fix this PR as well?

**Comment by brussee** [comment]
retest this please

**Comment by brussee** [comment]
Partly, because apparently only 12 tests to go:
```
Test Result (12 failures / -75)

    Tribler.Test.test_my_channel.TestMyChannel.test_add_torrents_playlists
    Tribler.Test.test_my_channel.TestMyChannel.test_metadata
    Tribler.Test.test_my_channel.TestMyChannel.test_rss_import
    Tribler.Test.test_remote_search.TestMixedRemoteSearch.test_ffsearch
    Tribler.Test.test_remote_search.TestMixedRemoteSearch.test_remotedownload
    Tribler.Test.test_remote_search.TestRemoteChannelSearch.test_channel_search
    Tribler.Test.test_remote_search.TestRemoteTorrentSearch.test_remote_torrent_search
    Tribler.Test.test_tunnel_community_positive.TestTunnelCommunityPositive.test_anon_download
    Tribler.Test.test_tunnel_community_positive.TestTunnelCommunityPositive.test_anon_tunnel
    Tribler.Test.test_tunnel_community_negative.TestTunnelCommunityNegative.test_anon_download_exitnode_changeofmind
    Tribler.Test.test_tunnel_community_negative.TestTunnelCommunityNegative.test_anon_download_without_exitnodes
    Tribler.Test.test_tunnel_community_negative.TestTunnelCommunityNegative.test_anon_download_without_relays
```

**Comment by devos50** [comment]
@brussee I'm working on the above tests

**Comment by brussee** [comment]
@devos50 Great! Right now I do not stop the tests if 1 or more are failing so this is _not_ blocking me.

**Pull request closed without merging**
