### PR TITLE
Print more information in unit tests

### PR DESCRIPTION
**Pull request by LipuFei**

### CODE REVIEW

**Comment by LipuFei** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by whirm** [comment]
@LipuFei ready?

**Comment by LipuFei** [comment]
@whirm The print code I added have never been tested. Maybe we should wait?

**Comment by LipuFei** [comment]
@whirm This one should be ready. I thought it is the one that prints dispersy statistics.

**Pull request merged**
