### PR TITLE
Colorized peer counts in debug window

### PR DESCRIPTION
**Pull request by qstokkink**
This allows everyone to see the overlay health without knowing the healthy peer counts, see https://github.com/Tribler/tribler/issues/4171#issuecomment-462121405 .

afbeelding

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please. Not sure how `Tribler.Test.Community.Tunnel.test_community.TestTriblerTunnelCommunity.test_payouts_e2e` managed to fail.

**Comment by devos50** [comment]
Hmm let me check that one...

**Comment by qstokkink** [comment]
@devos50 https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_linux/1281/

**Comment by qstokkink** [comment]
Possibly this?

```
ERROR   1549802063       community:TriblerTunnelCommunity:544  On linked e2e: could not find download!
ERROR   1549802063 hidden_services:TriblerTunnelCommunity:396  On linked e2e: could not find download for ��V?f�����(*(t5?�/�?!
```

**Comment by qstokkink** [comment]
retest this please 😠

**Comment by qstokkink** [comment]
retest this please 🤦‍♂️

**Pull request merged**
