### PR TITLE
Removed general excepts from category.py

### PR DESCRIPTION
**Pull request by lfdversluis**
Adds **1** test

### CODE REVIEW

**Comment by lfdversluis** [comment]
on mac:
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/local/lib/python2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/Users/tribler/Documents/workspace/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/Core/Modules/channel/channel.py", line 85, in _on_channel_created
    if channel_data[u'channel'].cid != self._channel_community.cid:
exceptions.AttributeError: 'NoneType' object has no attribute 'cid'
```

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
all passed.

**Comment by lfdversluis** [comment]
Linux: 
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Modules/tracker_manager.py", line 98, in update_tracker_info
    tracker_info = self._tracker_dict[tracker_url]
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
all passed

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
all passed

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
all passed

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
all passed

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
all passed. Safe to merge you think @whirm ?

**Comment by whirm** [comment]
@lfdversluis looks stable! Could you cover the missing branch?

**Comment by lfdversluis** [comment]
@whirm ready for merge!

**Pull request merged**
