### PR TITLE
WIP: fix AlreadyCalledError on channel download callback

### LINKED ISSUE #4026: Error on on_channel_download_finished - AlreadyCalledError
```python
Traceback (most recent call last):
File "/home/quinten/Documents/tribler/TriblerGUI/event_request_manager.py", line 133, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <class 'twisted.internet.defer.AlreadyCalledError'>: 
/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py:1261:run
/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py:1270:mainLoop
/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py:896:runUntilCurrent
/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/task.py:239:__call__
--- <exception caught here> ---
/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py:151:maybeDeferred
/home/quinten/Documents/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py:610:_task_process_alerts
/home/quinten/Documents/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py:406:process_alert
/home/quinten/Documents/tribler/Tribler/Core/Libtorrent/__init__.py:17:invoke_func
/home/quinten/Documents/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py:505:process_alert
/home/quinten/Documents/tribler/Tribler/Core/Libtorrent/__init__.py:17:invoke_func
/home/quinten/Documents/tribler/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py:650:on_torrent_finished_alert
/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py:564:<lambda>
/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py:521:on_channel_download_finished
/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py:460:callback
/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py:561:_startRunCallbacks
]

```

### PR DESCRIPTION
**Pull request by ichorid**
Fixes #4026 

Happens in Python...

### CODE REVIEW

**Comment by ichorid** [comment]
retest this please

**Comment by devos50** [comment]
It seems that our Jenkins server is down. This is most likely caused by major ICT maintenance that is currently being done on the campus.

**Comment by qstokkink** [comment]
retest this please

**Comment by ichorid** [comment]
just put it into https://github.com/Tribler/tribler/pull/4090

**Pull request closed without merging**
