### PR TITLE
Add typing to pricelevel_list.py

### PR DESCRIPTION
**Pull request by cclauss**
@devos50 @qstokkink @ichorid Just to get the sense of the changes required to add __typing__ to a file that is causing us some type-related issues...

__Tests on Mac__ is failing because we would need to __pip install typing__ on Python 2 (it is built-in in Python 3) and then add a __mypy__ test run to our builds.  https://mypy.readthedocs.io/en/latest/cheat_sheet.html

### CODE REVIEW

**Comment by qstokkink** [comment]
Seems workable, I like it.

**Comment by cclauss** [comment]
The type comments can go on the same line or on the next line so long lines should not be an issue.

**Comment by devos50** [comment]
retest this please

**Comment by cclauss** [comment]
retest this please

**Comment by cclauss** [comment]
retest this please

**Comment by cclauss** [comment]
retest this please

**Comment by cclauss** [comment]
retest this please

**Comment by cclauss** [comment]
retest this please

**Comment by cclauss** [comment]
retest this please

**Pull request merged**
