### PR TITLE
Various fixes for 7.4.0

### LINKED ISSUE #4779: RuntimeError: wrapped C/C++ object has been deleted
Version: 7.3.0
Platform: Windows-7-6.1.7601-SP1
Uptime:1687.55800009
Report: [26546](http://reporter.tribler.org/stacktrace/26546)

```python
Traceback (most recent call last):
File "TriblerGUI\dialogs\startdownloaddialog.py", line 142, in perform_files_request
RuntimeError: wrapped C/C++ object of type ClickableLabel has been deleted
```

### LINKED ISSUE #4842: Tribler settings is none - token mining page
```python
Traceback (most recent call last):
File "TriblerGUI\widgets\tokenminingpage.py", line 153, in on_received_downloads
TypeError: 'NoneType' object has no attribute '__getitem__'
```

### LINKED ISSUE #4843: Homepage - KeyError: 'torrents'
```python
Traceback (most recent call last):
File "TriblerGUI\widgets\homepage.py", line 81, in received_popular_torrents
KeyError: 'torrents'
```

### LINKED ISSUE #4851: NoneType object has no attribute 'checkpoint' - error when restarting credit mining torrent
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'checkpoint'
Tribler\Core\CreditMining\CreditMiningPolicy.py:243:run
Tribler\Core\Libtorrent\LibtorrentDownloadImpl.py:1027:restart
lib\site-packages\twisted\internet\defer.py:321:addCallback
lib\site-packages\twisted\internet\defer.py:310:addCallbacks
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:653:_runCallbacks
Tribler\Core\APIImplementation\LaunchManyCore.py:393:on_download_handle_created
]
```

### LINKED ISSUE #4859: Trust balance is not correct
Endpoint response is not consistent with what is expected in the GUI
trust-balance

### LINKED ISSUE #4868: Crash on version check failure
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.ValueError'>: No JSON object could be decoded
lib\site-packages\twisted\web\_newclient.py:1220:_bodyDataFinished_CONNECTED
lib\site-packages\twisted\web\client.py:2152:connectionLost
lib\site-packages\twisted\internet\defer.py:459:callback
lib\site-packages\twisted\internet\defer.py:567:_startRunCallbacks
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:653:_runCallbacks
Tribler\Core\Modules\versioncheck_manager.py:45:on_request_error
lib\site-packages\twisted\python\failure.py:346:trap
lib\site-packages\twisted\internet\defer.py:653:_runCallbacks
Tribler\Core\Modules\versioncheck_manager.py:40:parse_body
Tribler\Core\Utilities\json_util.py:126:loads
lib\json\__init__.py:339:loads
lib\json\decoder.py:364:decode
lib\json\decoder.py:382:raw_decode
]
```
Crash on version check failure
Report [#27491](http://reporter.tribler.org/stacktrace/27491)

### LINKED ISSUE #4869: Clicking on homepage torrents crashes Tribler on Python3
Clicking on homepage torrents crashes Tribler on Python3
```
ERROR   1569588508.20            tribler_window:108  (root)  Traceback (most recent call last):
  File "/home/tribler/tudelft/tribler/TriblerGUI/widgets/home_recommended_item.py", line 77, in on_download_button_clicked
    self.window().start_download_from_uri(self.download_uri)
  File "/home/tribler/tudelft/tribler/TriblerGUI/tribler_window.py", line 749, in start_download_from_uri
    self.dialog = StartDownloadDialog(self, self.download_uri)
  File "/home/tribler/tudelft/tribler/TriblerGUI/dialogs/startdownloaddialog.py", line 44, in __init__
    if torrent_name.startswith('file:'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

### PR DESCRIPTION
**Pull request by xoriole**
- Fixes #4851 
- Fixes #4843 
- Fixes #4842 
- Fixes #4779
- Adds python version to Debug/General
- Adds libtorrent version to Deug/General
- Fixes #4859
- Fixes #4869
- Fixes #4868

### CODE REVIEW

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
Metadata store test is failing occasionally
```
Tribler.Test.Core.Modules.MetadataStore.test_store.TestMetadataStore.test_squash_mdblobs
```
Error Message
```
'NoneType' object has no attribute 'to_dict'
-------------------- >> begin captured logging << --------------------
DEBUG   1569923934           store:MetadataStore:338  ('Added payload batch to DB (entries, seconds): %i %f', (21, 0.027991))
--------------------- >> end captured logging << ---------------------
```

**Comment by ichorid** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Pull request merged**
