### PR TITLE
TFTP with retry mechanism

### LINKED ISSUE #903: Finish remaining features for TFTP
In the future we will remove Libswift, as it is not sufficiently stable and too complex.

We will test TFTP protocol, from 22 years ago. (https://tools.ietf.org/html/rfc1350)

Priorities and steps:
- [x] integrate TFTP with rawserver.py
- [x] most basic service: single 1MByte hard-coded test file transfer
- [x] ability to serve small files from a given working directory
- [x] add a first and simple timeout
- [x] a downloader gets no response for 5 seconds, we timeout and abort
- [x] do a clean abort, use a temp file or something
- [x] only deliver fully downloaded files
- [x] Fancy timeout and retransmit mechanism
- [x] do a re-transmit of last data packet after 5 seconds, if no ACK is received
- [x] receiver has the ability to ignore duplicated data packets
- [x] simple and effective content correctnes
- [x] the filename contains or is equal to a SHA1 hash check
- [x] after file is downloaded, check the hash.
- [x] if it is incorrect, simply abort
- [x] we do not try to recover from this type of error, too complex

### PR DESCRIPTION
**Pull request by LipuFei**
DO NOT MERGE YET
Closes #903

### CODE REVIEW

**Comment by LipuFei** [comment]
@whirm I think it's ready, but this will break the old TFTP protocol because they are not compatible with each other, so we need a discussion before merging it.

**Comment by whirm** [comment]
Ok

**Comment by NielsZeilemaker** [comment]
Why is it incompatible?

**Comment by LipuFei** [comment]
I added a packet sequence number which doesn't exist in the old TFTP version, and it breaks the compatibility.

**Comment by NielsZeilemaker** [comment]
Why do you need a sequence number?

**Comment by LipuFei** [comment]
To know if an incoming packet is a re-sent or not. If we receive a re-sent packet and there is no sequence number, it is difficult to know whether it is a re-sent packet or the other person sent a wrong packet.

**Comment by NielsZeilemaker** [comment]
Explain "a wrong packet"

**Comment by LipuFei** [comment]
Wrong packet means a packet that is not what we are expecting or is not what we have seen before (a re-sent packet). Suppose we are expecting a DATA packet with data_id 20, and someone sends us a DATA packet with data_id 22, then this id 22 packet is wrong.

**Comment by NielsZeilemaker** [comment]
But would it cause any problems? I would expect a peer which receives a request for part 22 to reply with part 22. Even if I request it multiple times.

**Comment by LipuFei** [comment]
It is fine for DATA and ACK packets because they contain part numbers, but the negotiation packets that are sent in the beginning to initiate a request don't have sequence numbers. If we receive an old retransmitted negotiation packet, it is impossible to tell if it is a retransmission or a wrong packet. And that's why I added this sequence number.

I will think about it again to see if there is a better way to do it.

**Comment by NielsZeilemaker** [comment]
Let's not retransmit any negotiation packets then. Abort if negotiation failed else retransmit request.

**Comment by LipuFei** [comment]
ok

**Pull request closed without merging**
