### PR TITLE
Work around racy torrent removal function

### PR DESCRIPTION
**Pull request by whirm**

### CODE REVIEW

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
Looking good

**Comment by whirm** [comment]
retest this

**Comment by whirm** [comment]
retest this please

**Pull request merged**
