### PR TITLE
READY: Fixed token balance in the GUI

### PR DESCRIPTION
**Pull request by xoriole**

### CODE REVIEW

**Comment by qstokkink** [comment]
For convenience, failing test on Py 3 Win:

```
======================================================================
ERROR: test_squash_mdblobs_multiple_chunks
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\site-packages\twisted\internet\defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\site-packages\twisted\internet\utils.py", line 221, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\site-packages\twisted\python\compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\site-packages\twisted\internet\utils.py", line 217, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64_py3\tribler\Tribler\Test\test_as_server.py", line 66, in check
    result = fun(*argv, **kwargs)
  File "<string>", line 2, in test_squash_mdblobs_multiple_chunks
  File "c:\users\heteoma\appdata\local\programs\python\python37\lib\site-packages\pony\orm\core.py", line 528, in new_func
    result = func(*args, **kwargs)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64_py3\tribler\Tribler\Test\Core\Modules\MetadataStore\test_store.py", line 123, in test_squash_mdblobs_multiple_chunks
    skip_personal_metadata_payload=False)])
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64_py3\tribler\Tribler\Test\Core\Modules\MetadataStore\test_store.py", line 121, in <listcomp>
    [d[0].to_dict()["signature"]
AttributeError: 'NoneType' object has no attribute 'to_dict'
```

**Comment by xoriole** [comment]
This PR has nothing to do with the failing test. Metadata store tests are failing occasionally. Also reported in PR (https://github.com/Tribler/tribler/pull/4856)

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Pull request merged**
