### PR TITLE
Added anonymization support to TorrentChecker

### PR DESCRIPTION
**Pull request by egbertbouman**
Fixes https://github.com/Tribler/tribler/issues/5262.

This PR:
* Updates `Dispatcher` to allow multiple simultaneous connections to the tunnel SOCKS server. To achieve this, circuits are reserved for a particular SOCKS session.
* Adds `Socks5Client` that can be used for connecting to our `Socks5Server`. Both TCP and UDP are supported.
* Adds `Socks5Connector` that allows anonymous HTTP connections to be established using `aiohttp`.
* Adds anonymization support to `TorrentChecker`. The `TorrentChecker` now uses the default hop count for all traffic.
* Updates SOCKS5 client/server to use the IPv8 serializer.

### CODE REVIEW

**Comment by qstokkink** [comment]
Quick pytest fixture note. You can fix the `W0621` Pylint errors using this construction (this example exposes the name `ipv8` as a fixture):

https://github.com/Tribler/tribler/blob/9dfba003c74d004ba9452ef5e7d931ec00eb5497/src/tribler-core/tribler_core/modules/tests/test_ipv8_health_manager.py#L19-L20

**Comment by egbertbouman** [comment]
@qstokkink Thanks, will do!

**Review by qstokkink — APPROVED** [review]
Cool 👍

**Comment by egbertbouman** [comment]
I did some more testing. I've created a list of 28 HTTP trackers that are verified to be working. With some tweaking, I managed to successfully scrape 27 of them using the `TunnelCommunity`. The remaining one was redirecting to HTTPS (which we don't support).

**Comment by ichorid** [comment]
So, we now have working HTTP tunnelling in Tribler?

**Comment by egbertbouman** [comment]
@ichorid Yes, we do. That doesn't mean that it's possible to browse websites, though. HTTP tunneling is only allowed if the response is bencoded.

**Comment by egbertbouman** [comment]
retest this please

**Review by qstokkink — APPROVED** [review]

**Comment by egbertbouman** [comment]
retest this please

**Pull request merged**
