### PR TITLE
Made a Readme-file for Mageia

### PR DESCRIPTION
**Pull request by Umeaboy**
Signed-off-by: Kristoffer Grundström <kristoffer.grundstrom1983@gmail.com>

### CODE REVIEW

**Comment by whirm** [comment]
I don't see anything Mageia specific on that README, would you care explaining the purpose of this file?

Thanks!

**Comment by whirm** [comment]
Closing due to lack of feedback, please feel free to reopen if you are still interested.

**Comment by Umeaboy** [comment]
The purpose of this file is to start the port to Mageia.

**Comment by whirm** [comment]
That's great! 
Please, reopen the PR whenever you have something ready or need feedback about the approach taken.

Cheers!

**Pull request closed without merging**
