### PR TITLE
Fix key error on metainfo fetch

### LINKED ISSUE #6609: KeyError on get_metainfo()
Sentry Issue: [TRIBLER-A2](https://sentry.tribler.org/organizations/tribler/issues/982/?referrer=github_integration)

```
CreationTraceback: 
  File "src\run_tribler.py", line 213, in <module>
  File "src\tribler-gui\tribler_gui\utilities.py", line 395, in trackback_wrapper
  File "src\tribler-gui\tribler_gui\core_manager.py", line 97, in on_request_error
  File "src\tribler-gui\tribler_gui\core_manager.py", line 177, in start_tribler_core

RuntimeError: The Tribler core has unexpectedly finished with exit code -1073741819 and status: 1!

[PID:4932] 2021-11-30 21:48:21,729 - ERROR <rest_manager:52> tribler_core.restapi.rest_manager.error_middleware(): b' Kb:g"u\xd1\x8e-\x87\xf22\xdd\xc5N}\xabPS'
Traceback (most recent call last):
  File "src\tribler-core\tribler_core\restapi\rest_manager.py", line 45, in error_middleware
  File "lib\site-packages\aiohttp\web_middlewares.py", line 119, in impl
  File "src\tribler-core\tribler_core\modules\libtorrent\r...
  File "src\tribler-gui\tribler_gui\utilities.py", line 398, in trackback_wrapper
  File "src\tribler-gui\tribler_gui\utilities.py", line 395, in trackback_wrapper
  File "src\tribler-gui\tribler_gui\core_manager.py", line 87, in on_core_finished
```

### PR DESCRIPTION
**Pull request by xoriole**
Fixes #6609

### CODE REVIEW

**Comment by xoriole** [comment]
retest this please

**Review by kozlovsky — APPROVED** [review]

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Pull request merged**
