### PR TITLE
Torrent store implementation, tests and migration code

### LINKED ISSUE #1151: Unable to move the collected_torrent_files directory
v6.4.1, windows 8.1 x64

I have tried to move the TriblerDownloads folder repeatedly and somehow it always ends up back on my desktop (I want to move it to `D:\Users\joris_000\Downloads`). All my downloads go into my custom directory just fine.

Weird thing is that `D:\Users\joris_000\Downloads\collected_torrent_files` does get created and a few torrent files do end up there. 

Also, should the default directory not be something like `%LOCALAPPDATA%/Tribler/collected_torrent_files`

### PR DESCRIPTION
**Pull request by whirm**
Closes #1151

### CODE REVIEW

**Comment by whirm** [comment]
@LipuFei the tests are passing and it's working fine on my comp. Could you check this branch on your machine too?

**Comment by whirm** [comment]
@LipuFei not yet, I'm making it so the collected_torrent_files doesn't get created anymore

**Comment by whirm** [comment]
@LipuFei Ok, you can test it now :)

**Comment by LipuFei** [comment]
@whirm I will test it a bit before merging it.

**Comment by whirm** [comment]
@LipuFei maybe it would be a good idea to test it on windows and mac too, but we need to update the packaging scripts to bundle leveldb/python-leveldb

**Comment by whirm** [comment]
@LipuFei do you want to take care of that?

**Comment by LipuFei** [comment]
@whirm I will

**Comment by LipuFei** [comment]
@whirm I just tried to install leveldb on Windows. This is going to be a huge pain...

**Comment by whirm** [comment]
@LipuFei this one seems to work:
https://github.com/bitcoin/leveldb/blob/bitcoin-fork/WINDOWS.md

**Comment by LipuFei** [comment]
@whirm This one also needs a rebase.

**Comment by whirm** [comment]
retest this please

**Pull request merged**
