### PR TITLE
Fix Dispersy community statistics bug in debug pane

### PR DESCRIPTION
**Pull request by xoriole**
Fix Dispersy community statistics bug in debug pane

### CODE REVIEW

**Comment by qstokkink** [comment]
The [test_get_community_statistics](https://github.com/Tribler/tribler/blob/b096b9bf48a3ac815c104408f84259b639ac7014/Tribler/Test/Core/Modules/RestApi/test_statistics_endpoint.py#L37) appears to be segfaulting.

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Pull request merged**
