### PR TITLE
Esof

### PR DESCRIPTION
**Pull request by luisoliveira8**

### CODE REVIEW

**Comment by synctext** [comment]
ok to test

**Comment by whirm** [comment]
What is this?

**Comment by snorberhuis** [comment]
This seems to be the results of an assignment from students from another university that looked at the Tribler project and how it is developed.

I did something similar here at the TU Delft.

**Comment by whirm** [comment]
@synctext you decide what to do with it. :)

**Comment by whirm** [comment]
But if it is going to be merged, better to get it squashed together.

**Comment by devos50** [comment]
Maybe this document can be placed inside the `docs/` directory?

**Comment by whirm** [comment]
I don't really see why this should be merged.

**Comment by Pathemeous** [comment]
The report is honestly so generic that it has very little relation with Tribler.

**Comment by synctext** [comment]
Agreed, too generic at the moment.

**Comment by whirm** [comment]
Ok, I'm closing this then.

**Pull request closed without merging**
