### PR TITLE
Removed 'channel' term from filter terms

### PR DESCRIPTION
**Pull request by devos50**
This was messing up my tests lol...

### CODE REVIEW

**Comment by devos50** [comment]
@lfdversluis can you review?

**Comment by lfdversluis** [comment]
Well not much to review here, besides to comment that many terms can arguably be removed from this list. This approach is old-fashioned anyway :)

**Comment by devos50** [comment]
Yes I agree, there are more terms to be removed. Still, we should use a better algorithm for the family filter.

**Comment by devos50** [comment]
@whirm ready for your review.

**Comment by whirm** [comment]
lol

**Pull request merged**
