### PR TITLE
Upload binaries by default 

### PR DESCRIPTION
**Pull request by drew2a**
This PR enables uploading binaries for each PR by default.

### CODE REVIEW

**Review by qstokkink — APPROVED** [review]

**Review by xoriole — COMMENTED** [review]
- Should we actually be uploading the binaries by default?
- Does this have any potential to prolong the time taken for pull requests?

**Comment by drew2a** [comment]
> Should we actually be uploading the binaries by default?

I don't know. It is up to us to decide. I personally never use binaries from the PR builds.

> Does this have any potential to prolong the time taken for pull requests?

Yes. For example, for the Windows build it adds 2m 43s:
https://github.com/Tribler/tribler/actions/runs/6811621558/job/18522334331

image

**Comment by drew2a** [comment]
As an alternative approach, I could implement a condition where, if a PR has a specific label (such as 'upload binaries'), then the binaries would be uploaded.

**Comment by drew2a** [comment]
I'm closing this PR. The new PR with the add binaries for PR with the label #7689.

**Pull request closed without merging**
