### PR TITLE
READY: Implemented endpoint to fetch Tribler settings

### PR DESCRIPTION
**Pull request by devos50**
In this PR, I've implemented the next endpoint: getting the settings present in Tribler. The fact that we are using three different configuration files makes it harder to return a single JSON dictionary with all the settings. Nevertheless, this endpoint returns a single JSON dictionary that should contain all settings needed for the new GUI.

I also made some minor changes to other files. For instance, I created a static method `get_literal_value` in `configparser.py` and I've added a method in that class to return a configuration file as dictionary. Moreover, I've written a test to check the new settings endpoint and extended the documentation.

### CODE REVIEW

**Comment by devos50** [comment]
@lfdversluis ready for review

**Comment by whirm** [comment]
Don't you think it would be better to leave this one out until we refactor the config stuff so it's not insane anymore? 

Do you need to access the settings right now?

**Comment by devos50** [comment]
@whirm I don't think it's insane (only around 40 lines of code to return the dictionary I need) and I'm using it for the new GUI already so I would like to have this endpoint implemented :)

**Comment by whirm** [comment]
What's insane is the current configuration system in Tribler, not your code.

**Comment by devos50** [comment]
@whirm yeah it's absolutely insane and there are some duplicates in the config (and probably unused config options) but for now we have to deal with it. It was not that hard to actually return a single JSON dictionary and I'm sure we can do it in way less code once we have a proper configuration system.

Nevertheless, I would like to have this endpoint being part of the code. Also, I'm not sure when exactly I'm going to rewrite the configuration system (maybe around the time a 6.6 alpha is released?) and my main focus currently is the new GUI and the API in Tribler.

**Comment by whirm** [comment]
I don't like that you are mixing persisted values with runtime values with no way to tell them apart. I would rather have the configuration endpoint deal with the actual config (as in getting/setting -1 for random ports and suchlike) and have something else to obtain runtime values.

**Comment by whirm** [comment]
Also, saving this config would persist the randomized value.

**Comment by devos50** [comment]
@whirm what do you think about a separate endpoint to fetch the ports?

**Comment by whirm** [comment]
What about a generic interface for runtime variables?

**Comment by devos50** [comment]
@whirm that's ok but I'm not sure about the name for the endpoint. Do you have a suggestion?

**Comment by whirm** [comment]
`variables`? Maybe having events trigger whenever those variable change could be enough?

**Comment by devos50** [comment]
@whirm variables sounds ok. I will create a separate PR for it and remove the assignment in this PR.

**Comment by devos50** [comment]
@whirm see my last fixup commit.

**Comment by whirm** [comment]
Ok, squash it!

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
(that was due to a connection error on the mac)

**Comment by devos50** [comment]
@whirm ready (I also updated the dispersy pointer to include the netifaces fix)

**Pull request merged**
