### PR TITLE
WIP: Fixed issue with config convert for 7.4

### LINKED ISSUE #4959: Conversion of downloads 7.3.2 -> 7.4.0 is broken
Steps to reproduce:
(Linux) download a torrent in 7.3.2 (py2), then fire up 7.4.0 (py3). All the downloads will be gone.
```
ERROR   1574258838.18    LibtorrentDownloadImpl:801  (LibtorrentDownloadImpl)  Resume data failed to save: <class 'Tribler.Core.exceptions.SaveResumeDataError'>: torrent has no metadata
```

### PR DESCRIPTION
**Pull request by xoriole**
Fixed config convert for 7.4 from the base state directory instead of versioned state directory.
Fixes #4959

### CODE REVIEW

**Comment by xoriole** [comment]
retest this please

**Comment by ichorid** [comment]
@xoriole , could you please merge it instead into `release-7.4.0` branch, so we can later merge the changes into `devel`?

**Comment by xoriole** [comment]
> @xoriole , could you please merge it instead into `release-7.4.0` branch, so we can later merge the changes into `devel`?

Yes, sure

**Comment by xoriole** [comment]
retest this please

**Comment by ichorid** [comment]
Moved to #4965 to be based properly on `release-7.4.0`

**Pull request closed without merging**
