### PR TITLE
Refactored general except in startWorker

### PR DESCRIPTION
**Pull request by lfdversluis**

### CODE REVIEW

**Comment by lfdversluis** [comment]
I cannot cover the except besides overriding the `extract_stack` function of traceback. But this would require me saving the pointer to the function which we do not want to have in tests.

**Comment by lfdversluis** [comment]
@devos50 Can you review?

**Comment by devos50** [comment]
Looks ok to me

**Comment by whirm** [comment]
Squash it

**Comment by lfdversluis** [comment]
@whirm Ready for merge

**Pull request merged**
