### PR TITLE
Next to devel

### PR DESCRIPTION
**Pull request by whirm**

### CODE REVIEW

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
Jenkins: 'Build timed out (after 13 minutes). Marking the build as failed.'

**Comment by whirm** [comment]
It will never pass as `devel` is crippled. I was just checking if it introduced any new issues.

**Pull request merged**
