### PR TITLE
Report the address type we don't support

### LINKED ISSUE #1817: "Unsupported address type" on community/tunnel/Socks5/conversion.py:149
Found on a failed test run for #1783 

https://jenkins.tribler.org/job/GH_Tribler_pull-request-tester/5279/testReport/Tribler.Test.test_hidden_community/TestHiddenCommunity/test_hidden_services/

```
CRITICAL 1451298521         _legacy:twisted:154  Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 611, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/udp.py", line 248, in doRead
    self.protocol.datagramReceived(data, addr)
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester@2/tribler/Tribler/community/tunnel/Socks5/server.py", line 53, in datagramReceived
    request = conversion.decode_udp_packet(data)
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester@2/tribler/Tribler/community/tunnel/Socks5/conversion.py", line 221, in decode_udp_packet
    offset, destination_address = __decode_address(address_type, offset, data)
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester@2/tribler/Tribler/community/tunnel/Socks5/conversion.py", line 149, in __decode_address
    raise ValueError("Unsupported address type")
exceptions.ValueError: Unsupported address type
```

### PR DESCRIPTION
**Pull request by whirm**
So we can debug #1817

### CODE REVIEW

**Comment by whirm** [comment]
hm, the exception is not triggering now

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
these tests are passing when running locally, I'm investigating why they fail so much when running on bbq.

**Comment by whirm** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Pull request merged**
