### PR TITLE
Autopep8

### PR DESCRIPTION
**Pull request by whirm**
Let's wait for the outstaning pull requests and I'll redo this one

### CODE REVIEW

**Comment by LipuFei** [comment]
@whirm ready?

**Comment by whirm** [comment]
No, I want to fix some ugly stuff made by autopep

**Comment by LipuFei** [comment]
@whirm I canceled it. It has been blocking for a long time.

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
@whirm Looks good, it would probably pass. Shall we merge it?

**Comment by whirm** [comment]
@LipuFei I'm redoing some ugly stuff autopep made, I'm half way trough it.

**Comment by whirm** [comment]
I'm splitting this into several smaller ones, it got too big for a single PR

**Pull request closed without merging**
