### PR TITLE
READY: Adjust test_download_from_url to use a locally seeded torrent

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
@lfdversluis ready for review

**Comment by devos50** [comment]
@whirm I think the pylint checker is broken

**Comment by lfdversluis** [comment]
Why not rename the add peer function and add doc? Moving lines of code can cause conflict for others

**Comment by devos50** [comment]
@lfdversluis I'm not reusing the `add_peer_to_download` method in other tests so I made it a class method instead of an inline function.

**Comment by devos50** [comment]
@whirm can you review?

**Comment by lfdversluis** [comment]
Ah ok, good then

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
(to check this pylint issue)

**Pull request merged**
