### PR TITLE
Implementation and tests for the new torrent storage system.

### PR DESCRIPTION
**Pull request by whirm**
DO NOT MERGE YET

### CODE REVIEW

**Comment by LipuFei** [comment]
@whirm you can add a `@skip` to the metadata download test in `test_remote_torrent_handler.py`. We are not using it at the moment.

**Comment by LipuFei** [comment]
@whirm I think we need to redesign the Metadata community to integrate it into the ChannelCommunity, and if we do so, the code for downloading metadata will be changed a lot, so for now don't spend too much time on the stuff that is related to metadata.

**Comment by whirm** [comment]
@LipuFei yeah, I already had added it locally :) I'm having trouble with test_magnet_link, for some reason it just stalls...

**Comment by whirm** [comment]
@LipuFei Ok, I've got it: 
```
Traceback (most recent call last):
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/SearchGridManager.py", line 911, in _do_gui_callback
    callback(dslist, magnetlist)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/__init__.py", line 115, in invoke_func
    return func(*args, **kwargs)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/list.py", line 1883, in RefreshBandwidthHistory
    for item in self.list.items.itervalues():
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14615, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
PyDeadObjectError: The C++ part of the LibraryList object has been deleted, attribute access no longer allowed.
Traceback (most recent call last):
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/SearchGridManager.py", line 911, in _do_gui_callback
    callback(dslist, magnetlist)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/list_details.py", line 942, in OnRefresh
    self.torrent.magnetstatus = magnetlist.get(self.torrent.infohash, None)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14615, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
PyDeadObjectError: The C++ part of the TorrentDetails object has been deleted, attribute access no longer allowed.
Traceback (most recent call last):
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/SearchGridManager.py", line 911, in _do_gui_callback
    callback(dslist, magnetlist)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/list_details.py", line 942, in OnRefresh
    self.torrent.magnetstatus = magnetlist.get(self.torrent.infohash, None)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14615, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
PyDeadObjectError: The C++ part of the LibraryDetails object has been deleted, attribute access no longer allowed.
Traceback (most recent call last):
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/SearchGridManager.py", line 911, in _do_gui_callback
    callback(dslist, magnetlist)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/SRstatusbar.py", line 98, in RefreshTransferSpeed
    self.SetTransferSpeeds(total_down, total_up)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14615, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
PyDeadObjectError: The C++ part of the SRstatusbar object has been deleted, attribute access no longer allowed.
Traceback (most recent call last):
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/SearchGridManager.py", line 911, in _do_gui_callback
    callback(dslist, magnetlist)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/EmbeddedPlayer.py", line 179, in OnStatesCallback
    if not self.download:
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14615, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
PyDeadObjectError: The C++ part of the EmbeddedPlayerPanel object has been deleted, attribute access no longer allowed.
Traceback (most recent call last):
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/SearchGridManager.py", line 911, in _do_gui_callback
    callback(dslist, magnetlist)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/__init__.py", line 115, in invoke_func
    return func(*args, **kwargs)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/list.py", line 1780, in RefreshItems
    didStateChange, _, newDS = SizeList.RefreshItems(self, dslist, magnetlist, rawdata=True)
TypeError: unbound method RefreshItems() must be called with SizeList instance as first argument (got _wxPyDeadObject instance instead)
```

**Comment by whirm** [comment]
I fixed this and another issue and it still hangs..., time to start the debugger

**Comment by whirm** [comment]
yay, deadlock

```
(gdb) info threads 
  Id   Target Id         Frame 
  15   Thread 0x7f57440fd700 (LWP 12898) "gmain" 0x0000003060edd18d in poll () at ../sysdeps/unix/syscall-template.S:81
  14   Thread 0x7f570effd700 (LWP 12915) "nosetests" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  13   Thread 0x7f570e7fc700 (LWP 12916) "nosetests" 0x0000003060ee62a3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  12   Thread 0x7f570dffb700 (LWP 12917) "nosetests" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  11   Thread 0x7f5742575700 (LWP 12927) "nosetests" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  10   Thread 0x7f5741093700 (LWP 12928) "nosetests" 0x0000003060ee62a3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  9    Thread 0x7f570f7fe700 (LWP 12929) "nosetests" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  8    Thread 0x7f5741d74700 (LWP 12947) "nosetests" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 0x7f570d7fa700 (LWP 12948) "nosetests" 0x0000003060ee62a3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  6    Thread 0x7f570cff9700 (LWP 12949) "nosetests" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 0x7f56effff700 (LWP 12959) "nosetests" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  4    Thread 0x7f56ed412700 (LWP 12960) "nosetests" 0x0000003060ee62a3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  3    Thread 0x7f56ecc11700 (LWP 12961) "nosetests" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7f574d9f3700 (LWP 13006) "nosetests" sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
* 1    Thread 0x7f5750bfa700 (LWP 12884) "nosetests" sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
(gdb) 
```

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
@LipuFei I would say it's ready :)

**Comment by whirm** [comment]
closing this as I've created a new PR which includes the data migration code

**Pull request closed without merging**
