### PR TITLE
Fix a notifier problem

### LINKED ISSUE #1482: 'Session' object has no attribute 'uch'
When starting Tribler with 1 hidden seeding (1-hop) torrent in the library.
```
ERROR   1434551531.37             log:455   Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/pouwelse/GITHUB/tribler/Tribler/Core/Libtorrent/LibtorrentMgr.py", line 441, in <lambda>
    notify_reachability = lambda: self.trsession.uch.notify(NTFY_REACHABLE, NTFY_INSERT, None, '')
exceptions.AttributeError: 'Session' object has no attribute 'uch'
```

### PR DESCRIPTION
**Pull request by LipuFei**
Closes #1482

### CODE REVIEW

**Comment by LipuFei** [comment]
@whirm ready when it passes

**Comment by LipuFei** [comment]
@whirm Got it. It's the right one.
See http://jenkins.tribler.org/job/GH_Tribler_pull-request-tester_devel/4489/console

**Comment by whirm** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
@whirm It didn't fail due to some unexpected error, but the failure was reported twice on jenkins.

**Comment by whirm** [comment]
retest this please

**Comment by LipuFei** [comment]
@whirm I have removed the debug commits. Ready to merge when it passes.

**Comment by LipuFei** [comment]
@whirm ready

**Pull request merged**
