### PR TITLE
Fixed UnicodeDecodeError in the GUI

### LINKED ISSUE #5394: [7.5.0] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 108: invalid continuation byte
From the error reporter (happens on Windows):

```
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\core_manager.py", line 48, in on_core_read_ready
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 108: invalid continuation byte
```

This happens immediately on startup. The error points to the following line in `core_manager.py`:

```
print(raw_output.decode().strip())
```

### PR DESCRIPTION
**Pull request by devos50**
Fixes #5394

### CODE REVIEW

**Comment by devos50** [comment]
@ichorid is this targetted at the right branch?

**Comment by ichorid** [comment]
Indeed, this is pointed to the right branch. I should update developers guideline :facepalm:

**Comment by devos50** [comment]
Now, should I merge creating the merge commit or squash and rebase? 🤔

**Comment by ichorid** [comment]
There is only a single commit, so use "rebase and merge" option. No auto-squashing.

**Pull request merged**
