### PR TITLE
Remove Crypto.py and some other things

### PR DESCRIPTION
**Pull request by LipuFei**

### CODE REVIEW

**Comment by synctext** [comment]
2 passes and lot of fails..
Are tribler or Jenkins things unstable?

**Comment by LipuFei** [comment]
@whirm The regular tests passed and the isolated one also passed, but some thing went wrong with its Java XML parser, and that's why it failed.

Ready to be merged.

**Comment by synctext** [comment]
@LipuFei  @whirm Can you identify the exact problem with the Java XML parser + fix it?

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
fixed

**Comment by whirm** [comment]
retest this please

**Comment by LipuFei** [comment]
@whirm ready

**Pull request merged**
