### PR TITLE
Merge release-7.5 into devel

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by ichorid** [comment]
изображение

:facepalm: 

the merge must be done directly from `release-7.5` branch into `devel` branch, by hand in git. And pushed manually through the command line (with checking it as a PR of course). Otherwise, history becomes a complete mess and you can't merge stuff without conflicts anymore.


That's how it should look:
изображение

**Comment by devos50** [comment]
Ok, missed that one. Even though I really don't like to push directly to `devel`, if that is the best practice I will do it like that next time.

**Comment by qstokkink** [comment]
> if that is the best practice

The official Git best practice is (see https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows#ch05-distributed-git):
"make it as easy on you and the project maintainer as possible"

The Atlassian (Bitbucket) best practice (see https://www.atlassian.com/git/tutorials/merging-vs-rebasing) is:
"If you would prefer a clean, linear history free of unnecessary merge commits, you should reach for git rebase [...] if you want to preserve the complete history of your project and avoid the risk of re-writing public commits, you can stick with git merge"

I prefer the risk-averse approach in IPv8, but the Tribler clean-branch approach is also excellently documented by Atlassian. But, as usual: "it depends" is the answer to what your project-specific best practice should be. We've already has lengthy discussions on this topic 😃

**Comment by qstokkink** [comment]
Oh, by the way, I created issue #5409 specifically for this reason. If the branch merge magic is done automatically, there can be no mistakes with merging vs. rebasing.

**Pull request merged**
