### PR TITLE
PR for Giga Channel

### PR DESCRIPTION
**Pull request by xoriole**
This PR is targeted on fixing issues encountered while stabilizing the Giga Channel PR (#4090) and improving the code coverage.

- Fix adding a giga channel for credit mining

### CODE REVIEW

**Comment by devos50** [comment]
@xoriole `test_payout_e2e` is fixed if the base `gigachannels` branch is rebased on top of the latest commit on devel.

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Pull request merged**
