### PR TITLE
Python random is discouraged, move to secrets

### PR DESCRIPTION
**Pull request by NoNameForMee**
Some of the CI/CD jobs for Tribler already warns about this:
https://github.com/Tribler/tribler/runs/1913957805
https://sonarcloud.io/project/security_hotspots?id=Tribler_tribler&hotspots=AW_DWqEXH4jiAyAXJjGK

Official python doc:
https://docs.python.org/3/library/secrets.html
https://docs.python.org/3/library/random.html

Please note: I used `secrets.choise(range(min,max))` as this is somewhat
clearer than `secrets.randbelow(n)` which treats edge different from random..
(I.e. `secrets.randbelow` would have to have "`n=max-min+1`" and then add "`min`").

And also note: I did not remove the "`import random`",
as some lines could not be translated 1:1 with the new secrets.

Feel free to edit this merge request, discard it or merge it at your will...

### CODE REVIEW

**Comment by ichorid** [comment]
ok to test

**Comment by egbertbouman** [comment]
I'm not really seeing any issues with using `random`. Of course, `random` is only pseudo-random, but it's not like we're using it for anything security-related. If we decide to merge this, it would mostly be to silence the CI/CD jobs.

**Comment by qstokkink** [comment]
As I was requested for review: completely agree with @egbertbouman.
You pay the price in performance (roughly 1.5 times slower) if you use secure random numbers unnecessarily:

```python
>>> timeit.timeit("secrets.choice(range(255))", "import secrets")
0.9644661999999755
>>> timeit.timeit("random.choice(range(255))", "import random")
0.5771826999999803

>>> timeit.timeit("secrets.choice(range(65535))", "import secrets")
1.0464367000000152
>>> timeit.timeit("random.choice(range(65535))", "import random")
0.6713555999999983
```

_Disclaimer: if you use random numbers for security you absolutely need to use `secrets` or `os.urandom`._

**Comment by ichorid** [comment]
@qstokkink , @egbertbouman  do we use secure random generators for tunnels and private key generation?

**Comment by qstokkink** [comment]
@ichorid yes, always.

**Comment by ichorid** [comment]
> @ichorid yes, always.

Then I see no reasons for moving to `secrets`. 

Thanks for all the work done though, @NoNameForMee . We prefer to only change stuff if it makes a positive impact. Better luck next time :wink:

**Pull request closed without merging**
