### PR TITLE
READY: VSIDS-based channel rating system

### PR DESCRIPTION
**Pull request by ichorid**
This PR implements a [VSIDS](https://arxiv.org/pdf/1506.08905.pdf)-like heuristics for channel popularity.
In short, whenever a gossip with a channel is received, the corresponding vote count is increased by +1, and then *all the other votes* are **multiplied** by a constant *decay factor*. As a result, the heuristic works like a temporal PageRank, bumping the most actively spread around channels to the top.

The decay factor for this version is 2.71 per 24 hours of Tribler online time. This means that when some channel gets a vote today, tomorrow by the same time the vote will be 2.71x times smaller. The decay is performed on per-vote basis, meaning that it happens gradually over time, as the votes come in. The algorithm is O(1) in regards to the number of DB calls for each vote update.

We keep each individual vote in the DB, along with its last update time and the amount that it added to the total vote count for the channel. Whenever a repeating vote is received, the previous vote amount for the same vote is *subtracted* from the vote sum, and the new amount is added instead. This results in votes *refresh* instead of *accumulation*, meaning that a single peer cannot aggressively bump their channel by bombarding another peer with gossip. Instead, persistence in vote support is key.

### CODE REVIEW

**Comment by devos50** [comment]
Nice mechanism! 👍 

Dynamic decaying is something for next releases I guess?

**Comment by ichorid** [comment]
> Dynamic decaying is something for next releases I guess?
Most probably, yes. For this release, I'll have to work out the normalization and QT delegate for displaying the rating.

**Comment by synctext** [comment]
Great stuff!
Can you please schedule a performance evaluation? Like using 250k real votes from the old AllChannel and test the retrieval time plus vote magic cost. Nightly Gumby experiment is deemed useful?

**Comment by ichorid** [comment]
@synctext , I'll think about how to the experiment properly.

**Comment by ichorid** [comment]
Note that this breaks the database format. The old database should be removed manually unless we merge #4514 first, and then change this PR to use the beta-deletion method.

**Comment by devos50** [comment]
Adding an additional [validation experiment](https://jenkins-ci.tribler.org/job/validation_experiments/)] would indeed be helpful, not only for correctness at scale but also to have a solid foundation to run some performance/accuracy tests on more advanced voting mechanisms in the future.

**Comment by ichorid** [comment]
retest this please

**Pull request merged**
