### PR TITLE
WIP: integrates bloom filter in tribler (from py-ipv8)

### PR DESCRIPTION
**Pull request by jonay2000**
As far as i could see, this resolves all references to the bloom filter from pyipv8 and redirects them to an implementation in tribler. I am not completely sure where i should put it (it's in core now). Input is appreciated. As promised in https://github.com/Tribler/py-ipv8/pull/477

### CODE REVIEW

**Comment by devos50** [comment]
ok to test

**Comment by jonay2000** [comment]
oh whoops, i totally forgot to also add the tests from py-ipv8 for the bloom filter. Right now only the code itself is added (that is why coverage fails). Should i add now or wait until you figure out if it should be there at all / refactored (https://github.com/Tribler/py-ipv8/pull/477)

**Comment by qstokkink** [comment]
@devos50 as the market is still in, should we merge this now?

**Comment by devos50** [comment]
@jonay2000 could you move the Bloomfilter class to the `Tribler.community.market` module (since the market is the only component that actually uses the bloomfilter)?

Also, I will remove the market implementation from Tribler and add [the submodule](https://github.com/tribler/anydex) instead as soon as possible. 👍

**Comment by jonay2000** [comment]
I am currently on holiday so I'll try to get it done by Monday. I'm sorry.

**Comment by devos50** [comment]
Superseded by #4547

**Pull request closed without merging**
