### PR TITLE
Fix dialogs

### LINKED ISSUE #1167: anonymous download popup, bad overlay
On Ubuntu, latest next branch.

Failure to expand and overlaps with the OK and CANCEL button now.
failure_to_expand

### PR DESCRIPTION
**Pull request by LipuFei**
Fixes #1167

### CODE REVIEW

**Comment by LipuFei** [comment]
@whirm ready to be merged after it passes the tests.

**Comment by LipuFei** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by LipuFei** [comment]
Opened another PR #1170 for `next` instead.

**Pull request closed without merging**
