### PR TITLE
READY: Should not eat exception silently

### PR DESCRIPTION
**Pull request by kozlovsky**
It is better to not eat exceptions silently, as it can mask some problems.

### CODE REVIEW

**Review by drew2a — DISMISSED** [review]
Cool, thank you!

**Comment by qstokkink** [comment]
ok to test

**Comment by qstokkink** [comment]
Note that the purpose of this code is to communicate a message to the user no matter what goes wrong. Even in the event `xmessage` is not installed (notably arch linux), a message is at least printed to the terminal (line 60-61). With this change the source error is no longer communicated. I'd suggest moving line 60+61 to preceed the `try .. except`.

**Comment by drew2a** [comment]
@qstokkink correct. 

But if I understand the code correctly, the `text` (the source error) will be printed in both cases.

Moving `print line` to the beginning of `def _show_system_popup` function is a good idea. But in this PR @kozlovsky just fixed my misstep from: https://github.com/Tribler/tribler/pull/5552/files

**Comment by qstokkink** [comment]
> 
> 
> @qstokkink correct.
> 
> But if I understand the code correctly, the `text` (the source error) will be printed in both cases.
> 
> Moving `print line` to the beginning of `def _show_system_popup` function is a good idea. But in this PR @kozlovsky just fixed my misstep from: https://github.com/Tribler/tribler/pull/5552/files

If that is the intention, it is providing duplicate functionality: a secondary way to format the text in a print statement. In that case, I would recommend the same thing I suggested before and to also print the actual exception in the exception handler. In effect, what it was doing before.

**Review by qstokkink — APPROVED** [review]

**Comment by kozlovsky** [comment]
I moved the print statement above as @qstokkink suggested and removed try/except block

Also I use `platform.system()` instead of `os.name` as it looks like a correct way according to doc:
https://docs.python.org/3/library/platform.html#platform.system
https://stackoverflow.com/questions/1854/python-what-os-am-i-running-on

**Comment by qstokkink** [comment]
I like this solution, I'll quickly have it retested to see if the Windows GUI test failure is persistent.

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please.. seems like the Windows machine is experiencing abnormal slowdown.

**Comment by devos50** [comment]
add to whitelist

**Comment by kozlovsky** [comment]
retest this please

**Review by devos50 — APPROVED** [review]

**Comment by devos50** [comment]
@kozlovsky please prefix the PR with `READY` if it is ready for review/merge 👍 

Also, note that our tests are currently unstable, and the GUI tests on Windows are occasionally failing. We should do some proper investigation of this behaviour soonish.

**Comment by kozlovsky** [comment]
> please prefix the PR with `READY` if it is ready for review/merge

@devos50 you mean as a prefix of PR name, like `"[READY] ..."`?

Maybe it is more convenient to create PRs that are not ready as drafts?
https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by devos50** [comment]
@kozlovsky normally I try to look at that too, but in this case, I did not see that the PR was converted from a draft state into a non-draft state.

Thinking about this, different devs are using different approaches. I consider a PR ready if it is either prefixed with `READY` or when it converts to a non-draft state. We should opt for one approach: either use prefixes in the title or, as you suggest, use draft/non-draft states.

**Comment by kozlovsky** [comment]
retest this please

**Comment by drew2a** [comment]
@kozlovsky @devos50 from my point of view, prefixes were good way to sort `ready/draft` pull request until `draft pull requests` have been introduced.

Let's discuss it :)

**Pull request merged**
