### PR TITLE
Deal once and for all with all the CWD/PATH/PYTHONPATH/non-ASCII path issues

### PR DESCRIPTION
**Pull request by whirm**

### CODE REVIEW

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
@rjruigrok Any idea on why the test_hidden_community tests are failing all the time? I even tried checking out 6.5-RC1 In case we broke something and it fails there too (Circuits are built but no actual data transfer at all)

**Comment by rjruigrok** [comment]
@whirm I'll have a look tonight. :+1: But in the recent tests: I can't find a link to the test results, do I have to check the isolated ones?

**Comment by whirm** [comment]
@rjruigrok They failed a bunch of times in a row, so I started bisecting them locally to make sure I didn't break anything on the last few months. But I can't make it pass a single time on my local machine. It passed the last time it ran on Jenkins so I don't know what to say. Locally it creates circuits no data is ever transferred through them.

Let's forget about it for the time being and I'll try to come up with a reason why it always fails on my workstation when 6.5 is out.

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Pull request merged**
