### PR TITLE
Release 7.3.0 beta2

### PR DESCRIPTION
**Pull request by xoriole**

### CODE REVIEW

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by synctext** [comment]
Please add the latest PR from Egbert to the Beta2 if possible. OK to delay. Great to get some milage on the new tunnels.

**Comment by devos50** [comment]
@synctext IIRC, The Tribler codebase needs some changes (and a PR) first in order to support the new tunnel format.

**Comment by devos50** [comment]
@xoriole also, should we merge beta releases in the `master` branch? It might be helpful to only merge stable releases in `master`.

**Comment by xoriole** [comment]
Beta2 is released. Closing this PR.

**Pull request closed without merging**
