### PR TITLE
Added MacPorts to build instructions

### PR DESCRIPTION
**Pull request by Dmole**

### CODE REVIEW

**Comment by synctext** [comment]
ok to test

**Comment by devos50** [comment]
@Dmole why did you create a new PR just to squash? You can use an interactive rebase (`git rebase -i HEAD~<number of commits>`) and force-push to git ;)

Please rebase this branch and I will merge. Don't use the `update branch` button on Github for this please since that will create a merge commit.

**Comment by Dmole** [comment]
Rebased.

**Comment by devos50** [comment]
Thanks!

**Comment by devos50** [comment]
Also thanks for your contribution 👍

**Pull request merged**
