### PR TITLE
Added information about setting the PATH variable

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by whirm** [comment]
How come you have to add this paths? I would expect the python installer to leave you with a fully working installation.

**Comment by devos50** [comment]
Because @lfdversluis did not add his Python directory to his `PATH` so we had to fix that.

**Comment by lfdversluis** [comment]
(The installer offers this at the bottom of the list of packages, but it is disabled by default.)

**Comment by whirm** [comment]
@devos50 waiting for the installer comment as talked about in person.

**Comment by devos50** [comment]
Done.

**Comment by whirm** [comment]
Looks great, could you squash it together?

**Comment by devos50** [comment]
@whirm done

**Pull request merged**
