### PR TITLE
Removed wx code from tests

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by devos50** [comment]
```
Testing whether starting a download anonymously from an infohash works ... Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Core\Utilities\twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1194, in run
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Core\Libtorrent\__init__.py", line 27, in <lambda>
    lambda_f = lambda a = args, kwa = kwargs: invoke_func(*a, **kwa)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Core\Libtorrent\__init__.py", line 28, in invoke_func
    download.session.lm.threadpool.add_task(lambda_f, 1)
exceptions.AttributeError: 'NoneType' object has no attribute 'add_task'
```

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
@lfdversluis can you review?

**Comment by lfdversluis** [comment]
Happy to get rid of those! All is well in test-land.

**Comment by lfdversluis** [comment]
```
66.7% 	

    30: C0411: (wrong-import-order), : standard import "from threading import enumerate as enumerate_threads" comes before "from twisted.internet import interfaces"
    30: C0412: (ungrouped-imports), : Imports from package threading are not grouped
```

Now may be a good time?

**Comment by devos50** [comment]
Same error as first one

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
@whirm ready for your review

**Pull request merged**
