### PR TITLE
VLC Fix

### PR DESCRIPTION
**Pull request by xoriole**
Uses bundled VLC libs instead of searching inside VLC app in MacOS.

### CODE REVIEW

**Comment by devos50** [comment]
It seems the coverage diff check is not working as expected?

**Comment by qstokkink** [comment]
```
[Set GitHub commit status (universal)] PENDING on repos [] (sha:f04d7c5) with context:GH_Tribler_PR_Tests/PR_coverage_check
ERROR: Unable to find a build for artifact copy from: GH_Tribler_PR_Tests/PR_linux
Archiving artifacts
[Cobertura] Publishing Cobertura coverage report...

[Cobertura] Publishing Cobertura coverage results...

[Cobertura] Cobertura coverage report found.

[Set GitHub commit status (universal)] ERROR on repos [] (sha:f04d7c5) with context:GH_Tribler_PR_Tests/PR_coverage_check
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Notifying upstream projects of job completion
Unable to get pull request builder trigger!!
Setting status of 0836216e0ab0fa8af08bc8beb424db0efc74cd52 to FAILURE with url https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_coverage_check/750//artifact/coverage_report.html and message: 'This PR lowers the code coverage. Click here ->
 '
Using context: Combined coverage diff
Finished: FAILURE
```

Did a job name change?

**Comment by devos50** [comment]
@qstokkink yes we changed the names of jobs.

@xoriole could you restart the mac? GUI tests seem to timeout again.

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
seems coverage is working

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by qstokkink** [comment]
Do we still need the stream redirection?

**Comment by xoriole** [comment]
> Do we still need the stream redirection?

We don't need stream redirection. I'm removing it.

**Pull request merged**
