### PR TITLE
Fix for fd leak on Ubuntu 17.04

### LINKED ISSUE #3014: tribler opens too many files by default
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

next / 7.0 / bc8991f

##### Operating system and version: #####

ubuntu 17.04 zesty

##### Expected behavior: #####

running tribler does not negatively impact operation of rest of system

##### Actual behavior: #####

Some default to ubuntu 17.04 user level file descriptor limit is exhausted.

##### Steps to reproduce the behavior: #####

1) run tribler

2) let tribler run overnight, with trustchain ("multichain" in next) enabled with/without torrents 

3) try to run another application that requires some free file descriptors to function properly, like eog.
application fails complaining "too many open files".  Closing tribler frees up the fds and eog works fine afterwards.

ulimit :
open files                      (-n) 1024

themusicgod1@eva1:~$ lsof | grep -i 'python2.7' | wc -l
10358

While it might very well be that stock ubuntu 17.04 is living a little close to the edge of how many files can reasonably expected to run applications like tribler, at the same time tribler should run in environments where the settings are set low without causing interference with other programs.

##### Relevant log file output: #####

n/a

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #3014 

Confirmed fix for Ubuntu 17.04.

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
@devos50 I I am not mistaken, Windows' firewall is blocking the Windows GUI tests. Ready for review.

**Comment by devos50** [comment]
@qstokkink no, the deployment tests left an instance of Tribler running.

**Comment by devos50** [comment]
@qstokkink I assume you verified that the socket leak is gone?

**Comment by qstokkink** [comment]
@devos50 yes, the socket leak is confirmed gone.

retest this please

**Comment by devos50** [comment]
I can confirm that the bug is probably gone now (tested it in the Proxmox Ubuntu machine).

**Pull request merged**
