### PR TITLE
Fixes #2188, added test cases for byte formatting methods

### LINKED ISSUE #2188: "Balance:" does not collapse to megabytes unlike "Total:".
##### Tribler version/branch+revision: #####

b60d3b126ddfcafc2a939c32ca6b9a97a962f561 devel

##### Operating system and version: #####

Debian

##### Expected behavior: #####

`Total: 94.87 MB   Balance: -80.71 MB`

##### Actual behavior: #####

`Total: 94.87 MB   Balance: -80712.54 KB`

### PR DESCRIPTION
**Pull request by Captain-Coder**
Test cases just test the current behaviour. Refactoring size_format might be usefull after Qt transition.

### CODE REVIEW

**Comment by devos50** [comment]
@Captain-Coder Please not that this method will be removed when the wx GUI can be removed since formatting speed strings will be a task of the Qt GUI. See https://github.com/devos50/tribler/blob/qt-gui/TriblerGUI/utilities.py#L7 for my implementation. Feedback or improvements on that method would be appreciated :)

Also, regarding #2188, currently it is not worth to fix most of the open wx-related issues. We should however still take them in considerations since some of the GUI bugs might be caused by an error in the core of Tribler. These issues should be fixed however.

**Comment by whirm** [comment]
ready?

**Comment by Captain-Coder** [comment]
@devos50, I already figured I shouldn't fix WX issues, that is why I chose an issue without the WX tag on it. I was unsure if this general util thing was wx specific or not. Also doing this makes me look like i'm doing something :) 

@whirm, yes it is ready as far as I can tell, even the CI seems to agree that it is good to go. (That's a first for me)

**Comment by whirm** [comment]
@Captain-Coder remember to set the issue to READY or I'll probalby ignore it (I clicked on this one by chance).

**Pull request merged**
