### PR TITLE
Implemented the family filter in the API

### PR DESCRIPTION
**Pull request by devos50**
So we can hide inappropriate content in the GUI.

### CODE REVIEW

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
```
test_101 (Tribler.Test.Core.Video.test_vod.TestVideoOnDemand) ... Unhandled Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/tribler/Documents/workspace/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/Core/Utilities/twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/Users/tribler/Documents/workspace/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 509, in session_getstate_usercallback_target
    self.set_download_states_callback(usercallback, newgetpeerlist, when=when)
  File "/Users/tribler/Documents/workspace/workspace/GH_Tribler_PR_tests_mac/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 488, in set_download_states_callback
    self.threadpool.add_task(network_set_download_states_callback_lambda, when)
exceptions.AttributeError: 'NoneType' object has no attribute 'add_task'
```

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
Same error as above

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
Same error as above...

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by devos50** [comment]
Again, the `add_task` error

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
That's weird: when running nosetests locally, it reports coverage on the lines in the coverage report. Maybe nose gets confused about the continue statement? Anyway, the line has to be covered, otherwise the unit test cannot succeed.

**Pull request merged**
