### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by drew2a**
Related to #6352 #6512 #6840

This PR adds `libtorrent==1.2.15` to requirements.txt. 

This version of libtorrent has been tested on macOS, Linux, and Windows.

### CODE REVIEW

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
`Tests on Windows 64-bit` reported the following error:

```python
ImportError while loading conftest 'E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64_pytest\tribler\src\tribler\core\conftest.py'.
src\tribler\core\conftest.py:17: in <module>
    from tribler.core.components.libtorrent.download_manager.download_manager import DownloadManager
src\tribler\core\components\libtorrent\download_manager\download_manager.py:53: in <module>
    lt.create_ut_metadata_plugin,
src\tribler\core\components\libtorrent\utils\libtorrent_helper.py:17: in __getattr__
    raise ImportError('libtorrent library is not installed')
E   ImportError: libtorrent library is not installed
```

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
I'm testing hidden peer discovery by executing the following commands:

```python

export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4"
export PYTHONPATH=$PWD/tribler/src:${PYTHONPATH}
export EXPERIMENT_RUN_TIME=${duration}

cd $PWD/tribler
echo ---------------------------------------------------------------create venv
python3 -m venv ./venv
. ./venv/bin/activate

echo ------------------------------------------------------install requirements
python3 -m pip install --upgrade setuptools pip
python3 -m pip install --upgrade -r ./requirements-core.txt
python3 -m pip list

echo ------------------------------------------------------start the experiment
python3 ./scripts/experiments/tunnel_community/hidden_peer_discovery.py

export R_LIBS_USER=$R_LIBS_USER${R_LIBS_USER:+:}$HOME/R
R --no-save < ./scripts/experiments/tunnel_community/hidden_peer_discovery.r

echo -----------------------------------------------------------deactivate venv
deactivate
```

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by kozlovsky** [comment]
retest this please

**Comment by kozlovsky** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
libgcrypt20 has been installed on the Linux machine:
```shell
sudo apt install libgcrypt20-dev
```

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Review by kozlovsky — APPROVED** [review]

**Pull request merged**
