### PR TITLE
Catch OSError in on_http_request

### PR DESCRIPTION
**Pull request by egbertbouman**

### CODE REVIEW

**Comment by qstokkink** [comment]
`OSError: [Errno 28] No space left on device` 😃

**Comment by devos50** [comment]
Hmm... the Windows machine used for the unit tests has two partitions, `C:\` and `E:\`. Jenkins runs on `E:\` (which has plenty of space) but it seems that the libtorrent download is placed somewhere in `C:\`, hinting that libtorrent tests might be writing to somewhere outside the workspace?

**Comment by qstokkink** [comment]
@devos50 confirmed:

https://github.com/Tribler/tribler/blob/8f03f05cb2d6965ca9ea298426fd232614074848/src/tribler-core/tribler_core/modules/libtorrent/tests/test_stream.py#L246-L249

That is writing to a `mkstemp`. On Windows this is somewhere on the `C:` drive by default.

**Comment by qstokkink** [comment]
Possible fixes are to set the default [`tempdir`](https://docs.python.org/3/library/tempfile.html#tempfile.tempdir) globally or to change the test to use our usual test dir:

https://github.com/Tribler/tribler/blob/fd748afb85b2919cd58bf08c198c6260724edda0/src/tribler-core/tribler_core/tests/tools/common.py#L7

**Comment by devos50** [comment]
On Windows, we have another failure in the hidden seeding test:

```
Traceback (most recent call last):
  File "E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\pyipv8\ipv8\taskmanager.py", line 131, in done_cb
    future.result()
  File "E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\pyipv8\ipv8\messaging\anonymization\community.py", line 779, in on_extend
    await self.dht_peer_lookup(extend_candidate.mid, peer=extend_candidate)
  File "E:\jenkins\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\src\pyipv8\ipv8\messaging\anonymization\community.py", line 950, in dht_peer_lookup
    await self.dht_provider.peer_lookup(mid, peer)
TypeError: peer_lookup() takes 2 positional arguments but 3 were given
```

**Comment by devos50** [comment]
retest this please

**Comment by egbertbouman** [comment]
@devos50 I know, its a problem with `MockDHTProvider`.

**Comment by egbertbouman** [comment]
Apparently, the hidden services test was having intermittent crypto errors. Of course, the errors didn't show up in the logs, it only happened on Linux, and only when running the tests on Jenkins. Anyway, this is fixed now in IPv8. From now on, crypto errors like this will show up in the logs.

**Pull request merged**
