### PR TITLE
Updated the IPv8 pointer

### PR DESCRIPTION
**Pull request by qstokkink**
This PR upgrades Tribler to the latest IPv8 version.

### CODE REVIEW

**Comment by qstokkink** [comment]
I'm not sure what is wrong with `pytest / run (windows-latest)`.

**Comment by qstokkink** [comment]
>I'm not sure that introducing the CommunitySettings is an improvement. What is the necessity of this intermediate class, and what benefits does it provide over simply and directly passing arguments through the constructor?

This was introduced due to pylint/ruff's `PLR0913` violation triggering on the IPv8 codebase. Ruff's documentation includes a small example of the benefits: https://docs.astral.sh/ruff/rules/too-many-arguments/ If you want a deeper Software Engineering argument, there is a more elaborate write-up here: https://matheus.ro/2018/01/29/clean-code-avoid-many-arguments-functions/

The necessity comes from the fact that Tribler will not work anymore with the latest version of IPv8 without this change. However, you can always hotpatch in some dirty construction later if you really want to. For this PR, I'll stick to the recommended approach.

> Additionally, this PR introduces a new dependency (typing_extension). Could you elaborate on the advantages of using it and explain why native typing is insufficient?

`typing_extensions` is a collection of backports for native typing constructs but from future Python versions. So, in a sense, native typing IS sufficient BUT we are running a Python version that is too old. IPv8 uses `typing_extensions` for the backports of `Self` and `Protocol`.

**Comment by drew2a** [comment]
> Settings

Too many arguments in a function can sometimes be a signal, or 'smell,' of suboptimal code or design. While this might be true in some instances, it's not universally applicable. The number of function parameters should not serve as an absolute indicator necessitating refactoring.

In Tribler, some communities do indeed have numerous parameters, while others do not. Therefore, only a few communities in Tribler appear to be potential candidates for refactoring, not all of them.

In this context, I'd argue that the necessity for a specialized `Setting` object feels a bit like 'dictatorship' from the ipv8 side. Speaking as a developer who has crafted communities in Tribler and will continue to do so in the future, I find this approach unsavory as it introduces an unnecessary level of abstraction, will likely clutter the code, and doesn’t present any significant benefits.

Please consider amending ipv8 such that this feature becomes optional instead of mandatory.

> typing_extensions

I understand. If 'IPv8 uses typing_extensions for the backports of Self and Protocol,' then IPv8 should install this dependency during its installation. It should not depend on the target application (Tribler) to install all required libraries.

**Comment by qstokkink** [comment]
>In Tribler, some communities do indeed have numerous parameters, while others do not. Therefore, only a few communities in Tribler appear to be potential candidates for refactoring, not all of them.

`Community` has 5 arguments to `__init__`, `TriblerCommunity` adds a 6th one. ALL communities are over the Pylint recommended max of 5 arguments before they even start adding anything.

> I'd argue that the necessity for a specialized Setting object feels a bit like 'dictatorship' from the ipv8 side. 

Calling an API a dictatorship seems a bit overly dramatic but I guess I can agree to being a dictator: I don't think it's a bad thing to have an API.

> IPv8 should install this dependency during its installation. It should not depend on the target application (Tribler) to install all required libraries.

It does. However, Tribler redefines exact versions of dependencies that only appear in IPv8. I added this to be consistent.

---

I get the overall feeling that you are not favor of this PR, which is fine: I'm not here to force you to use anything and I'll just close it.

**Pull request closed without merging**
