### PR TITLE
png images: strip profiles

### PR DESCRIPTION
**Pull request by cheecheeo**
iCCP errors are being thrown by tribler. On the arch wiki the recommended solution
is:
```
convert -strip <input filename> <output filename>
```

Without this change, when running v6.4.3 I continually get these errors:
5bd3d558-28de-11e5-82d0-52e677d12ec0

Has this been fixed since v6.4.3 was released?

### CODE REVIEW

**Comment by synctext** [comment]
ok to test

**Comment by synctext** [comment]
test this please

**Comment by whirm** [comment]
@synctext you should be on the admin list now, try again.

**Comment by whirm** [comment]
Just as a comment: I already stripped the PNGs a while ago. I guess somebody modified them and forgot to strip them again?
@cheecheeo thanks for the PR BTW!

**Comment by synctext** [comment]
test this please

**Comment by whirm** [comment]
ok to test

**Comment by cheecheeo** [comment]
Thanks!

**Comment by whirm** [comment]
@cheecheeo thank you for the PR :)

**Pull request merged**
