### PR TITLE
Added ability to perform a memory dump to the debug pane

### PR DESCRIPTION
**Pull request by devos50**
This helps us to debug memory issues faster.

### CODE REVIEW

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by qstokkink** [comment]
I think what's failing in the Mac test is a packet coming in after the community has been unloaded, but before the endpoint is closed. This is due to the closing order in Dispersy (which I also ran into with IPv8) at:

https://github.com/Tribler/dispersy/blob/a68fbe7eba4a6542c8d64975ac0504a0cff5e5b6/dispersy.py#L1705-L1719

**Comment by devos50** [comment]
Hmm can we safely swap the closing order (first stop the endpoint and unload the communities afterwards)?

Also, I need to put the thread printing before the assertion error. If the assert triggers, the stacks do not get printed.

**Comment by devos50** [comment]
retest this please

**Comment by qstokkink** [comment]
@devos50 no this is not an easy fix, we can't just switch the order. Some communities send messages when unloaded (for instance the TunnelCommunity). We would need to implement a two phase endpoint shutdown: first disable receiving on the endpoint, then unload the communities and lastly disable sending on the endpoint.

**Comment by devos50** [comment]
@qstokkink I don't think it's related to Dispersy since in the test that went wrong in the Mac build (https://jenkins.tribler.org/job/GH_Tribler_PR_tests_mac/4914/artifact/output/test_runners_output/0.err/*view*/), I don't even start Dispersy.

There are some more instances where we schedule stuff on the thread pool, for instance, our download callback, which might cause this issue. Still, it never gave any problems like this. I will create a separate issue for this and merge this PR.

**Comment by qstokkink** [comment]
@devos50 yes that's a different issue (I was looking at the failed run before that)

**Pull request merged**
