### PR TITLE
WIP: market community

### PR DESCRIPTION
**Pull request by mitchellolsthoorn**
Market community acting as a stock exchange for exchanging multi chain bytes against bitcoin

### CODE REVIEW

**Comment by synctext** [comment]
add to whitelist

**Comment by synctext** [comment]
retest this please

**Comment by mitchellolsthoorn** [comment]
@whirm can you mark this PR for tests on jenkins?

**Comment by synctext** [comment]
add to whitelist

**Comment by whirm** [comment]
add to whitelist

**Comment by lfdversluis** [comment]
Hey guys, I noticed the PR testsers fail with `No module named bintrees`. The bintrees module does not appear to be available on the official repos of debian (and therefore ubuntu). We do have the requirement as we are packaging Tribler. For reference: https://packages.debian.org/search?suite=stable&section=all&arch=any&searchon=names&keywords=bintrees

**Comment by mitchellolsthoorn** [comment]
@lfdversluis thx,  I will try to include it as a submodule.

**Comment by whirm** [comment]
Is that dependency really needed?

**Comment by mitchellolsthoorn** [comment]
@whirm we use one class from that library for the orderbook data structure. So fhe matching engine can easily search it

**Comment by synctext** [comment]
retest this please

**Comment by devos50** [comment]
@whirm I don't think we are going to merge this anytime soon since it needs a major cleanup of the commit history and a rebase. Also, it does not provide direct functionality to Tribler. Should we close this PR?

**Pull request closed without merging**
