### PR TITLE
Remove prctl import from LaunchManyCore

### PR DESCRIPTION
**Pull request by vandenheuvel**
I removed the import of `prctl` as it isn't used.

### CODE REVIEW

**Comment by vandenheuvel** [comment]
@devos50 You can have a look at [this](https://github.com/seveas/python-prctl/blob/master/prctl.py). I believe some names are being set, but I still don't think this should be in production code. Is it a good idea to add a comment to the docs and remove this code?

**Comment by devos50** [comment]
@vandenheuvel see https://github.com/Tribler/tribler/issues/7. Apparently, it was used to set thread names. I'm pretty sure that it can be removed. If we run into any problems, we revert this commit but I don't think we will.

**Comment by synctext** [comment]
Please ensure threads have names. Quite essential for debugging.

**Comment by synctext** [comment]
never mind. thnx for clearing the junk..

**Pull request merged**
