### PR TITLE
Remove is_unit_testing and fix the tests using it.

### LINKED ISSUE #1067: is_unit_testing is set to False on some tests
This doesn't make sense and it's misleading.

### PR DESCRIPTION
**Pull request by whirm**
Closes #1067

### CODE REVIEW

**Comment by whirm** [comment]
@LipuFei ready to merge if it passes

**Comment by LipuFei** [comment]
@whirm Need rebase.

**Comment by LipuFei** [comment]
retest this please

**Comment by whirm** [comment]
@LipuFei dont' bother, it still is broken, I'm working on it.

**Comment by whirm** [comment]
@LipuFei Ok, that should fix it

**Pull request merged**
