### PR TITLE
update dispersy ref.

### PR DESCRIPTION
**Pull request by whirm**

### CODE REVIEW

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
@LipuFei I send a pull request to @whirm fixing this branch. It needed some modification to both Tribler and Dispersy

**Comment by NielsZeilemaker** [comment]
@whirm the new dispersy puts a wrapper around the M2Crypto.EC object, hence some methods need to be changed.
Basically, stuff like this line:
https://github.com/Tribler/tribler/blob/next/Tribler/community/tunnel/crypto/tunnelcrypto.py#L69
Needs to be
```
member._ec.key instead of member._ec
```
So have a look for _ec in the tunnel stuffs and replace them by _ec.key

**Comment by NielsZeilemaker** [comment]
Oh, its _ec.ec

**Comment by NielsZeilemaker** [comment]
And btw, whats happening with all those sessionpoolthreads?
```
INFO    1420544776.23  LaunchManyCore:706   tlm: Thread still running=SessionPoolThread-232, daemon=True, instance=<ThreadPoolThread(SessionPoolThread-232, started daemon 139751452047104)>
INFO    1420544776.23  LaunchManyCore:706   tlm: Thread still running=SessionPoolThread-251, daemon=True, instance=<ThreadPoolThread(SessionPoolThread-251, started daemon 139750147524352)>
INFO    1420544776.23  LaunchManyCore:706   tlm: Thread still running=SessionPoolThread-343, daemon=True, instance=<ThreadPoolThread(SessionPoolThread-343, started daemon 139748228196096)>
INFO    1420544776.24  LaunchManyCore:706   tlm: Thread still running=SessionPoolThread-249, daemon=True, instance=<ThreadPoolThread(SessionPoolThread-249, started daemon 139750164309760)>
INFO    1420544776.24  LaunchManyCore:706   tlm: Thread still running=SessionPoolThread-247, daemon=True, instance=<ThreadPoolThread(SessionPoolThread-247, started daemon 139750181095168)>
INFO    1420544776.24  LaunchManyCore:706   tlm: Thread still running=SessionPoolThread-245, daemon=True, instance=<ThreadPoolThread(SessionPoolThread-245, started daemon 139750197880576)>
INFO    1420544776.24  LaunchManyCore:706   tlm: Thread still running=SessionPoolThread-243, daemon=True, instance=<ThreadPoolThread(SessionPoolThread-243, started daemon 139750214665984)>

**Comment by whirm** [comment]
@NielsZeilemaker What do I replace the EC.load_key() with in permid.py:read_keypair()? it makes key_to_bin to assert because it still is an EC.EC instead of DispersyKey

**Comment by NielsZeilemaker** [comment]
@whirm my fix is gone btw, it not going to work without it

**Comment by NielsZeilemaker** [comment]
That's fixed by the pull request I sent you, it uses M2CryptoSK(filename=...)

**Comment by whirm** [comment]
Oh, sorry, I overwrote the history (my office branch was out of sync as I worked from home these last dasy)

**Comment by NielsZeilemaker** [comment]
@whirm i'll have a go at fixing this tonight, I guess some of the ecutils stuff needs to be modified slightly.

**Comment by NielsZeilemaker** [comment]
@whirm I send you a pull request which fixed the unit-tests for me

**Comment by synctext** [comment]
This is the yet another elaborate NielsPersy/Dispersy enhancement. Too much for upcoming 6.4.2 bugfix release, pushing it forward.

**Comment by NielsZeilemaker** [comment]
This one is done, the other one is a wip

**Comment by NielsZeilemaker** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
retest this please

**Pull request closed without merging**
