### PR TITLE
WIP: Fix test blockage

### PR DESCRIPTION
**Pull request by whirm**
Detect whenever an event loop or thread has blocked and act accordingly.

DO NOT MERGE YET

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
@whirm btw have a look at this file
https://github.com/Tribler/tribler/blob/devel/Tribler/Main/tribler_lockprofiler.py

maybe you can use it to see whose calling what

**Comment by whirm** [comment]
@NielsZeilemaker maybe it should be separated so it's explicit.

**Comment by whirm** [comment]
> @whirm btw have a look at this file
> https://github.com/Tribler/tribler/blob/devel/Tribler/Main/tribler_lockprofiler.py
> 
> maybe you can use it to see whose calling what

I will, thanks!

**Comment by NielsZeilemaker** [comment]
The test tunnel still has a reference to self.Call

**Comment by whirm** [comment]
@NielsZeilemaker oops, my fault I overlooked that when rebasing. Thx

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
@whirm the torrent_checker.shutdown is blocking on the reactor thread, but doesn't use a timeout value for the join https://github.com/Tribler/tribler/blob/devel/Tribler/Core/TorrentChecker/torrent_checker.py#L129

The torrent_checking thread itself accesses the database through the reactor thread, and hence it might cause a deadlock.

I would add a timeout value on the join, or remove the blocking decorator.

**Comment by whirm** [comment]
@NielsZeilemaker I'll have a look

**Comment by whirm** [comment]
@NielsZeilemaker this whole thing should be twistified, the thread is calling stuff on the reactor, so we are not getting anything out of running the rest on it's own thread. I'm thinking I'll just make it a loopingCall that selects the sockets on the pool.

**Comment by NielsZeilemaker** [comment]
Make an issue out of it, but for now I would add the timeout. 

I know @LipuFei spend quite some time fixing/changing the torrent_checker and I think finally it has been running somewhat smoothly. I wouldn't start messing with it if I were you.

**Comment by LipuFei** [comment]
@whirm @NielsZeilemaker I think `LoopingCall` is a possible solution. I don't mind changing that. Just make sure that `select` doesn't block the reactor thread and choose an appropriate LoopingCall interval so that tracker sessions don't time out too much.

**Comment by whirm** [comment]
@LipuFei the loopingcall interval would be very short as the task would spend most of the time waiting in the threadpool for the select() timeout to happen or some data to get in.

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Pull request closed without merging**
