### PR TITLE
Added fedora instructions

### PR DESCRIPTION
**Pull request by Mechazawa**

### CODE REVIEW

**Comment by az-z** [comment]
@NielsZeilemaker ,
 i see the issue is closed. I was under impression you are looking into this (fedora port). Please let me know.

**Comment by NielsZeilemaker** [comment]
I'll have another go with Fedora 21 to see if I can get Tribler up and running.

**Comment by NielsZeilemaker** [comment]
Unfortunately it's a no go, we can modify Tribler to get it running using the keys @fabianhjr mentioned. However, the master member keys (those used as an identifier for the communities) don't load and cannot load as the curves are not supported.

**Comment by az-z** [comment]
Neils,
 what are these "master keys"?
//sorry i'm of my league on this subject.
Maybe a better question is - what are the requirements (per package) on OS
? My line of thinking iseither to open the ticket with RH team or follow-up
on the existing tickets,

**Comment by NielsZeilemaker** [comment]
It's a bit complex, but it's a part of the decentralized  permission system tribler is using. 
We can't change these keys to the ones which do work on fedora, as they are used as identifiers and changing them won't allow you to discover other peers using tribler.

**Comment by az-z** [comment]
Will those that work in fedora work in other system?

**Comment by NielsZeilemaker** [comment]
It will, but we cant easily switch to a new type of identifier

**Comment by az-z** [comment]
What other diatributions that do not support these keys or its only rh?

**Comment by NielsZeilemaker** [comment]
I think it's only redhat, but you just needs to recompile openssl with the ecckeys enabled to get it working.

**Comment by az-z** [comment]
Neil,
so @ this point the above instructions are comments are outdated - such as m2crypto etc.
in other words - all i need to do is to recompile the openssl package with ecckeys enabled ?
and if the above statment correct (about openssl) , how do i enable ecckeys? 
The latest openssl-1.0.1k-1.fc21 is been compiled as 
./Configure \
        --prefix=%{_prefix} --openssldir=%{_sysconfdir}/pki/tls ${sslflags} \
        --system-ciphers-file=%{_sysconfdir}/crypto-policies/back-ends/openssl.config \
        zlib enable-camellia enable-seed enable-tlsext enable-rfc3779 \
        enable-cms enable-md2 no-mdc2 no-rc5 no-ec2m no-gost no-srp \
        --with-krb5-flavor=MIT --enginesdir=%{_libdir}/openssl/engines \
        --with-krb5-dir=/usr shared  ${sslarch} %{?!nofips:fips}

**Comment by az-z** [comment]
@NielsZeilemaker 
i pocked around a bit.
Does this package have all what is required ?
https://github.com/ptudor/centos6-openssl/commit/0d47cbdf595c0991751114664f62c57914131bda

**Comment by NielsZeilemaker** [comment]
I'm not sure, we're using sect curves which seem to be missing from that list. But have a go,  if you get null pointers in m2 crypto then you know there is still a problem with openssl

**Comment by az-z** [comment]
@NielsZeilemaker 
how about this 
[code]
<mock-ch/opt/openssl-compat-bitcoin/bin/openssl ecparam -list_curves
  secp112r1 : SECG/WTLS curve over a 112 bit prime field
  secp112r2 : SECG curve over a 112 bit prime field
  secp128r1 : SECG curve over a 128 bit prime field
  secp128r2 : SECG curve over a 128 bit prime field
  secp160k1 : SECG curve over a 160 bit prime field
  secp160r1 : SECG curve over a 160 bit prime field
  secp160r2 : SECG/WTLS curve over a 160 bit prime field
  secp192k1 : SECG curve over a 192 bit prime field
  secp224k1 : SECG curve over a 224 bit prime field
  secp224r1 : NIST/SECG curve over a 224 bit prime field
  secp256k1 : SECG curve over a 256 bit prime field
  secp384r1 : NIST/SECG curve over a 384 bit prime field
  secp521r1 : NIST/SECG curve over a 521 bit prime field
  prime192v1: NIST/X9.62/SECG curve over a 192 bit prime field
  prime192v2: X9.62 curve over a 192 bit prime field
  prime192v3: X9.62 curve over a 192 bit prime field
  prime239v1: X9.62 curve over a 239 bit prime field
  prime239v2: X9.62 curve over a 239 bit prime field
  prime239v3: X9.62 curve over a 239 bit prime field
  prime256v1: X9.62/SECG curve over a 256 bit prime field
  sect113r1 : SECG curve over a 113 bit binary field
  sect113r2 : SECG curve over a 113 bit binary field
  sect131r1 : SECG/WTLS curve over a 131 bit binary field
  sect131r2 : SECG curve over a 131 bit binary field
  sect163k1 : NIST/SECG/WTLS curve over a 163 bit binary field
  sect163r1 : SECG curve over a 163 bit binary field
  sect163r2 : NIST/SECG curve over a 163 bit binary field
  sect193r1 : SECG curve over a 193 bit binary field
  sect193r2 : SECG curve over a 193 bit binary field
  sect233k1 : NIST/SECG/WTLS curve over a 233 bit binary field
  sect233r1 : NIST/SECG/WTLS curve over a 233 bit binary field
  sect239k1 : SECG curve over a 239 bit binary field
  sect283k1 : NIST/SECG curve over a 283 bit binary field
  sect283r1 : NIST/SECG curve over a 283 bit binary field
  sect409k1 : NIST/SECG curve over a 409 bit binary field
  sect409r1 : NIST/SECG curve over a 409 bit binary field
  sect571k1 : NIST/SECG curve over a 571 bit binary field
  sect571r1 : NIST/SECG curve over a 571 bit binary field
  c2pnb163v1: X9.62 curve over a 163 bit binary field
  c2pnb163v2: X9.62 curve over a 163 bit binary field
  c2pnb163v3: X9.62 curve over a 163 bit binary field
  c2pnb176v1: X9.62 curve over a 176 bit binary field
  c2tnb191v1: X9.62 curve over a 191 bit binary field
  c2tnb191v2: X9.62 curve over a 191 bit binary field
  c2tnb191v3: X9.62 curve over a 191 bit binary field
  c2pnb208w1: X9.62 curve over a 208 bit binary field
  c2tnb239v1: X9.62 curve over a 239 bit binary field
  c2tnb239v2: X9.62 curve over a 239 bit binary field
  c2tnb239v3: X9.62 curve over a 239 bit binary field
  c2pnb272w1: X9.62 curve over a 272 bit binary field
  c2pnb304w1: X9.62 curve over a 304 bit binary field
  c2tnb359v1: X9.62 curve over a 359 bit binary field
  c2pnb368w1: X9.62 curve over a 368 bit binary field
  c2tnb431r1: X9.62 curve over a 431 bit binary field
  wap-wsg-idm-ecid-wtls1: WTLS curve over a 113 bit binary field
  wap-wsg-idm-ecid-wtls3: NIST/SECG/WTLS curve over a 163 bit binary field
  wap-wsg-idm-ecid-wtls4: SECG curve over a 113 bit binary field
  wap-wsg-idm-ecid-wtls5: X9.62 curve over a 163 bit binary field
  wap-wsg-idm-ecid-wtls6: SECG/WTLS curve over a 112 bit prime field
  wap-wsg-idm-ecid-wtls7: SECG/WTLS curve over a 160 bit prime field
  wap-wsg-idm-ecid-wtls8: WTLS curve over a 112 bit prime field
  wap-wsg-idm-ecid-wtls9: WTLS curve over a 160 bit prime field
  wap-wsg-idm-ecid-wtls10: NIST/SECG/WTLS curve over a 233 bit binary field
  wap-wsg-idm-ecid-wtls11: NIST/SECG/WTLS curve over a 233 bit binary field
  wap-wsg-idm-ecid-wtls12: WTLS curvs over a 224 bit prime field
  Oakley-EC2N-3: 
	IPSec/IKE/Oakley curve #3 over a 155 bit binary field.
	Not suitable for ECDSA.
	Questionable extension field!
  Oakley-EC2N-4: 
	IPSec/IKE/Oakley curve #4 over a 185 bit binary field.
	Not suitable for ECDSA.
	Questionable extension field!
[/code]

**Comment by NielsZeilemaker** [comment]
The curves seem to be there.

**Comment by az-z** [comment]
@NielsZeilemaker 
what else i need to check? Or i can just install the package and tribler will pick them (curves) up ?

**Comment by NielsZeilemaker** [comment]
You need to convince m2crypto to use this version of openssl. Or replace the default openssl completely.

**Comment by almereyda** [comment]
Now, why not also sending a Pull Request to upstream? I believe RPM world
could have its use for the additional crypto Tribler requires.

**Comment by az-z** [comment]
@almereyda Jon, i think there is a conflict between feature request (from this application) and lawyers from redhat. easy to understand that latter wins.
@NielsZeilemaker ,
 ill not be participating in this further unfortunately. Due to concerns in https://lists.torproject.org/pipermail/tor-dev/2014-December/007999.html

**Comment by synctext** [comment]
@az-z
We are very much aware of that negative review on the Tor mailing list.
All mentioned issues have been fixed or should be addressed soon.

As a university research team we're very committed to fix all concerns and have the needed crypto expertise in the team. However, improvements take costly development time.
A nuanced follow-up can be read here: https://github.com/Tribler/tribler/issues/1066

Our darknet roadmap for coming years is here: https://github.com/Tribler/tribler/issues/3

**Comment by bam80** [comment]
Maybe someone gives it another try, please?

**Comment by sbadux** [comment]
It would be great to have a rpm package. I'm not using Tribler because I'm on Fedora and it's not available

**Comment by devos50** [comment]
I remember that we had quite some issues with `M2Crypto`. However, that dependency is long gone and the move to Python 3 might also resolve some dependency issues.

Unfortunately, our development time is scarce and we have to prioritise. Adding Fedora support would mean yet another platform to maintain, besides Windows/Mac/Debian/Ubuntu, which we already have our hands full with.

That said, as a first step we could try to setup a Fedora machine and try to install all required dependencies to run Tribler. We have some plans in the pipeline to do so with arch linux already.

**Comment by sbadux** [comment]
> I remember that we had quite some issues with `M2Crypto`. However, that dependency is long gone and the move to Python 3 might also resolve some dependency issues.
> 
> Unfortunately, our development time is scarce and we have to prioritise. Adding Fedora support would mean yet another platform to maintain, besides Windows/Mac/Debian/Ubuntu, which we already have our hands full with.
> 
> That said, as a first step we could try to setup a Fedora machine and try to install all required dependencies to run Tribler. We have some plans in the pipeline to do so with arch linux already.

You may consider a distro-agnostic package like AppImage or Flatpak. It may solve a lot of problems but I'm not a developer so I don't know if it's difficult to create such kind of packages

**Comment by bam80** [comment]
+1 for distro-agnostic package like AppImage or Flatpak. Then you could drop distro-specific efforts altogether and just support Linux in a whole.

**Pull request closed without merging**
