### PR TITLE
Merge mds module and component

### PR DESCRIPTION
**Pull request by drew2a**
This PR contains location changes of files from the metadata_store module.

The new structure: https://github.com/drew2a/tribler/tree/feature/merge_mds/src/tribler-core/tribler_core/components/metadata_store

image

Addresses #6335

### CODE REVIEW

**Review by ichorid — CHANGES_REQUESTED** [review]
The gigachannel community-related files must be placed along with the gigachannel community component, not with MDS.

Also, DB-related tests, such as `test_metadata`, must be placed close to DB code, e.g. in `metadata_store/db/tests`

**Comment by drew2a** [comment]
@ichorid

**Comment by drew2a** [comment]
@ichorid 
>The gigachannel community-related files must be placed along with the gigachannel community component, not with MDS.
Also, DB-related tests, such as test_metadata, must be placed close to DB code, e.g. in metadata_store/db/tests

Fixed. Internals of MDS are quite intertwined, so I tried my best to split them into components.
But it is not the intention of the PR. The intention of the PR is to merge MDS module and MDS component.

If you find other misplaced internals, please move them on your own.

**Comment by drew2a** [comment]
retest this please

**Review by ichorid — APPROVED** [review]

**Pull request merged**
