### PR TITLE
Add Tribler translation to Spanish

### PR DESCRIPTION
**Pull request by Manuel-Senpai**
Hi:
I have translated Tribler to Spanish, I have uploaded the files "es_ES.ts" and "es_ES.qm "and also the web file "https://github.com/Tribler/tribler#readme" renamed as "README.es.rst", if everything is ok, I hope you can include them in the next version. 
Best regards

### CODE REVIEW

**Comment by synctext** [comment]
| <translation>Conexiones máximas por descarga</translation>

Thnx for that X-mas contribution! This seems like days of work?

**Comment by Manuel-Senpai** [comment]
Hi guys:
Sorry for the question, I'm a newbie in Gibhub and I have no idea about programming or how this goes, can the translation be added to Tribler? or is there something wrong and I have to change it, I tell you I'm very lost here.... ;-)

**Comment by Manuel-Senpai** [comment]
Hi guys:
Sorry for the question, I'm a newbie in Gibhub and I have no idea about programming or how this goes, can the translation be added to Tribler, is there something wrong and I have to change it, I tell you I'm very lost around here..... ;-)

**Review by kozlovsky — CHANGES_REQUESTED** [review]
@Manuel-Senpai thank you for this translation!

We cannot add the Spanish README translation, as it would be very hard to maintain README in multiple languages. It is already a bit obsolete and needs to be updated from the English version, so it does not worth having it.

But the other files look good! For us to be able to accept the PR, you need to rebase it against the current main branch, remove the README translation, and move other files to `src/tribler/gui/i18n` subdirectory. Can you do it? Or, I can do it for you.

**Comment by Manuel-Senpai** [comment]
Hi @kozlovsky:
Better if you do it... I don't want to break anything, hahaha, I've been trying to delete the "README.es.rst" and I still don't quite understand the steps.... 
Tell me if you need any data to do it
Best regards

**Comment by kozlovsky** [comment]
Thank yuo @Manuel-Senpai, the translation was merged in #7246

**Pull request closed without merging**
