### PR TITLE
Implemented variables endpoint

### PR DESCRIPTION
**Pull request by devos50**
This PR implements the endpoint to fetch runtime-defined variables.

### CODE REVIEW

**Comment by devos50** [comment]
@lfdversluis ready for review

**Comment by lfdversluis** [comment]
Return runtime-defined variables used by the current Tribler session > Returns
Looks good to me

**Comment by devos50** [comment]
Fixed. @whirm can you review?

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
Looks fine, squash

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
(to see if I fixed diff-violations)

**Comment by devos50** [comment]
Also, any suggestion for the next endpoint? :D

**Comment by whirm** [comment]
Upgrade downloader?

**Comment by devos50** [comment]
@whirm you mean that the next version of Tribler is downloaded automatically in the background when there is a new version available? I think that should be implemented as an extension of the `VersionCheckManager`.

**Comment by whirm** [comment]
Yes, but you will need an endpoint to trigger the update, right? But yeah, let's leave this for later.

**Pull request merged**
