### PR TITLE
Update Tribler development on Windows.md

### PR DESCRIPTION
**Pull request by lfdversluis**
- Removed build tools as they do not install required distributions
- Added dependency walker explanation in case something is not installed by Visual Studio (if someone deselected something)

### CODE REVIEW

**Comment by whirm** [comment]
Please, add the link to the dependencies instead of telling people to use google.

**Comment by lfdversluis** [comment]
@whirm That varies what the user is missing, in our case we missed two of them. If more are required in the future, we continuously have to edit this file. The point is: MVS2015 should have all of them shipped.

**Comment by synctext** [comment]
you oncountered two cases of missing DLLs, however only one is listed in this commit. As Elric indicated, list them and approach to fix/download location.

**Comment by whirm** [comment]
@lfdversluis exactly, every time the dependencies change, we need to update the related documentation as we have done until now :)

**Comment by lfdversluis** [comment]
@whirm ready to merge if you agree

**Comment by whirm** [comment]
Squash it and I'll merge

**Comment by lfdversluis** [comment]
@whirm This can be merged btw

**Pull request merged**
