### PR TITLE
Convert the Tribler core tests to pytest

### LINKED ISSUE #5572: Tribler tests should use the succeed/fail from IPv8
It seems that the `succeed` and `fail` methods are defined twice, in `utilities.py` and in IPv8. Since IPv8 is already a dependency of IPv8, we should use the methods from IPv8 and remove the definitions from Tribler.

### PR DESCRIPTION
**Pull request by devos50**
In this PR, I converted the Tribler core tests to use `pytest`, instead of our custom scripts in the Gumby repository.

## Why pytest?

[pytest](https://docs.pytest.org/en/stable/) is a powerful and flexible testing framework, compared to existing, older ones that we used to integrate (e.g., nose and trial). A key feature of pytest is the ability to define fixtures, small modules that can be loaded in each test. This, for example, enables developers to enable the HTTP API in a test by passing an additional parameter. This saves much code since we do not have to load the same objects over and over in different test suites. Additional advantages of pytest include:
- The ability to define a default timeout for all tests. This addresses #5459.
- Native support for the parallel execution of tests.
- Native support for creating code coverage reports that are compatible with our existing Jenkins tools.
- Improved test readability since we do not have to embed tests within a class.

## What is included in this PR?

This PR refactors all tests in the `tribler_core` package to a pytest-compatible format. Most of the fixtures can be found in the `conftest.py` file and are used by the tests.

While converting the tests, I managed to refactor many of the tests that were unnecessarily starting a libtorrent session. This addresses issue #5501 and significantly improved the executing of the test suite, compared to our “old” test base. We only start libtorrent for the tests that really need it, e.g., the anonymous download/hidden seeding tests. Moreover, I found various tests that were not effectively testing anything. If applicable, I removed or heavily modified such tests. I also removed a few duplicate tests, improved docstrings where needed, and fixed a few tests that were writing assets in our test directory. Finally, I converted a few `path_util` instances to use the `pathlib` library instead, partially addressing #5030. I also fixed #5572.

I believe that these changes and improvements will contribute to a more stable unit test suite and quicker development cycles.

## Test speedup

I performed some runs to see what the speedup of `pytest` is. Note that the hidden seeding test is not working yet, which will most likely bump up this duration by a few seconds. I found that the duration of a full execution of the `pytest` test suite **is around 20 seconds** (while utilising 12 cores). This is significantly faster compared to our old test suite, which can take up to four minutes on Windows.

## How stable are the tests?

The tests seem to be pretty stable, which can be addressed to two changes. First, since we avoid starting libtorrent in most tests, there are less resources being consumed by the tests, leading to more stable behaviour and less interference with other tests. Second, I added a few retry mechanisms when starting specific components such as the REST API and HTTP tracker.

To find flaky tests, I used `pytest-flakefinder`. As I also reported in my master thesis, Tribler has a long history of flaky tests and we never really addressed this issue, besides for disabling the failing tests and spamming "retest this please" on our pull requests. I executed the plugin on our test base, which runs each test 50 times. This deployment revealed various dependencies between tests, which I fixed.

## TODO list

There are a few open items before this PR can be considered complete:
- [x] Make sure that the tests work on all supported platforms.
- [x] Generate code coverage reports.
- [x] Install the required dependencies on our machines.
- [x] ~~Refactor the streaming tests.~~ I do not think it is worth to do this since the `Stream` class is already covered by other tests. Still, I will make a separate issue for this.
- [x] Fix the API streaming test in the download tests.
- [x] Add bash/batch scripts to quickly run the unit tests.
- [x] Add testing etiquette to the contributing guidelines (e.g., no unnecessary libtorrent sessions).
- [x] Fix the hidden seeding test (asked @egbertbouman).
- [x] Fix the failing GUI tests.
- [x] Create a Jenkins job to find flaky tests (see [here](https://jenkins-ci.tribler.org/job/Test_tribler_devel_flake_finder/)).
- [x] Update Jenkins PR jobs to use `pytest` -> I have created separate jobs for the pytest runners, and integrated them in our main Jenkins build.
- [x] Fix remaining flake8/pylint errors.

## Reviewing this PR

Reviewing this PR is not for the faint-hearted. The modifications are invasive and the diffs are hard to review.

Note that I made a few changes to the main code base here and there. I tried my best to cover these changes, which was easy to do since they are usually touched by the test that I was currently working on. Please review the changes to the main code base carefully. Any advice on how to make better use of the pytest primitives is appreciated!

[Jenkins pytest job (Linux)](https://jenkins-ci.tribler.org/job/pers/job/pytest_linux_devos50/)
[Jenkins pytest job (Mac)](https://jenkins-ci.tribler.org/job/pers/job/pytest_mac_devos50/)
[Jenkins pytest job (Windows)](https://jenkins-ci.tribler.org/job/pers/job/pytest_win_devos50/)

### CODE REVIEW

**Comment by devos50** [comment]
I have been playing a bit with some pytest plugins.

The `pytest-flakefinder` plugin, originally developed by Dropbox, is extremely useful to detect flaky tests (tests that sometimes fail due to randomness/system interference). As I also reported in my master thesis, Tribler has a long history of flaky tests and we never really addressed this issue, besides for disabling the failing tests and spamming "retest this please" on our pull requests. I executed the plugin on our test base, which runs each test 50 times. This deployment revealed various dependencies between tests, which I fixed. For now, there seem to be two flaky tests left (which can hopefully be addressed by @ichorid):

```
FAILED tribler-core/tribler_core/modules/metadata_store/tests/test_store.py::test_squash_mdblobs[10]
FAILED tribler-core/tribler_core/modules/metadata_store/tests/test_store.py::test_squash_mdblobs_multiple_chunks[3]
FAILED tribler-core/tribler_core/modules/metadata_store/tests/test_store.py::test_squash_mdblobs_multiple_chunks[18]
FAILED tribler-core/tribler_core/modules/metadata_store/tests/test_store.py::test_squash_mdblobs_multiple_chunks[39]
```

The `pytest-randomly` plugin allows us to run all unit tests in a random order. This is helpful for detecting hidden dependencies between tests. I have enabled this behaviour by default. Note that each run reports a random seed and we can easily replay a specific run to further debug bugs. Running `pytest-flakefinder` in combination with `pytest-randomly` revealed more failures which I will debug next.

**Comment by ichorid** [comment]
like, wow! I thought I fixed the stuff for good by using fixed random seeds...

**Comment by ichorid** [comment]
I'll still wait for your to finish this, not to interfere with your work. I'll reopen the issues for the squash test.

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by qstokkink** [comment]
I believe you can get rid of all the `W0621` errors by explicitly setting the `name` in the `@pytest.fixture` definitions: https://docs.pytest.org/en/stable/reference.html#pytest-fixture-api

**Comment by devos50** [comment]
This PR is ready from my side for a review 👍

**Review by ichorid — APPROVED** [review]

**Comment by ichorid** [comment]
Blind approve.
Merge at will.

**Comment by qstokkink** [comment]
Is it expected that https://jenkins-ci.tribler.org/job/Test_tribler_devel_flake_finder/ has no successful runs?

**Comment by devos50** [comment]
@qstokkink yes that is expected for now. That Jenkins job runs every test 50 times (while randomising the order of the tests) and there are still a few tests that are flaky (e.g., the mdblob tests). A single failing test causes the job to fail already.

We can look at these nasty edge cases later but for now, I consider the main unit test jobs stable enough 👍

**Review by qstokkink — APPROVED** [review]
Oof. That's a lot of lines. Seems sane though.

I'd prefer coming up with a uniform way of defining fixtures, such that Pylint doesn't flip its shit with 10M `W0621` and `W0613` warnings. But, that can be in a separate PR.

**Pull request merged**
