### PR TITLE
Fixed spelling errors in documentation

### LINKED ISSUE #2711: Fix spelling errors in the documentation
The spelling checker on the PRs has uncovered some spelling errors in the documentation which should be fixed:

<ul>
<li>./CONTRIBUTING.rst</li>
<ul>
<li>submiting</li>
</ul>
<li>./README.rst</li>
<ul>
<li>commiting</li>
</ul>
<li>./doc/building/building_on_windows.rst</li>
<ul>
<li>executeable</li><li>packes</li>
</ul>
<li>./doc/development/development_on_linux.rst</li>
<ul>
<li>respecive</li>
</li>
</ul>
<li>./doc/development/development_on_windows.rst</li>
<ul>
<li>pakets</li><li>stuctures</li>
</ul>
<li>./doc/development/development_on_osx.rst</li>
<ul>
<li>
acccess</li>
</ul>
</ul>

### LINKED ISSUE #2719: Detect PR documentation spelling regression
Right now the documentation spelling checker only compiles a report of the spelling errors in a PR's documentation. Ideally we would like to have this fail if the amount of spelling errors increases.

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #2711, resolves #2719

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
@devos50 Ready for review. Results of failed spelling check here (proof of resolving #2719):
https://jenkins.tribler.org/job/GH_Tribler_PR_spelling_check/23//artifact/output/spelling_report.html

**Comment by devos50** [comment]
Very nice addition, thanks! 👍

**Pull request merged**
