### PR TITLE
Use libtorrent bencode instead

### PR DESCRIPTION
**Pull request by LipuFei**

### CODE REVIEW

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
@whirm ready. Don't know why the TimedTaskQueue tests are getting those errors. Have any idea?

**Comment by whirm** [comment]
maybe the test is broken and it's actually failing?

**Comment by whirm** [comment]
haven't looked at it

**Comment by LipuFei** [comment]
@whirm I tested the TimedTaskQueue test at home and I didn't get those errors. Strange

**Comment by LipuFei** [comment]
@whirm I didn't do anything and now it works fine. Weird.

**Comment by whirm** [comment]
some racy stuff maybe? I would ignore it as my PR is rewriting the whole thing.

**Comment by LipuFei** [comment]
@whirm anyway, I will ignore it. ready. :)

**Comment by synctext** [comment]
Why is our family filter on when doing ``Tribler.Test.test_remote_search.TestRemoteQuery.test_channelsearch`` ?
``DEBUG   1425637740.83    FamilyFilter:58    Torrent is XXX: ``

**Comment by LipuFei** [comment]
@synctext It was always on.

**Comment by LipuFei** [comment]
@synctext I will disable it in another PR.

**Comment by whirm** [comment]
@LipuFei can you drop the debug commit first?

**Comment by LipuFei** [comment]
@whirm done

**Pull request merged**
