### PR TITLE
fix callback from main thread

### PR DESCRIPTION
**Pull request by brussee**
@whirm gui callback on WxThread

### CODE REVIEW

**Comment by brussee** [comment]
```
Regression

Tribler.Test.test_remote_search.TestRemoteTorrentSearch.test_remote_torrent_search (from nosetests)
Failing for the past 1 build (Since Failed#2535 )
Took 30 sec.
add description
Error Message

Test raised 1 unhandled exceptions, last one was: AttributeError("'NoneType' object has no attribute 'magnet_close'",)
```
https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/2535/testReport/junit/Tribler.Test.test_remote_search/TestRemoteTorrentSearch/test_remote_torrent_search/

**Comment by whirm** [comment]
Let's wait for #2443 to get merged and then re-run this one.

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
We are in a roll here! :D

**Pull request merged**
