### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by whirm**

### CODE REVIEW

**Comment by whirm** [comment]
@synctext, @Pathemeous, @devos50, @snorberhuis & co.: I'll wait to merge this until tomorrow in case anybody wants to suggest corrections/improvements/clarifications.

**Comment by devos50** [comment]
Looks fine! Maybe also add that the `.Tribler` directory lives in `~/.Tribler` on Linux/OS X?

**Comment by snorberhuis** [comment]
:+1:

**Comment by whirm** [comment]
Thanks guys

**Pull request merged**
