### PR TITLE
Removed packages that are no longer used by Tribler

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by whirm** [comment]
Update `debian/control` and check that both the windows and osx build scripts won't break if this is missing.

**Comment by devos50** [comment]
@whirm the OS X build script was not using the `gmpy` library as dependency. The Windows build also succeeds.

**Comment by whirm** [comment]
@devos50 you missed `Tribler/Main/Build/Win32/setuptribler.py`

**Comment by devos50** [comment]
That one is removed by the Windows builder PR of @lfdversluis, shall I also remove it in this PR?

**Comment by whirm** [comment]
Yeah, let's do all of it at once.

**Comment by devos50** [comment]
done.

**Comment by lfdversluis** [comment]
Looks like I'm going to get a conflict :-1:

**Comment by synctext** [comment]
You removed 1 package: python-gmpy
I vaguely recall that this was an optional package which dramatically improved the performance of crypto operations.

**Comment by devos50** [comment]
@synctext it is not imported anywhere (also not in Dispersy) so this dependency is not used.

I also recall that It was used to speed up arithmetic operations but apparently it got removed somewhere in the development process. Not sure about the reason why though.

**Comment by synctext** [comment]
OK, thnx for quickly checking.

**Comment by whirm** [comment]
I've checked and no dependency of Tribler recommends this either. If I remember correctly that was used in @NielsZeilemaker's custom-made crypto stuff that was later replaced with python-cryptography

**Pull request merged**
