### PR TITLE
Tooling enhancements

### PR DESCRIPTION
**Pull request by xoriole**
Added support for detailed community statistics

### CODE REVIEW

**Comment by xoriole** [comment]
A screenshot of aggregate IPv8 statistics in Tribler debug pane
ipv8_statistics

**Comment by qstokkink** [comment]
@xoriole hmm your TriblerTunnel and MarketCommunity statistics are a bit worrying. Is the tracker still up?

**Comment by synctext** [comment]
Do we know the punture-request, etc type and puncture effectiveness?
btw please make RC2 ready when its ready..

**Comment by xoriole** [comment]
Five minutes stats:
debug_pane_ipv8_general
debug_pane_ipv8_overlays
@qstokkink 
> hmm your TriblerTunnel and MarketCommunity statistics are a bit worrying. Is the tracker still up?

Yes, tracker should be up but I think IPv8 peer statistics is not accurate.
>Also, why is the DHT community using a third peer?!

How do you infer that?

@synctext 
>Do we know the punture-request, etc type and puncture effectiveness?

Yes, we have statistics of all the message types, just need to update the GUI. That will be in a separate 'details' tab.

> btw please make RC2 ready when its ready..

Yes, will do. I want this PR also in RC2.

**Comment by xoriole** [comment]
Detail statistics snapshot
ipv8_detail_statistics

**Comment by synctext** [comment]
Great tooling progress!

**Pull request merged**
