### PR TITLE
Removed GUI-only tests

### PR DESCRIPTION
**Pull request by devos50**
These tests are only testing our GUI and can be removed.

### CODE REVIEW

**Comment by devos50** [comment]
Tunnel tests timed out... anyway, I only removed tests. @lfdversluis can you review?

**Comment by lfdversluis** [comment]
Alright, part one of many steps towards Vietnam. Nothing much to comment here except a question: do you have something like this on QT? (I believe so)

**Comment by devos50** [comment]
Yes, I have a set of automated GUI tests where screenshots are taken.

**Comment by devos50** [comment]
@whirm can you review?

**Comment by whirm** [comment]
retest this please

**Comment by devos50** [comment]
anon tests timed out

**Comment by devos50** [comment]
retest this please

**Pull request merged**
