### PR TITLE
Set socket reuseaddr to true while checking free port

### PR DESCRIPTION
**Pull request by xoriole**
Fixes https://github.com/Tribler/tribler/issues/7847

### CODE REVIEW

**Comment by drew2a** [comment]
Nice improvement. Could you educate me a bit and share how this change fixes the issue?

**Comment by xoriole** [comment]
> If the local application dies while a connection is active, the port will be tied up in TIME_WAIT. This is also true if the application dies while a connection is pending.
> TIME_WAIT is the state that typically ties up the port for several minutes after the process has completed.

@drew2a Here is a nice write-up about `Bind: Address Already in Use` issue
https://hea-www.harvard.edu/~fine/Tech/addrinuse.html

image

**Comment by drew2a** [comment]
Thank you for the article!

I now understand that you modified `NetworkUtils.is_port_free()` to allow it to return TRUE for ports that are in the `TIME_WAIT` status.

**Review by drew2a — CHANGES_REQUESTED** [review]
Allowing `NetworkUtils.is_port_free()` to return TRUE for ports that are in the TIME_WAIT status leads to two consequences:
1. It allows the GUI to reuse a port that is in `TIME_WAIT` status (which solves the issue with the Application Tester).

https://github.com/Tribler/tribler/blob/becc7277c966e344e7be37d5c0598064890587d5/src/tribler/gui/tribler_window.py#L166-L170

2. It allows `NetworkUtils.get_random_free_port()` and `NetworkUtils.get_first_free_port()` to use ports in `TIME_WAIT` status.

Both cases are risky as there could be a third-party application (not Tribler) that is leaving the port in `TIME_WAIT` to restore it later.

Although this fix resolves the issue with the Application Tester, it could lead to more severe problems in production.

I suggest solving the problem by using a random port for each consecutive Application Tester run (currently, it uses `20100` all the time).

**Comment by xoriole** [comment]
I have implemented another PR https://github.com/Tribler/tribler/pull/7859 as an alternative solution to the current PR. 
Closing this PR in favor of https://github.com/Tribler/tribler/pull/7859.

**Pull request closed without merging**
