### PR TITLE
Fix Ubuntu 21.04+ startup issue

### PR DESCRIPTION
**Pull request by xoriole**
Fixes https://github.com/Tribler/tribler/issues/6701

### CODE REVIEW

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Review by kozlovsky — APPROVED** [review]

**Review by kozlovsky — APPROVED** [review]

**Pull request merged**
