### PR TITLE
Added a minimum size of the window to Tribler

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
hm, apparently I did a one-line mistake during the rebase of next_to_devel, which wasn't catched on my PR, I'll fix it.

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by lfdversluis** [comment]
retest this please

**Pull request merged**
