### PR TITLE
Update development_on_linux.rst

### LINKED ISSUE #7811: pip3 error: externally-managed-environment
**Describe the bug**
pip3 error: externally-managed-environment

**To Reproduce**

1. Put Debian 12 in a VM
2. Try https://tribler.readthedocs.io/en/latest/development/development_on_linux.html#debian-ubuntu-mint
3. Report documentation bug

**Expected behavior**
Documentation should use one of the options listed in the pip3 error, or Not list Debian as an option.

**Desktop (please complete the following information):**

- OS: Debian 12
- Tribler's version: master

**Additional context**
```
pip3 install --upgrade -r tribler/requirements.txt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```

### PR DESCRIPTION
**Pull request by Dmole**
Debian 12

This PR fixes #7811

### CODE REVIEW

**Comment by drew2a** [comment]
This PR fixes #7811

**Comment by xoriole** [comment]
@Dmole Tribler currently does not work with 3.10 (+?). See: https://github.com/Tribler/tribler/issues/7728

I would prefer if you could update the PR to use pyenv and Python3.9 instead.

**Comment by Dmole** [comment]
kozlovsky has a fix, and headless is not using QT, so maybe supporting default versions on modern OSs can be realized...

**Comment by qstokkink** [comment]
After the most-recent GUI rework, I no longer think this PR is relevant and I will close it.

**Pull request closed without merging**
