### PR TITLE
Fixed bug when broadcasting upgrade tick

### PR DESCRIPTION
**Pull request by devos50**
Causing problems when the upgrader has to do work :(

### CODE REVIEW

**Comment by devos50** [comment]
@lfdversluis can you review?

**Comment by lfdversluis** [comment]
Weird, was this one of our changes? Can you write a test for this function to prevent it failing in the future?

**Comment by devos50** [comment]
@lfdversluis I've added that in one of my latest PRs (where I extended the events endpoint with various more types). I found it out by starting with a fresh `.Tribler` directory.

Also, I've added a test. Can you review again?

**Comment by lfdversluis** [comment]
Looks good.

**Pull request merged**
