### PR TITLE
Check if threadpool is None

### LINKED ISSUE #2340: twisted_utils.py: reactor.threadpool is NoneType
Since #2323 on startup of twisted plugin on Android:

```
 Unhandled Error
 Traceback (most recent call last):
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/base.py", line 417, in fireEvent
     DeferredList(beforeResults).addCallback(self._continueFiring)
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/defer.py", line 317, in addCallback
     callbackKeywords=kw)
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
     self._runCallbacks()
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
     current.result = callback(current.result, *args, **kw)
 --- <exception caught here> ---
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/internet/base.py", line 430, in _continueFiring
     callable(*args, **kwargs)
   File "/data/user/0/org.tribler.android/files/tribler_plugin.py", line 93, in start_tribler
     upgrader = self.session.prestart()
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Session.py", line 192, in prestart
     self.upgrader.run()
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Upgrade/upgrade.py", line 39, in run
     failed, has_to_upgrade = self.check_should_upgrade()
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/dispersy/util.py", line 46, in helper
     return blockingCallFromThread(reactor, func, *args, **kargs)
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/dispersy/util.py", line 225, in blockingCallFromThread
     return f(*args, **kwargs)
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Upgrade/upgrade.py", line 97, in check_should_upgrade
     self.notify_done()
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Upgrade/upgrade.py", line 79, in notify_done
     self.session.notifier.notify(NTFY_UPGRADER, NTFY_FINISHED, None)
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/CacheDB/Notifier.py", line 126, in notify
     callInThreadPool(task, *args)
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Utilities/twisted_utils.py", line 46, in callInThreadPool
     if isInThreadPool():
   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Utilities/twisted_utils.py", line 56, in isInThreadPool
     return current_thread() in reactor.threadpool.threads
 exceptions.AttributeError: 'NoneType' object has no attribute 'threads'
```

### PR DESCRIPTION
**Pull request by brussee**
Closes #2340

### CODE REVIEW

**Comment by brussee** [comment]
retest this please

**Comment by lfdversluis** [comment]
If there is no threadpool Twisted is not running. The moment the twisted thread comes alive a pool is created. Looks similar to a recent bug in #2325

**Comment by brussee** [comment]
If the threadpool is started on demand the first time it won't be there.

**Comment by whirm** [comment]
@brussee the twisted reactor will set up the threadpool. If the twisted reactor is not running there's no thread pool available. That usually can be easily be solved by using reactor.callWhenRunning (https://twistedmatrix.com/documents/8.1.0/api/twisted.internet.base.ReactorBase.html#callWhenRunning).

**Comment by whirm** [comment]
Closing this.

**Comment by whirm** [comment]
@brussee's was the right solution I misread the thing the first time around. :/

**Pull request closed without merging**
