### PR TITLE
macOS documentation update

### PR DESCRIPTION
**Pull request by drew2a**
## Readme

1. I removed ```git clone --recursive git@github.com:Tribler/tribler.git``` but left ```git clone --recursive https://github.com/Tribler/tribler.git``` as more common way to clone the repo.
1. "Running from repo" section has been restructured, because there were several points of "how to install dependencies".

## Development on osx

1. Added missed commands to PyQt5 section
1. Added workaround for libtorrent installation invented by @devos50: https://github.com/Homebrew/homebrew-core/pull/43858
1. Replace custom pip installation by "pip3 install -r requirements.txt"

## Requirements.txt

1. Missing dependencies have been added
1. `faulthandler` has been moved down because it is a builtin module since Python 3.3 (and its installation may cause an error).
1. Os-dependent function "_show_system_popup" has been fixed (it was falling on macOS)

### CODE REVIEW

**Comment by devos50** [comment]
ok to test

**Comment by devos50** [comment]
add to whitelist

**Comment by synctext** [comment]
Quickly looked at some of the docs. I personally prefer short and compact reading without overly "wordiness". The following lines are repeated 3 times, could be shortened to: "_For Windows_". Or a more informative would be to include "Windows 2000" is no longer supported, or stuff like from Ubuntu 12.04 onward, etc.
> See `our Windows development guide <http://tribler.readthedocs.io/en/devel/development/development_on_windows.html>`_
for setting everything up on Windows.

**Comment by drew2a** [comment]
@synctext it make sense.

Note: if we want attract more external developers, or new team members, we should rewrite the documentation. It looks outdated and a bit inconsistent.

**Comment by synctext** [comment]
yes, we need accurate specs/docs. However, only advanced developers and our best students are able to make contributions. Like OS kernels and compilers, it's complicated.

**Review by ichorid — APPROVED** [review]

**Comment by devos50** [comment]
That's a nice overview of changes!

A minor comment: we tend to create branches on our own forks and create a PR to upstream. Only for collective features we create a branch on the upstream repository (e.g., when we worked on the multi-channel feature).

**Comment by devos50** [comment]
Also, with the merge of this PR you are now an official contributor to Tribler and you earned our limited edition Tribler mug (we will give it to you when you're in the office) 👍

**Comment by drew2a** [comment]
> A minor comment: we tend to create branches on our own forks and create a PR to upstream. Only for collective features we create a branch on the upstream repository (e.g., when we worked on the multi-channel feature).

Ok, got it. Next time I will do so.

> Also, with the merge of this PR you are now an official contributor to Tribler and you earned our limited edition Tribler mug (we will give it to you when you're in the office)

Oh my God! ◕‿‿◕

**Pull request merged**
