### PR TITLE
Fix expandedPanel_videoplayer is None on Mac

### LINKED ISSUE #1893: Tribler is producing errors in the first seconds after startup
When starting up Tribler, searching for `Pioneer` and clicking the stream button, Tribler is showing an exception:

5740f4098d7a8aa70f9e18521bea78f1

Exception:

```
Jan 22 15:48:05 MBP-van-Martijn Tribler[2089] <Notice>: Traceback (most recent call last):
Jan 22 15:48:05 MBP-van-Martijn Tribler[2089] <Notice>:   File "Tribler/Main/vwxGUI/MainFrame.pyo", line 581, in startDownload
Jan 22 15:48:05 MBP-van-Martijn Tribler[2089] <Notice>:   File "Tribler/Main/vwxGUI/__init__.pyo", line 128, in invoke_func
Jan 22 15:48:05 MBP-van-Martijn Tribler[2089] <Notice>:   File "Tribler/Main/vwxGUI/SearchGridManager.pyo", line 658, in playTorrent
Jan 22 15:48:05 MBP-van-Martijn Tribler[2089] <Notice>: AttributeError: 'NoneType' object has no attribute 'Reset'
```

### PR DESCRIPTION
**Pull request by LipuFei**
Fix #1893

### CODE REVIEW

**Comment by whirm** [comment]
add to whitelist

**Comment by devos50** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by LipuFei** [comment]
Are the tests breaking so often again?

**Comment by whirm** [comment]
@LipuFei for some reason it's running tests from a different PR

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Pull request merged**
