### PR TITLE
Fix issues with circuits

### LINKED ISSUE #1531: Traceback after deleting a download that had anontunnel enabled
That's in current devel.

```
Traceback (most recent call last):
  File "/var/data/projects/delft/tribler/Tribler/Main/tribler_main.py", line 646, in sesscb_states_callback
    self.tunnel_community.monitor_downloads(dslist)
  File "/var/data/projects/delft/tribler/Tribler/dispersy/util.py", line 35, in helper
    return func(*args, **kargs)
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/hidden_community.py", line 256, in monitor_downloads
    self.do_dht_lookup(info_hash)
  File "/var/data/projects/delft/tribler/Tribler/community/tunnel/hidden_community.py", line 282, in do_dht_lookup
    circuit = self.selection_strategy.select(None, self.hops[info_hash])
KeyError: '%U\x9bd\x04\x9d\xcagZc3\\\xaa\x8bZ\xaa\x91\x0e/\x04'
```

### PR DESCRIPTION
**Pull request by rjruigrok**
Fixes #1531 and #1532.

### CODE REVIEW

**Comment by rjruigrok** [comment]
ok to test

**Comment by rjruigrok** [comment]
Hmm. Not enough swag. :smiley:

**Comment by whirm** [comment]
@rjruigrok you don't need to do that. You are on the list(tm)

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
@rjruigrok looks fine to me, not sure about the "safe seeding using proxies", maybe "safe seeding using AnonTunnel"? @synctext ?

**Comment by whirm** [comment]
@rjruigrok: @synctext says: "Encrypted anonymous seeding using proxies"

**Comment by whirm** [comment]
replace this and I'll merge it and tag RC1

**Comment by whirm** [comment]
@synctext said you won't be working on this till tomorrow, so I'm merging this and changing the message myself.

**Pull request merged**
