### PR TITLE
Removed hard-coded addresses in TrustChain blocks from market

### PR DESCRIPTION
**Pull request by devos50**
Instead, we use the EgbertDHT ©

### CODE REVIEW

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
I'm getting this error during the tests on Linux:

```
Test whether we unreserve the quantity if a proposed trade timeouts ... The test-suite locked up! Force quitting! Thread dump:
THREAD#140495954351872
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
|       self.run()
|   File "/usr/lib/python2.7/threading.py", line 754, in run
|       self.__target(*self.__args, **self.__kwargs)
|   File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 45, in work
|       for task in iter(queue.get, _stop):
|   File "/usr/lib/python2.7/Queue.py", line 168, in get
|       self.not_empty.wait()
|   File "/usr/lib/python2.7/threading.py", line 340, in wait
|       waiter.acquire()
THREAD#140495971137280
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
|       self.run()
|   File "/usr/lib/python2.7/threading.py", line 754, in run
|       self.__target(*self.__args, **self.__kwargs)
|   File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 45, in work
|       for task in iter(queue.get, _stop):
|   File "/usr/lib/python2.7/Queue.py", line 168, in get
|       self.not_empty.wait()
|   File "/usr/lib/python2.7/threading.py", line 340, in wait
|       waiter.acquire()
THREAD#140496038803200
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
|       self.run()
|   File "/usr/lib/python2.7/threading.py", line 754, in run
|       self.__target(*self.__args, **self.__kwargs)
|   File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 45, in work
|       for task in iter(queue.get, _stop):
|   File "/usr/lib/python2.7/Queue.py", line 168, in get
|       self.not_empty.wait()
|   File "/usr/lib/python2.7/threading.py", line 340, in wait
|       waiter.acquire()
THREAD#140496078927616
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
|       self.run()
|   File "/usr/lib/python2.7/threading.py", line 754, in run
|       self.__target(*self.__args, **self.__kwargs)
|   File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/pyipv8/ipv8/test/util.py", line 51, in <lambda>
|       _twisted_thread = Thread(target=lambda: reactor.run(installSignalHandlers=False), name="Twisted")
|   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1261, in run
|       self.mainLoop()
|   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1273, in mainLoop
|       self.doIteration(t)
|   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 218, in doPoll
|       l = self._poller.poll(timeout, len(self._selectables))
THREAD#140495979529984
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
|       self.run()
|   File "/usr/lib/python2.7/threading.py", line 754, in run
|       self.__target(*self.__args, **self.__kwargs)
|   File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 45, in work
|       for task in iter(queue.get, _stop):
|   File "/usr/lib/python2.7/Queue.py", line 168, in get
|       self.not_empty.wait()
|   File "/usr/lib/python2.7/threading.py", line 340, in wait
|       waiter.acquire()
THREAD#140495962744576
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
|       self.run()
|   File "/usr/lib/python2.7/threading.py", line 754, in run
|       self.__target(*self.__args, **self.__kwargs)
|   File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 45, in work
|       for task in iter(queue.get, _stop):
|   File "/usr/lib/python2.7/Queue.py", line 168, in get
|       self.not_empty.wait()
|   File "/usr/lib/python2.7/threading.py", line 340, in wait
|       waiter.acquire()
THREAD#140495987922688
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
|       self.run()
|   File "/usr/lib/python2.7/threading.py", line 754, in run
|       self.__target(*self.__args, **self.__kwargs)
|   File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 45, in work
|       for task in iter(queue.get, _stop):
|   File "/usr/lib/python2.7/Queue.py", line 168, in get
|       self.not_empty.wait()
|   File "/usr/lib/python2.7/threading.py", line 340, in wait
|       waiter.acquire()
THREAD#140496320254784
|   File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/community/market/community.py", line 339, in unload
|       yield super(MarketCommunity, self).unload()
|   File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/pyipv8/ipv8/taskmanager.py", line 163, in shutdown_task_manager
|       self.cancel_all_pending_tasks()
|   File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/community/market/core/orderbook.py", line 358, in cancel_all_pending_tasks
|       for order_id in self.get_order_ids():
|   File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/pyipv8/ipv8/taskmanager.py", line 98, in cancel_all_pending_tasks
|       for name in self._pending_tasks.keys():
|   File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/pyipv8/ipv8/taskmanager.py", line 87, in cancel_pending_task
|       self._pending_tasks.pop(name, None)
|   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 547, in cancel
|       self.result.cancel()
|   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 500, in errback
|       self._startRunCallbacks(fail)
|   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
|       self._runCallbacks()
|   File "/usr/lib/python2.7/traceback.py", line 279, in format_stack
|       return format_list(extract_stack(f, limit))
|   File "/usr/lib/python2.7/traceback.py", line 313, in extract_stack
|       return list
|   File "/usr/lib/python2.7/linecache.py", line 69, in checkcache
|       del cache[filename]
THREAD#140496030148352
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
|       self.run()
|   File "/usr/lib/python2.7/threading.py", line 754, in run
|       self.__target(*self.__args, **self.__kwargs)
|   File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 45, in work
|       for task in iter(queue.get, _stop):
|   File "/usr/lib/python2.7/Queue.py", line 168, in get
|       self.not_empty.wait()
|   File "/usr/lib/python2.7/threading.py", line 340, in wait
|       waiter.acquire()
THREAD#140496004708096
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
|       self.run()
|   File "/usr/lib/python2.7/threading.py", line 754, in run
|       self.__target(*self.__args, **self.__kwargs)
|   File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 45, in work
|       for task in iter(queue.get, _stop):
|   File "/usr/lib/python2.7/Queue.py", line 168, in get
|       self.not_empty.wait()
|   File "/usr/lib/python2.7/threading.py", line 340, in wait
|       waiter.acquire()
THREAD#140496047195904
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
|       self.run()
|   File "/usr/lib/python2.7/threading.py", line 754, in run
|       self.__target(*self.__args, **self.__kwargs)
|   File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 45, in work
|       for task in iter(queue.get, _stop):
|   File "/usr/lib/python2.7/Queue.py", line 168, in get
|       self.not_empty.wait()
|   File "/usr/lib/python2.7/threading.py", line 340, in wait
|       waiter.acquire()
THREAD#140496021755648
|   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
|       self.__bootstrap_inner()
|   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
|       self.run()
|   File "/usr/lib/python2.7/threading.py", line 754, in run
|       self.__target(*self.__args, **self.__kwargs)
|   File "/usr/local/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 45, in work
|       for task in iter(queue.get, _stop):
|   File "/usr/lib/python2.7/Queue.py", line 168, in get
|       self.not_empty.wait()
|   File "/usr/lib/python2.7/threading.py", line 340, in wait
|       waiter.acquire()
+ FAILURE=1
```

**Comment by qstokkink** [comment]
@devos50 the test is taking longer than the this-test-is-taking-so-long-that-the-entire-thing-has-probably-locked-up timeout. You can set the test class's `MAX_TEST_TIME` to a higher value if this is expected behavior.

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
I think it is caused by some weird construction in the DHT community: if I don't load the DHT community, the tests seems to pass. I will do more extensive debugging tomorrow.

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
I found the issue; the market tests are currently taking longer than 10 seconds in total to run. I thought that the ten seconds was for each individual test. Now with the DHT stuff added, the tests are slowed down a bit so I guess this pushed it just over the 10 second duration...

**Pull request merged**
