### PR TITLE
Removed unused variables.

### PR DESCRIPTION
**Pull request by devos50**
I encountered some unused variables that could be removed.

### CODE REVIEW

**Comment by whirm** [comment]
Yeah, I had this special value variable removed on a wip branch I have, I always wondered what that originally meant :D

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
@whirm can you merge this one please? It contains the fix for the unhandled exception.

**Pull request merged**
