### PR TITLE
Catch unhandled exceptions and fail the tests if any has been raised

### PR DESCRIPTION
**Pull request by whirm**

### CODE REVIEW

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
@LipuFei ready

**Comment by whirm** [comment]
@LipuFei ready if it passes

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
@LipuFei Do not merge it yet, I still have to fix some stuff

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
@LipuFei I guess it's ready. The mangled log on the unit test report is still crappy but I'm trying to fix that.

**Comment by whirm** [comment]
@LipuFei look at the last failed run to see how it looks now in case you have any suggestion

**Comment by whirm** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
@whirm looks good. ready?

**Comment by whirm** [comment]
@LipuFei yup. 
I'll try to fix the double logging on the report now.

**Comment by LipuFei** [comment]
@whirm needs a rebase

**Comment by LipuFei** [comment]
@whirm ready?

**Comment by whirm** [comment]
@LipuFei yes

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
@LipuFei this retest is to check something unrelated to the PR, you can merge it.

**Pull request merged**
