### PR TITLE
Add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by wsxy162**
Initial translations for zh_CN.

### CODE REVIEW

**Comment by devos50** [comment]
ok to test

**Comment by devos50** [comment]
Thank you for your contribution! (Or should I say 感谢您的贡献😀)?

Please let us know when this PR is ready for review!

**Comment by wsxy162** [comment]
> Please let us know when this PR is ready for review!

The translation is quite complete, you can feel free to review it.

**Comment by devos50** [comment]
retest this please

**Review by devos50 — APPROVED** [review]
@xoriole could you also review this PR?

**Review by xoriole — APPROVED** [review]

**Comment by ichorid** [comment]
@wsxy162  , I've recently [cleaned up and wrapped](https://stackoverflow.com/questions/44286102/minimize-to-tray-on-macosx) all the remaining GUI strings in `tr()`. Would you care to update the translation?

**Comment by wsxy162** [comment]
> @wsxy162 , I've recently [cleaned up and wrapped](https://stackoverflow.com/questions/44286102/minimize-to-tray-on-macosx) all the remaining GUI strings in `tr()`. Would you care to update the translation?

Okay, it may take a few days.

**Comment by ichorid** [comment]
Take your time. The release will be frozen by the end of May. Before that, there will be a couple more things changed in the GUI, so it is better to plan ahead to do another small translation update just before the release.

**Comment by wsxy162** [comment]
@ichorid Facing a string -- "It shows <strong>%s</strong> interactions made by <strong>%s</strong> users", I would like to [use Numbered Arguments](https://doc.qt.io/qt-5/i18n-source-translation.html#using-numbered-arguments) to change the words order in my translation, could you modify the original strings?

**Comment by ichorid** [comment]
> @ichorid Facing a string -- "It shows **%s** interactions made by **%s** users", I would like to [use Numbered Arguments](https://doc.qt.io/qt-5/i18n-source-translation.html#using-numbered-arguments) to change the words order in my translation, could you modify the original strings?

I can do this, but it is better to do this in a single PR. Could you please point me to every string that will require such modifications? Even better, you could do the PR yourself :wink:

**Comment by wsxy162** [comment]
> you could do the PR yourself

Not familiar with this. Just found three places:

```
src/tribler-gui/tribler_gui/widgets/trustgraphpage.py
231            "network. It shows <strong>%s</strong> interactions made by <strong>%s</strong> users."

src/tribler-gui/tribler_gui/widgets/downloadsdetailstabwidget.py
106            tr("%s in %d files")

src/tribler-gui/tribler_gui/utilities.py
171        return tr("%iy %iw") % (years, weeks)
173        return tr("%iw %id") % (weeks, days)
175        return tr("%id %ih") % (days, hours)
177        return tr("%ih %im") % (hours, minutes)
179        return tr("%im %is") % (minutes, seconds)


```

**Comment by ichorid** [comment]
> Not familiar with this. Just found three places:

Ok, I'll do it. I'll post it here when the PR with the changes is merged.

**Comment by ichorid** [comment]
@wsxy162, I've updated the translation, including the changes you suggested. Also, we missed the dialogs dir initially, so I added it now. That's about 40 new strings for you to translate :wink:

**Pull request merged**
