### PR TITLE
Fix Python 3 syntax errors

### PR DESCRIPTION
**Pull request by cclauss**
IN https://github.com/Tribler/tribler/issues/3883#issuecomment-445044813 I thought we had a big task in front of us to find and fix Python 3 syntax errors but it was quite easy.  Fixes in these nine files were required but this PR would bring us to:
Python 2 syntax errors: 0
Python 3 syntax errors: 1 --> __Tribler/community/market/community.py__ see #4092

### CODE REVIEW

**Comment by devos50** [comment]
Thank you for your contribution! Please prefix your PR with either `WIP` if you are still working on it, or `READY` if the pull request is ready for a review from our side 👍

**Comment by devos50** [comment]
Please ignore the pylint issues and remove the pylint-specific comments from the code.

**Comment by cclauss** [comment]
Argh...  I do dislike PyLint.

**Comment by cclauss** [comment]
Does https://github.com/Tribler/tribler/pull/4091/files#diff-34c1af109bb6fc65c2295a8cea67072aR26 cause Linux tests to fail?

**Comment by devos50** [comment]
retest this please

**Comment by cclauss** [comment]
Awesome!  If you could run the commands:
* __python2 -m flake8 --count --exclude=.git,./TriblerGUI/vlc.py --show-source --statistics --select=E901,E999,F821,F822,F823__  # On Python 2
* __python3 -m flake8 --count --exclude=.git,./TriblerGUI/vlc.py --show-source --statistics --select=E901,E999,F821,F822,F823__  # On Python 3
that would help us track progress and makes sure that we do not backslide on other pull requests in the process.  Once a fix for #4093 is in, we can remove the __--exclude__ option.  Once we are satisfied Python 3 is working, we can remove or modify these.

**Pull request merged**
