### PR TITLE
Pony and LZ4 as pip dependency

### PR DESCRIPTION
**Pull request by xoriole**
Pony and LZ4 as pip dependency.

Fixes https://github.com/Tribler/tribler/issues/4224

### CODE REVIEW

**Comment by qstokkink** [comment]
If we're going the pip route, we might as well pull in the latest versions of other packages with pip as well.

**Comment by xoriole** [comment]
I also don't want to go the pip route but we need these dependencies for now. Let's keep these until snap build setup is complete.

**Comment by devos50** [comment]
Yup, for now we have to.

**Comment by devos50** [comment]
Funny, since you did not change any .py file, it will check _all_ files for flake8 violations.

**Comment by xoriole** [comment]
@devos50 Yes, it is probably because I cherry-picked one of the commits from 7.2.0-exp1 branch. I'll squash them and push, then it might resolve itself.

**Comment by qstokkink** [comment]
The whole pip switch is kind of a big deal though: #3935, #3056.

But if we _absolutely have to_ switch to pip, let's do it right and solve #3770 while doing it.

**Comment by synctext** [comment]
Clearly this requires a bigger discussion before picking a direction. Leaving Debian in the cold is quite a big deal.

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
As discussed with @xoriole, this PR is ready for merge 👍

**Pull request merged**
