### PR TITLE
New Tribler PyQt GUI

### LINKED ISSUE #14: New version check from Tribler
We should add a way to check if there's a newer Tribler release. At least for when it crashes so we don't get reports for possibly fixed bugs.

### LINKED ISSUE #1802: Create unit tests that test only the GUI
Currently, the tests are testing both the GUI and the Tribler core system. We should have a clear separation of GUI and Core in the tests. We can use a mocked `Session` to control the GUI and to test whether it is displaying the right stuff.

### LINKED ISSUE #2190: [devel] Removing torrents from my channel works with a delay
##### Tribler version/branch+revision:

b60d3b126ddfcafc2a939c32ca6b9a97a962f561 devel
##### Expected behavior:

Removed torrent from my channel immediately disappears. Or there is indication that removal is in progress.
##### Actual behavior:

It disappears from the list after some delay. No indication of background operation.

### PR DESCRIPTION
**Pull request by devos50**
**Please make sure to backup your `.Tribler` directory before trying out the new GUI! Things might not work out as expected.**

In this PR, I add the new GUI, written in pyQt to Tribler. Unfortunately, the new GUI and Tribler core should be in the same repo since we want only one issue tracker.
## General info

The GUI is written using the Qt framework with PyQt bindings so Python can be used to program the GUI. I tried to create as much as possible elements using the Qt Designer application. The designer files (ending with the `.ui` file extension) can be found in the `qt_resources` directory. Images used by the new GUI can be found in the `images` directory.
## Running the GUI

Before you run the GUI, make sure you have Qt5 and pyQt installed. `cd` to the tribler directory and enter the following commands:

```
python run_gui.py
```

Additionally, you can use any IDE (I’m using PyCharm) to run the GUI.

In order to test the GUI while developing, I’ve created a separate project that provides fake data to the new Tribler GUI such as channels, torrents and downloads. This project can be found [here](https://github.com/devos50/TestTriblerAPI). Note that not all endpoints are currently implemented and this project is during development, the main source of data for the GUI. I’m also planning to use this project for the automated GUI tests. Running this project is easy, checkout the project from GitHub, `cd` to the `TestTriblerAPI` directory and execute `python main.py`. Generating the random data will take around 20-30 seconds.
## Progress

There are many endpoints that should be implemented in the GUI, the fake API provider and the real Tribler project. Below, I will keep track of the progress for each endpoint, categorised by functionality.
### General

_I will implement the save settings endpoint in Triblerafter we are making use of `ConfigObj`._

| Functionality | In GUI? | In fake API provider? | In Tribler? |
| --- | --- | --- | --- |
| Get settings | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/956cf963c58d31d4990a5b8c9b701e39ddb38929 </li></ul> |
| Save settings | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[ ] </li></ul> |
| Get variables | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/c340cdcb0165c69cac1af3f1c6a0cd5f98a0d345 </li></ul> |
### Channels

| Functionality | In GUI? | In fake API provider? | In Tribler? |
| --- | --- | --- | --- |
| Get all channels | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/24e0c75b5fabcc53b307500b49f334f5fd533522</li></ul> |
| Get subscribed channels | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/fe7b2f3b1ca798aff0f2daceb20929715d3116d3</li></ul> |
| Get popular channels | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2362/commits/a46bfff20c6806b72a8c9ac60602ee7ef1d1d8a6 </li></ul> |
| Subscribe to a channel | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/6681046a3b2e941d93391ed89c4bbf9b267f21a3</li></ul> |
| Unsubscribe from a channel | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/6681046a3b2e941d93391ed89c4bbf9b267f21a3</li></ul> |
| Edit someone else's channels | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2337/commits/20b6e02a6ac7cc8536ccb64577b361030e2671e9 </li></ul> |
### Torrents

| Functionality | In GUI? | In fake API provider? | In Tribler? |
| --- | --- | --- | --- |
| Get torrents in channel | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2210/commits/c01dcf3717857071ec63b649598e44316731b087</li></ul> |
| Get random torrents | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] fe4cb2271aec6c1e934c0ed294991f873598e2c8 </li></ul> |
| Add a torrent to download | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2464/commits/f4d6c108967426f8ad0e4307b10b234247c75fcb</li></ul> |
| Create a torrent file | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2242/commits/40b4c77a3bc6346f7957eb97517968cda516d8f1</li></ul> |
### Search

| Functionality | In GUI? | In fake API provider? | In Tribler? |
| --- | --- | --- | --- |
| Search channels and torrents | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/b54f56e78fdac48f7be01baacfe6f0375d7830c5</li></ul> |
| Get search completion terms | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2332/commits/925e8b94295a54c685fe4a22030fdaa86ebd54fa</li></ul> |
### My Channel

| Functionality | In GUI? | In fake API provider? | In Tribler? |
| --- | --- | --- | --- |
| Get channel overview | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/cacd86ddaa123e246603b244b3e5b372aa3e17b5 </li></ul> |
| Get channel torrents | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/c140ea7bdaec0f1e5f87456b52458290b1089a66 </li></ul> |
| Get channel playlists | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2207/commits/20178274ddd9a1e82f4430ec9805ef2e8957fad2</li></ul> |
| Get channel rss feeds | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/c7c93658461fbf648fc00c01cb07fe6713f78e22</li></ul> |
| Create new channel | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/390c4e2fabd71ed7203f9a5faaaf50664cdd34b1</li></ul> |
| Edit channel properties | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/e0c2751c6ed7ce2c67aaeb07b44ab2d2c5b36827</li></ul> |
| Remove torrent(s) | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2367/commits/5f5b33381a689d9f9076bf1dd662c3541e2e34f1</li></ul> |
| Add torrent(s) | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2214/commits/31eab17cf27b9d0e371193788acb5d83877d3742</li></ul> |
| Create playlist(s) | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2369/commits/0c3897564e734a957aab1815c82733b18a570191</li></ul> |
| Edit playlist(s) | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2447/commits/d304c008e4d2dc35082f3e4dbeaee8fe1b31e4b8</li></ul> |
| Remove playlist(s) | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2447/commits/cc5a9a4af96b1b214209ad180be5d132f5f7956c</li></ul> |
| Add torrent to playlist(s) | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/ab99748f9b800290779bbbb247542f247f1fd68c</li></ul> |
| Remove torrent from playlist(s) | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/ab99748f9b800290779bbbb247542f247f1fd68c</li></ul> |
| Add rss feed | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2161/commits/f8b4a0b5ed19721eae91ba0ba7b57a64f8eae916</li></ul> |
| Remove rss feed | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/3a297483a34d0c01a61401062fb3515a31262411</li></ul> |
| Recheck rss feed | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/6ba15cec539807db526c0eb2cc11b2b9b4d8b1d5</li></ul> |
### Downloads

| Functionality | in GUI? | In fake API provider? | In Tribler? |
| --- | --- | --- | --- |
| Get downloads | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/commit/221405192509c87fedd60184e28d0ec57dc1a1a1</li></ul> |
| Remove download | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2321/commits/22cb1ca2bda3a22fa7368464257304a884c875de</li></ul> |
| Start/resume download | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2321/commits/22cb1ca2bda3a22fa7368464257304a884c875de</li></ul> |
| Stop download | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2321/commits/22cb1ca2bda3a22fa7368464257304a884c875de</li></ul> |
| Force recheck download | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2330/commits/f0190fc6ed067e6127ecdaa4fd98c2a5c5f851c8</li></ul> |
| Export download to .torrent | <ul><li>[x] </li></ul> | <ul><li>[x] </li></ul> | <ul><li>[x] https://github.com/Tribler/tribler/pull/2339/commits/d303f1288b29c0931e127fde13728787ec23c227</li></ul> |
| Change anonymity level of download | <ul><li>[ ] </li></ul> | <ul><li>[ ] </li></ul> | <ul><li>[ ] </li></ul> |
### Other tasks
- [x] Distinguish between handled and unhanded exceptions when performing requests on the side of the server
- [x] Create a design for the home page
- [x] Create a loading screen -> see https://gyazo.com/3d6174191214aaee9b3991de406d4a45
- [x] Create a feedback window when Tribler crashes -> see https://gyazo.com/63456453b54325bf7ea706c86ea78382
- [x] ~~Make use of the model-view-delegation pattern Qt provides. This will improve performance when rendering (big) lists tremendously.~~ not feasible, I had bad performance when working with model-view. This is due to the fact that custom widgets have to be created for every item in the list. I've implemented a lazy-loaded list that is working very well.
- [x] Implement the search result ranking algorithm as described in #2250.
- [x] Show a notification in the GUI if a newer version of Tribler is available.
- [x] Integrate the twistd Tribler plugin so it gets started when the GUI boots.

Fixes #1802, fixes #2190, fixes #14

### CODE REVIEW

**Comment by brussee** [comment]
> - [ ] Distinguish between handled and unhanded exceptions when performing requests on the side of the server

I took care of this in PR #2175 with RESTRequest.processingFailed() in restapi/rest_manager.py
Compare to MyChannelEndpoint.render_PUT() in case of a DuplicateChannelNameError.

**Comment by jkaberg** [comment]
Hey guys, love the work beeing done here! I noticed this one "Create a design for the home page", and I'm guessing you're referring to an Web UI (?)

Might I suggest baseing this of something like (my personal favourite) [ruTorrent](https://github.com/Novik/ruTorrent) or the orginal [uTorrent Web UI](https://github.com/bittorrent/webui)

**Comment by whirm** [comment]
@jkaberg Only the Qt and Android GUI are being implemented for nowt We would love to see a community developed web UI for Tribler. The REST interface should make it pretty easy.

**Comment by whirm** [comment]
retest this please

**Comment by synctext** [comment]
Quite a bunch of errors when running your code. First Dispersy blocks and (again) converts all torrents. Then these errors popup:

```
Tribler version: 6.5.2-GIT
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Main/tribler_main.py", line 154, in __init__
    session.start()
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Core/Session.py", line 458, in start
    self.lm.register(self, self.sesslock)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Core/APIImplementation/LaunchManyCore.py", line 172, in register
    self.init()
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Core/APIImplementation/LaunchManyCore.py", line 269, in init
    load_communities()
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/dispersy/util.py", line 47, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/dispersy/util.py", line 238, in blockingCallFromThread
    result.raiseException()
  File "<string>", line 2, in raiseException
type: __init__() got an unexpected keyword argument 'split_payload_func'
```

```
 Traceback from this thread:
  File "Tribler/Main/tribler.py", line 95, in <module>
    __main__()
  File "Tribler/Main/tribler.py", line 85, in __main__
    run()
  File "Tribler/Main/tribler.py", line 68, in run
    run_main()
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Main/tribler_main.py", line 1002, in run
    use_torrent_search=use_torrent_search, use_channel_search=use_channel_search)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Main/tribler_main.py", line 154, in __init__
    session.start()
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Core/Session.py", line 458, in start
    self.lm.register(self, self.sesslock)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Core/APIImplementation/LaunchManyCore.py", line 172, in register
    self.init()
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Core/APIImplementation/LaunchManyCore.py", line 269, in init
    load_communities()
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/dispersy/util.py", line 47, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/dispersy/util.py", line 234, in blockingCallFromThread
    this_thread_tb = traceback.extract_stack()

 Traceback from the reactor's thread:
   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Core/APIImplementation/LaunchManyCore.py", line 251, in load_communities
    self.dispersy.define_auto_load(MultiChainCommunity, dispersy_member, load=True)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/dispersy/dispersy.py", line 388, in define_auto_load
    community = community_cls.init_community(self, master, my_member, *args, **kargs)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/dispersy/community.py", line 226, in init_community
    community.initialize(*args, **kargs)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/dispersy/community.py", line 347, in initialize
    self._initialize_meta_messages()
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/dispersy/community.py", line 505, in _initialize_meta_messages
    for meta_message in self.initiate_meta_messages():
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/community/multichain/community.py", line 89, in initiate_meta_messages
    allow_signature_func=self.allow_signature_request, split_payload_func=split_function),

Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Main/tribler_main.py", line 154, in __init__
    session.start()
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Core/Session.py", line 458, in start
    self.lm.register(self, self.sesslock)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Core/APIImplementation/LaunchManyCore.py", line 172, in register
    self.init()
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Core/APIImplementation/LaunchManyCore.py", line 269, in init
    load_communities()
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/dispersy/util.py", line 47, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/dispersy/util.py", line 238, in blockingCallFromThread
    result.raiseException()
  File "<string>", line 2, in raiseException
TypeError: __init__() got an unexpected keyword argument 'split_payload_func'
ERROR   1465831779.31        dispersy:1728  exception during handle_callback for torrent-collect-response
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/dispersy/dispersy.py", line 1723, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/community/search/community.py", line 486, in on_torrent_collect_response
    self._process_collect_request_response(messages)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/community/search/community.py", line 525, in _process_collect_request_response
    timeout=CANDIDATE_WALK_LIFETIME)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/dispersy/util.py", line 35, in helper
    return func(*args, **kargs)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Core/RemoteTorrentHandler.py", line 131, in download_torrent
    self.torrent_requesters[priority].add_request(infohash, candidate, timeout)
ERROR   1465831797.27        dispersy:1728  exception during handle_callback for torrent-collect-response
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/dispersy/dispersy.py", line 1723, in _update
    messages[0].handle_callback(messages)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/community/search/community.py", line 486, in on_torrent_collect_response
    self._process_collect_request_response(messages)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/community/search/community.py", line 525, in _process_collect_request_response
    timeout=CANDIDATE_WALK_LIFETIME)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/dispersy/util.py", line 35, in helper
    return func(*args, **kargs)
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_endpoints/Tribler/Core/RemoteTorrentHandler.py", line 131, in download_torrent
    self.torrent_requesters[priority].add_request(infohash, candidate, timeout)
KeyError: 0
ERROR   1465831798.46        dispersy:1728  exception during handle_callback for torrent-collect-response
```

**Comment by synctext** [comment]
GUI part also complains:

```
/TriblerGUI>env PYTHONPATH=..: python Main.py
ERROR:root:Traceback (most recent call last):
  File "Main.py", line 104, in received_variables
    self.video_player_page.video_player_port = variables["variables"]["ports"]["video~port"]
TypeError: 'NoneType' object has no attribute '__getitem__'

ERROR:root:Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_gui/TriblerGUI/homepage.py", line 41, in received_popular_torrents
    for torrent in result["torrents"]:
TypeError: 'NoneType' object has no attribute '__getitem__'

ERROR:root:No JSON object could be decoded
Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_gui/TriblerGUI/tribler_request_manager.py", line 81, in on_finished
    json_result = json.loads(str(data))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
GOT EVENT ERROR
1
ERROR:root:Traceback (most recent call last):
  File "/home/pouwelse/GITHUB/gui_in_QT_tribler-NEW-June2016/tribler_gui/TriblerGUI/downloadspage.py", line 50, in received_downloads
    for download in downloads["downloads"]:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by devos50** [comment]
@synctext regarding the 2nd error: this is currently expected when Tribler (with the old GUI) is not running/crashes when starting the new GUI. I should have some better error handling/retry mechanism which I will tackle the same time as integrating the twistd plugin.

For the first error, I will try to do the same steps on an Ubuntu machine in a moment.

**Comment by devos50** [comment]
@synctext you should enable the HTTP API. This is turned off by default and we currently have no option to turn it on from the GUI. Please modify `~/.Tribler/libtribler.conf` and enable the API by replacing the following section:

```
[http_api]
enabled = True
port = 8085
```

After that, first start the old GUI and next you can try to start the new GUI.

I got it working on a proxmox (ubuntu) machine: https://gyazo.com/2f5350f5ccf7b26e22510882b73bd2b9

**Comment by devos50** [comment]
A progress update: I've fixed some minor and major bugs and integrated the Tribler twistd plugin! This means that it is no longer necessary to have two separate GUIs besides each other to test this PR. You still need two repositories (I will update the instructions in the first post in a moment).

Moreover, I created a bunch of GUI tests. They are using the fake API provider and are not complete yet. During the run, screenshots are taken, like the old GUI tests. Running these on Linux, Windows and OS X will be my next priority.

Other work:
- Tested the GUI on Windows and Linux. On Linux, it worked out of the box with only a minor difference (but that was easily fixed by a CSS rule). On Windows, it required some more work since the twistd executable is not always available so I had to rewrite some parts of the startup process.
- Implemented a mechanism so only one instance of the Tribler GUI runs. If the user attempts to open a second Tribler instance, the already opened GUI is activated instead.
- Implemented the dialog when a new Tribler version is available in the new GUI.
- Created a loading screen when a user starts the GUI. This is not a splash screen but instead, integrated in the main GUI window. It also displays the status of the upgrader.
- Fixed some minor layout bugs

**Comment by vi** [comment]
Will old GUI and this GUI coexist for a couple of versious?

I don't believe that new GUI will cover 100% of features from the day one, even if the developer tries to achieve that. There will probably missing sorting here, missing option there which would need to use old GUI as workaround.

**Comment by devos50** [comment]
@vi as far as I know, we don't have any plans to let the old GUI co-exists. We are too understaffed to manage two GUIs. However, it's not very hard to extend the new GUI with features since it's written in Qt. Also, we try to make extending the REST API as easy as possible which means that these missing features can be implemented by some other developers.

Running the new GUI at the moment is not easy since you need two repositories besides each other. I will work on some installers next week and I will let you know when they are ready :)

**Comment by lfdversluis** [comment]
@vi However, the next experimental release (I think 6.6) will have the old wx GUI and will still receive bug fixes for now.

**Comment by vi** [comment]
Is it _only_ the GUI or also some internal changes?

May one run this GUI and traditional GUI interchangeably?

GUI-only changes should not suppose to require `.Tribler` backups...

**Comment by synctext** [comment]
@vi the way the GUI talks to the core was a mess. It's now nice and tidy instead of one big bag of code. So new GUI is also about superior code organisation and detecting bugs faster.

**Comment by vi** [comment]
Shall I suggest those checkboxes (what is an "endpoiont"?) for features I use (or want) to ensure they will not be missing?

## Downloads

* Sorting by size, download status, anonymity, name, date added
* View segmented bar showing which fragments are fully/partially present and which are not yet downloaded
* Toggle files between included and excluded (it would be nice if there would be third mode: ["included, download sequentially"](https://github.com/Tribler/tribler/issues/1718));
* View downloaded % for each file in a torrent
* Copy magnet links (there is already "export torrent" in checkboxes)
* Ability to work with [very big torrents](https://github.com/Tribler/tribler/issues/1689);
* Quick filter by name or size
* Adding new download from file, magnet, http or https link

## Network
* Edit bandwidth limits, including per-torrent
* View current total upload/download limit, balance, etc.
* View port/NAT status, number of connected peers

**Comment by synctext** [comment]
that is a big list @vi :-)
first focus is now a minimal viable GUI: search,select and stream.
all with a Youtube feel. Next release will add further features.

**Comment by vi** [comment]
So until this next release with further features the old Tribler UI should be supported.

My use case of Tribler seems to be far away from Youtube...

**Comment by brussee** [comment]
The create torrent endpoint is done: #2242 as well as the add torrent to download: #2464.

**Comment by ardhipoetra** [comment]
Credit mining GUIDBTuples can be removed if #2398 is merged. Mind to check it?

**Comment by devos50** [comment]
@brussee thanks, I've updated the checkboxes (was a bit outdated).

**Comment by devos50** [comment]
Managed to get the GUI tests working on OS X and Windows, see https://jenkins.tribler.org/job/pers/job/Test_gui_mac_devos50/10/ and https://jenkins.tribler.org/job/pers/job/Test_gui_win64_devos50/9/

**Comment by synctext** [comment]
solid progress!
if you don't mind I'll post highlights on the forum.

**Comment by devos50** [comment]
@synctext np, go ahead :)

Just managed to get the first OS X builder working with this new GUI + PyInstaller: https://jenkins.tribler.org/job/pers/job/Build-Tribler7_OSX/. **note that this build is quite unstable and needs more polishing**.

**Comment by vi** [comment]
1. Is usual (legacy) Tribler GUI usable with this merged?
2. Can both legacy GUI and this GUI be used at the same time? Two windows - one Tribler.

**Comment by devos50** [comment]
I've created a separate job for the GUI tests: https://jenkins.tribler.org/job/GH_Tribler_PR_tests_GUI/. When this PR is merged, we can execute this multi-job on every PR.

**Comment by devos50** [comment]
After 6.5 months, this PR is finally ready to be merged! I cleaned up the code as much as I can and fixed many Pylint errors.

Regarding the code coverage: the GUI tests are executed in a separate job and this will test the code in the TriblerGUI directory.

I will merge this PR tomorrow if no-one has further comments on it.

**Pull request merged**
