### PR TITLE
Fix make torrent and update dispersy

### PR DESCRIPTION
**Pull request by LipuFei**
* fix make torrent
* update dispersy pointer

### CODE REVIEW

**Comment by LipuFei** [comment]
@whirm I made a unit test to test the torrent file creation function.

**Comment by LipuFei** [comment]
@whirm feel free to merge when it passes

**Comment by LipuFei** [comment]
@whirm Looks like the segmentation fault is back again. Have any clue about what happened?

**Comment by whirm** [comment]
From gorilla1:
``` 
[256358.061796] nosetests[6149]: segfault at 8 ip 00007f4c4ef2a68a sp 00007f4be7ffcfa0 error 4 in libtorrent-rasterbar.so.7.0.0[7f4c4ee1c000+34c000]
[259431.481242] nosetests[18169]: segfault at 8 ip 00007fad1e28768a sp 00007fac5adf2fa0 error 4 in libtorrent-rasterbar.so.7.0.0[7fad1e179000+34c000]
[259888.560915] nosetests[17606]: segfault at 1c0 ip 00007f248cdcb85f sp 00007fff0dd62f30 error 4 in libwx_gtk2u_core-2.8.so.0.8.0[7f248cafd000+39b000]
```

**Comment by LipuFei** [comment]
retest this please

**Pull request merged**
