### PR TITLE
Update dispersy pointer

### PR DESCRIPTION
**Pull request by LipuFei**

### CODE REVIEW

**Comment by LipuFei** [comment]
@whirm ready. looks like the channel search test might have been fixed by this one.

**Comment by LipuFei** [comment]
@whirm I will try a few more times.

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
I think I broke the discovery community, but guys have a look at http://jenkins.tribler.org//job/GH_Tribler_pull-request-tester_devel/3667/
It's asserting http://jenkins.tribler.org//job/GH_Tribler_pull-request-tester_devel/3667/artifact/output//Screenshot-16.png but passes the unit-tests.

@whirm are you sure that the changes to testasaserver were ok?

**Comment by NielsZeilemaker** [comment]
@LipuFei @whirm this is an existing bug in the discovery community which is now detected because of moving the encode_decode stuff into dispersy. Will fix asap, it's a trivial change.

**Comment by NielsZeilemaker** [comment]
superceded by #1338

**Pull request closed without merging**
