### PR TITLE
Reintroduced general exception handler

### LINKED ISSUE #8137: Hook in error events for GUI
The general exception handler in Python was broken with the new GUI. This should be reintroduced.

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #8137

This PR:

 - Adds uncaught exception forwarding to the GUI.

### CODE REVIEW

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Review by egbertbouman — COMMENTED** [review]
Looks good. Now that we have the general exception handler again, maybe you should remove the Axios interceptor (in tribler.service.ts)? I'm still getting an error on a metainfo timeout.

**Comment by qstokkink** [comment]
@egbertbouman I made an issue for that here: #8141 I'm looking for some input on "sexier" solutions than what I'm currently thinking of.

**Review by egbertbouman — APPROVED** [review]

**Pull request merged**
