### PR TITLE
Updated anon download test to have a unique file

### LINKED ISSUE #8109: Windows integration tests sometimes failing
On both `Windows, Python 3.9` and `Windows, Python 3.10` the integration tests sometimes get stuck forever:

```python
python run_unit_tests.py -a -k tribler/test_integration -p 2
```

---

My first thought is that the instances on the two processes might be finding each other because they have the same download:

https://github.com/Tribler/tribler/blob/2c8eae29b779605244a03dc50a345149033f1513/src/tribler/test_integration/test_anon_download.py#L178-L179

https://github.com/Tribler/tribler/blob/2c8eae29b779605244a03dc50a345149033f1513/src/tribler/test_integration/test_hidden_services.py#L209-L210

These instances _should_ never connect to each other but we can give them different file contents + names just to be sure.

Of course, there may still be something entirely different going on.

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #8109

This PR:

 - Updates the file contents used in `test_anon_download` to be unique, w.r.t. `test_hidden_services`.

### CODE REVIEW

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
validate

**Comment by qstokkink** [comment]
10/10 validations succeeded. At least this seems more stable than before: marking as READY.

**Comment by qstokkink** [comment]
validate

**Review by xoriole — APPROVED** [review]

**Pull request merged**
