### PR TITLE
Fix socks port selection method

### LINKED ISSUE #5437: Address already in use (now with international flavor!)
7.5.1:

```python
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 112, in on_read_data
RuntimeError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 45777): normalerweise darf jede socketadresse (protokoll, netzwerkadresse oder anschluss) nur jeweils einmal verwendet werden
--LONG TEXT--
Traceback (most recent call last):
File "lib\asyncio\events.py", line 88, in _run
File "ipv8\taskmanager.py", line 123, in done_cb
File "src\tribler-core\tribler_core\modules\tunnel\socks5\server.py", line 27, in start
File "lib\asyncio\base_events.py", line 1374, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 45777): normalerweise darf jede socketadresse (protokoll, netzwerkadresse oder anschluss) nur jeweils einmal verwendet werden

--CONTEXT--
{'message': 'Exception in callback TaskManager.register_task.<locals>.done_cb(<Task finishe...ndet werden")>) at ipv8\\taskmanager.py:120', 'exception': OSError(10048, "error while attempting to bind on address ('127.0.0.1', 45777): normalerweise darf jede socketadresse (protokoll, netzwerkadresse oder anschluss) nur jeweils einmal verwendet werden"), 'handle': <Handle TaskManager.register_task.<locals>.done_cb(<Task finishe...ndet werden")>) at ipv8\taskmanager.py:120>}
```

```python
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 112, in on_read_data
RuntimeError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 9150): обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
--LONG TEXT--
Traceback (most recent call last):
File "lib\asyncio\events.py", line 88, in _run
File "ipv8\taskmanager.py", line 123, in done_cb
File "src\tribler-core\tribler_core\modules\tunnel\socks5\server.py", line 27, in start
File "lib\asyncio\base_events.py", line 1374, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 9150): обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)

--CONTEXT--
{'message': 'Exception in callback TaskManager.register_task.<locals>.done_cb(<Task finishe...адрес/порт)")>) at ipv8\\taskmanager.py:120', 'exception': OSError(10048, "error while attempting to bind on address ('127.0.0.1', 9150): обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)"), 'handle': <Handle TaskManager.register_task.<locals>.done_cb(<Task finishe...адрес/порт)")>) at ipv8\taskmanager.py:120>}
```

```


Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 112, in on_read_data
RuntimeError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 9983): 각 소켓 주소(프로토콜/네트워크 주소/포트)는 하나만 사용할 수 있습니다
--LONG TEXT--
Traceback (most recent call last):
File "lib\asyncio\events.py", line 88, in _run
File "ipv8\taskmanager.py", line 123, in done_cb
File "src\tribler-core\tribler_core\modules\tunnel\socks5\server.py", line 27, in start
File "lib\asyncio\base_events.py", line 1374, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 9983): 각 소켓 주소(프로토콜/네트워크 주소/포트)는 하나만 사용할 수 있습니다

--CONTEXT--
{'message': 'Exception in callback TaskManager.register_task.<locals>.done_cb(<Task finishe... 사용할 수 있습니다")>) at ipv8\\taskmanager.py:120', 'exception': OSError(10048, "error while attempting to bind on address ('127.0.0.1', 9983): 각 소켓 주소(프로토콜/네트워크 주소/포트)는 하나만 사용할 수 있습니다"), 'handle': <Handle TaskManager.register_task.<locals>.done_cb(<Task finishe... 사용할 수 있습니다")>) at ipv8\taskmanager.py:120>}
```

And some Jenkins stuff:
```python
Traceback (most recent call last):
File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-gui/tribler_gui/core_manager.py", line 119, in on_received_state
RuntimeError: [Errno 98] Address already in use
--LONG TEXT--
Traceback (most recent call last):
File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/run_tribler.py", line 95, in start_tribler
File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-core/tribler_core/session.py", line 396, in start
File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-core/tribler_core/restapi/rest_manager.py", line 75, in start
File "/home/tribler/.local/lib/python3.6/site-packages/aiohttp/web_runner.py", line 104, in start
File "/usr/lib/python3.6/asyncio/base_events.py", line 1082, in create_server
sock.listen(backlog)
OSError: [Errno 98] Address already in use

--CONTEXT--
{'message': 'Task exception was never retrieved', 'exception': OSError(98, 'Address already in use'), 'future': <Task finished coro=<start_tribler_core.<locals>.start_tribler() done, defined at /home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/run_tribler.py:64> exception=OSError(98, 'Address already in use')>
```

### PR DESCRIPTION
**Pull request by ichorid**
probably fixes #5437

### CODE REVIEW

**Comment by ichorid** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by egbertbouman** [comment]
retest this please

**Comment by ichorid** [comment]
The previous version gets free port by trying the ports sequentially starting from a random one. There are two problems:
1. if the thing can't get a port, it will not raise an error. Maybe I'm missing the higher-level logic checking for `None` on return. I still think to raise an error is a better solution.
2. If the random number is too close to the `max_port` and some ports are already occupied there, the thing will fail for no reason.

**Comment by egbertbouman** [comment]
@ichorid I'm not saying your changes are not an improvement, but I'm wondering how it fixes https://github.com/Tribler/tribler/issues/5437. To me, it seems that the port was just claimed by something else in the meantime (like described in https://github.com/Tribler/tribler/issues/5437#issuecomment-656050450)

**Comment by ichorid** [comment]
So, to properly fix this, we must retry claiming the port on error. I'll try to implement that.

**Comment by ichorid** [comment]
If done properly, this is going to be too invasive for 7.5. Closing it for now.

**Pull request closed without merging**
