### PR TITLE
fixes #2494 Error if ffmpeg cannot be found on OS X on latest devel

### LINKED ISSUE #2494: Error if ffmpeg cannot be found on OS X on latest devel
The statement introduced in https://github.com/Tribler/tribler/commit/6ddac6bf26972bfb1e1cf81db1bdb3dee2379d36 crashes when the `find_executable` call returns `None`.

### PR DESCRIPTION
**Pull request by brussee**

### CODE REVIEW

**Comment by brussee** [comment]
@whirm Ready.

**Comment by devos50** [comment]
Great!

**Comment by brussee** [comment]
Maybe the absolute path should also be set to unicode like the darwin if branch?

**Comment by brussee** [comment]
retest this please

**Comment by brussee** [comment]
retest this please

**Pull request merged**
