### PR TITLE
Emercoin

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
This pull request enables Emercoin lookups from within tribler. If you search for emc:XYZ tribler is going to connect to your local Emercoin wallet in order to do a magnet:XYZ key lookup. The value is then parsed as a magnet link, and downloading will commence.

### CODE REVIEW

**Comment by whirm** [comment]
@NielsZeilemaker ready?

**Comment by NielsZeilemaker** [comment]
It is yes, I was planning to modify the AddTorrent dialog to also support emc links, but I didn't have the time. But the code is working.

**Comment by maxihatop** [comment]
I tried to run your system to use emercoin tracker - attempts are unsuccessful.

Emercoin server prints "ThreadRPCServer incorrect password attempt from 127.0.0.1"

Tribbler logging:

urllib2.URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\home.pyo", line 137, in OnClick
  File "Tribler\Main\vwxGUI\GuiUtility.pyo", line 405, in dosearch
  File "Tribler\Main\vwxGUI\MainFrame.pyo", line 388, in startDownloadFromArg
  File "Tribler\Main\vwxGUI\MainFrame.pyo", line 443, in startDownloadFromEMC
  File "Tribler\Main\Emercoin\EmercoinMgr.pyo", line 21, in fetch_key
  File "urllib2.pyo", line 154, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default    
urllib2.HTTPError: HTTP Error 401: Authorization Required

**Comment by whirm** [comment]
@maxihatop You should open a new issue for that.

**Pull request merged**
