### PR TITLE
Fix gaierror

### LINKED ISSUE #5167: [7.5.0-exp1] Name or service not known
Traceback (most recent call last):
  File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 114, in on_read_data
RuntimeError: [Errno -2] Name or service not known

Also it's stuck on "Sending..."

### PR DESCRIPTION
**Pull request by ichorid**
continued from #5211 
fixes #5167

### CODE REVIEW

**Comment by egbertbouman** [comment]
@ichorid I think it would have been nice if you left a comment at https://github.com/Tribler/tribler/pull/5211 requesting changes instead of closing my PR and cherry-picking the fix. Just an idea for the future.

**Comment by ichorid** [comment]
@egbertbouman , I closed your original PR because I thought you abandoned it and/or was busy with other matters. Tests were broken on that PR, it was not in "draft" state and was not marked WIP either, and there were no signs of activity.

**Comment by egbertbouman** [comment]
@ichorid Still, this wasn't the first time that you've closed/hijacked my PR without any form of discussion. I would appreciate if you stopped doing this.

**Comment by ichorid** [comment]
I didn't know it matters to you that much. I'll take that into consideration next time.

**Pull request merged**
