### PR TITLE
Catch unhandled internal Twisted response error

### LINKED ISSUE #3768: OpenSSL.SSL.Error
From reporter - Tribler 7.1.0-exp3 (#15432)
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 127, in on_read_data
RuntimeError: [Failure instance: Traceback (failure with no frames): <class 'twisted.web._newclient.ResponseNeverReceived'>: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]>]
]
```

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #3768

### CODE REVIEW

**Comment by qstokkink** [comment]
Oh no, sonarcloud is failing. 😨

**Comment by devos50** [comment]
retest this please

**Comment by qstokkink** [comment]
There seems to be some error in the SonarCloud script, it is marking the build as SUCCESS and then crashing: 

```
Fetching task status...
Task done, status: PENDING
SonarQube says OK
Has build IN_PROGRESS with id: AWU9xJksIGZrxxccGODz - waiting 10000 to execute next check.
Has build IN_PROGRESS with id: AWU9xJksIGZrxxccGODz - waiting 10000 to execute next check.
Status => SUCCESS
ERROR: Build step failed with exception
```

**Comment by qstokkink** [comment]
Oh hey, haven't seen that one in a while:

```python
Traceback (most recent call last):
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_tests_GUI_win64\tribler\Tribler\Test\GUI\test_gui.py", line 615, in test_manage_playlist
    self.wait_for_list_populated(window.playlist_manage_in_playlist_list)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_tests_GUI_win64\tribler\Tribler\Test\GUI\test_gui.py", line 146, in wait_for_list_populated
    raise TimeoutException("The list was not populated within 10 seconds")
TimeoutException: The list was not populated within 10 seconds
```

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
It seems SonarCloud was a victim of this bug: https://issues.jenkins-ci.org/browse/JENKINS-45659 , I reset the time to wait from 0 back to the default of 10000. This should be fixed again now (and in the future).

**Pull request merged**
