### PR TITLE
Refactor rest utils

### PR DESCRIPTION
**Pull request by drew2a**
This PR improves the work of rest_utils and finished fix #6738

### CODE REVIEW

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Review by kozlovsky — APPROVED** [review]

**Pull request merged**
