### PR TITLE
READY: Skip test_normal_torrent

### LINKED ISSUE #2411: Unstable test_normal_torrent in Tribler.Test.API.test_seeding.TestSeeding
```
I: ======================================================================
I: ERROR: test_normal_torrent (Tribler.Test.API.test_seeding.TestSeeding)
I: ----------------------------------------------------------------------
I: Traceback (most recent call last):
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/test_as_server.py", line 73, in check
I:     result = fun(*argv, **kwargs)
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/API/test_seeding.py", line 96, in test_normal_torrent
I:     self.subtest_is_seeding()
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/API/test_seeding.py", line 104, in subtest_is_seeding
I:     s.send(CHOKE)
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/btconn.py", line 117, in send
I:     self.s.send(tobinary(len(data)))
I: error: [Errno 32] Broken pipe
I: ----------------------------------------------------------------------
```

```
I: ======================================================================
I: ERROR: test_normal_torrent (Tribler.Test.API.test_seeding.TestSeeding)
I: ----------------------------------------------------------------------
I: Traceback (most recent call last):
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/test_as_server.py", line 73, in check
I:     result = fun(*argv, **kwargs)
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/API/test_seeding.py", line 96, in test_normal_torrent
I:     self.subtest_is_seeding()
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/API/test_seeding.py", line 102, in subtest_is_seeding
I:     s.read_handshake_medium_rare()
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/btconn.py", line 100, in read_handshake_medium_rare
I:     data = self._readn(68)
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/btconn.py", line 149, in _readn
I:     raise ex
I: error: [Errno 104] Connection reset by peer
I: ----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by brussee**
Workaround #2411 for now...

### CODE REVIEW

**Comment by brussee** [comment]
@whirm Ready.

**Comment by whirm** [comment]
I'm waiting for feedback on the issue for this one.

I think this should be fixed instead of skipped.

**Comment by brussee** [comment]
retest this please

**Comment by brussee** [comment]
I agree it should be fixed rather than skipped, but it falls definitively out of my scope.

**Comment by brussee** [comment]
retest this please

**Comment by whirm** [comment]
Let's get the test runner working on jenkins first, then we can worry about the failing tests.

**Comment by brussee** [comment]
Alright

**Pull request closed without merging**
