### PR TITLE
Make LibtorrentMgr non-singleton

### PR DESCRIPTION
**Pull request by LipuFei**

### CODE REVIEW

**Comment by whirm** [comment]
@LipuFei  did you see that one?
```
CRITICAL 1426159149.77            util:63    Unhandled exception raised while running the test: <class 'wx._core.PyDeadObjectError'> PyDeadObjectError('The C++ part of the ListBody object has been deleted, attribute access no longer allowed.',)
CRITICAL 1426159149.77            util:63    Locals by frame, innermost last:
CRITICAL 1426159149.77            util:63    /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py:14665 <lambda>:
CRITICAL 1426159149.77            util:63    |        event = <wx._core.PyEvent; proxy of <Swig Object of type 'wxPyEvent *' at 0x7ff45102c900> >
CRITICAL 1426159149.77            util:63    /home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Main/vwxGUI/__init__.py:123 invoke_func:
CRITICAL 1426159149.77            util:63    |         args = (<Tribler.Main.vwxGUI.list.LocalSearchManager object at 0x7ff3c9ee9410>, <Tribler.Main.Utility.GuiDBHandler.ASyncDelayedResult object at 0x7ff3a1e62150>)
CRITICAL 1426159149.77            util:63    |         func = <function _on_data at 0x7ff4542bf140>
CRITICAL 1426159149.77            util:63    |       kwargs = {}
CRITICAL 1426159149.77            util:63    /home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Main/vwxGUI/list.py:318 _on_data:
CRITICAL 1426159149.77            util:63    |  total_items = 1
CRITICAL 1426159149.77            util:63    | delayedResult = <Tribler.Main.Utility.GuiDBHandler.ASyncDelayedResult object at 0x7ff3a1e62150>
CRITICAL 1426159149.77            util:63    |         self = <Tribler.Main.vwxGUI.list.LocalSearchManager object at 0x7ff3c9ee9410>
CRITICAL 1426159149.77            util:63    |         data = [<Tribler.Main.Utility.GuiDBTuples.ChannelTorrent object at 0x7ff3c9f43c50>]
CRITICAL 1426159149.77            util:63    /home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Main/vwxGUI/__init__.py:114 invoke_func:
CRITICAL 1426159149.77            util:63    |         args = (<Tribler.Main.vwxGUI.list.LibraryList; proxy of <Swig Object of type 'wxBoxSizer *' at 0x5d05160> >, [<Tribler.Main.Utility.GuiDBTuples.ChannelTorrent object at 0x7ff3c9f43c50>])
CRITICAL 1426159149.77            util:63    |         func = <function SetData at 0x7ff4542d3488>
CRITICAL 1426159149.77            util:63    |       kwargs = {}
CRITICAL 1426159149.77            util:63    /home/jenkins/workspace/GH_Tribler_pull-request-tester_devel/tribler/Tribler/Main/vwxGUI/list.py:1900 SetData:
CRITICAL 1426159149.77            util:63    |         self = <Tribler.Main.vwxGUI.list.LibraryList; proxy of <Swig Object of type 'wxBoxSizer *' at 0x5d05160> >
CRITICAL 1426159149.77            util:63    |         data = [('f\xed\x7f0\xe3\xb3\x0f\xa6G\xab\xaa\x19\xa3nu\x03\xaa\x07\x155', [u'Pioneer.One.S01E06.720p.x264-VODO', None, 1622609917, None, None, None, 0, 0, 0, 0, 0, ''], <Tribler.Main.Utility.GuiDBTuples.ChannelTorrent object at 0x7ff3c9f43c50>, <class 'Tribler.Main.vwxGUI.list_item.LibraryListItem'>)]
CRITICAL 1426159149.77            util:63    |         file = <Tribler.Main.Utility.GuiDBTuples.ChannelTorrent object at 0x7ff3c9f43c50>
CRITICAL 1426159149.77            util:63    /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py:14615 __getattr__:
CRITICAL 1426159149.77            util:63    |         self = wxPython wrapper for DELETED ListBody object! (The C++ object no longer exists.)
CRITICAL 1426159149.77            util:63    |         args = ('SetData',)
```

**Comment by LipuFei** [comment]
@whirm Yes. I will look at this later. I am now making a statistics module which can dump statistics data before shutting down, so we can get dispersy community statistics if a test fails.

**Comment by whirm** [comment]
@LipuFei ready?

**Comment by LipuFei** [comment]
@ready

**Pull request merged**
