### PR TITLE
Pr testing do not merge

### PR DESCRIPTION
**Pull request by whirm**

### CODE REVIEW

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by lfdversluis** [comment]
I see you are using the diff-tool :D Looks good, 5 rows now :+1: What does the "Test on Linux" do btw?

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
@lfdversluis it runs the tests on linux :D

**Comment by lfdversluis** [comment]
@whirm huh? Doesn't the **default** do this? Or are you running on BBQ and a linux install (debian vs something else) concurrently? :o

**Comment by devos50** [comment]
@lfdversluis in the future, we want to run unit tests on OS X, Windows and Linux so we want to create separate (testing) jobs for each test platform. The default job can maybe aggregate all the results produced by the subjobs.

**Comment by lfdversluis** [comment]
@devos50 fancy stuff going on here. I like it.

**Pull request closed without merging**
