### PR TITLE
removed old readme file

### LINKED ISSUE #2074: Tribler/readme.txt should be removed
This readme is 6 years old and I don't think it contains any relevant information anymore.

https://github.com/Tribler/tribler/blob/devel/Tribler/readme.txt

### PR DESCRIPTION
**Pull request by lfdversluis**
Fixes #2074

### CODE REVIEW

**Comment by lfdversluis** [comment]
Coverage report makes no sense: https://jenkins.tribler.org/job/GH_Tribler_PR_coverage_check/593//artifact/coverage_report.html

**Comment by lfdversluis** [comment]
Batch 1 hang: https://jenkins.tribler.org/job/GH_Tribler_PR_tests_mac/362/artifact/output/test_runners_output/1.err/*view*/

**Comment by lfdversluis** [comment]
retest this please

**Comment by devos50** [comment]
I suspect that the coverage job in jenkins is fetching the wrong revision when one of the sub-jobs (os x, linux, windows testers) fails.

**Comment by lfdversluis** [comment]
This is only getting worse, now the tests on linux as well as mac failed (and the coverage too).

**Comment by lfdversluis** [comment]
retest this please

**Comment by devos50** [comment]
tests failing on mac is uncommon, I will see whether there is something strange going on on the machine.

**Comment by devos50** [comment]
Fetching the repo from Github appears to take over two minutes and the build times out after three minutes (we have a flexible build timeout and most of the time, builds are completed within two minutes). I will make the timeout more flexible.

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
(made some other changes to the windows and mac builders)

**Comment by lfdversluis** [comment]
@devos50 Looks like the changes were unsuccessful

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by lfdversluis** [comment]
retest this please

**Comment by whirm** [comment]
The tunnel community tests got stuck again: https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/640/artifact/output/test_runners_output/00003.err/*view*/

**Comment by whirm** [comment]
retest this please

**Pull request merged**
