### PR TITLE
Revert searchcommunity update

### PR DESCRIPTION
**Pull request by whirm**
Until we decide what to do about the backward incompatibility.

### CODE REVIEW

**Comment by whirm** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
Everything is included in #1352

**Pull request closed without merging**
