### PR TITLE
Next to devel

### LINKED ISSUE #1938: No channels matching tv assertion when running tests
When running `test_channel_search `, I get the following error:

```
======================================================================
ERROR: test_channel_search (Tribler.Test.test_remote_search.TestRemoteChannelSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester/tribler/Tribler/Test/test_as_server.py", line 72, in check
    process_unhandled_exceptions()
  File "/home/jenkins/workspace/GH_Tribler_pull-request-tester/tribler/Tribler/Test/util.py", line 111, in check_exceptions
    raise Exception("Test raised %d unhandled exceptions, last one was: %s" % (exc_counter, last_exc))
Exception: Test raised 1 unhandled exceptions, last one was: AssertionError('no channels matching tv',)
```

### LINKED ISSUE #2298: Error when running the unit tests
```
Tribler.Test.Core.Libtorrent.test_libtorrent_mgr.TestLibtorrentMgr.test_get_session_one_hop (from nosetests)

FakeTriblerSession instance has no attribute 'set_listen_port_runtime'
```

Reference: https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/1884/testReport/junit/Tribler.Test.Core.Libtorrent.test_libtorrent_mgr/TestLibtorrentMgr/test_get_session_one_hop/

### LINKED ISSUE #2307: Error in API tests
```
Testing whether the API returns a formatted 500 error if ValueError is raised ... Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Core\Utilities\twisted_thread.py", line 55, in _reactor_runner
    reactor.run(installSignalHandlers=False)
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1194, in run
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Core\APIImplementation\threadpoolmanager.py", line 50, in caller
    fun(*args, **kwargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Core\Libtorrent\LibtorrentMgr.py", line 482, in do_dht_check
    lt_session = self.get_session()
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Core\Libtorrent\LibtorrentMgr.py", line 186, in get_session
    if hops not in self.ltsessions:
exceptions.TypeError: argument of type 'NoneType' is not iterable
```

Reference: https://jenkins.tribler.org/job/GH_Tribler_PR_tests_win64/1528/artifact/output/test_runners_output/0.err/*view*/

### LINKED ISSUE #2318: Socket error during tests on 32 bit windows
```
======================================================================
ERROR: test_can_create_engine_wrapper (Tribler.Test.Core.Libtorrent.test_libtorrent_download_impl.TestLibtorrentDownloadImpl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Test\test_as_server.py", line 236, in setUp
    self.session.start()
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Core\Session.py", line 456, in start
    self.lm.register(self, self.sesslock)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Core\APIImplementation\LaunchManyCore.py", line 172, in register
    self.init()
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Core\APIImplementation\LaunchManyCore.py", line 269, in init
    load_communities()
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\dispersy\util.py", line 46, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\dispersy\util.py", line 240, in blockingCallFromThread
    result.raiseException()
  File "<string>", line 2, in raiseException
CannotListenError: Couldn't listen on any:32481: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted.
-------------------- >> begin captured logging << --------------------
```
https://jenkins.tribler.org/job/GH_Tribler_PR_tests_win32/1670/artifact/output/test_runners_output/1.err/*view*/

### LINKED ISSUE #2345: Error in test_downloadfromfile
```
Regression

Tribler.Test.test_libtorrent_download.TestLibtorrentDownload.test_downloadfromfile (from nosetests)
Failing for the past 1 build (Since Failed#2216 )
Took 27 sec.
Error Message

Test raised 1 unhandled exceptions, last one was: TypeError('__init__() takes exactly 2 arguments (1 given)',)
```

Reference: https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/2216/testReport/junit/Tribler.Test.test_libtorrent_download/TestLibtorrentDownload/test_downloadfromfile/

### LINKED ISSUE #2390: "no channels matching de"
https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/2336/testReport/junit/Tribler.Test.test_remote_search/TestRemoteChannelSearch/test_channel_search/

https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/2336/testReport/junit/Tribler.Test.test_remote_search/TestRemoteChannelSearch/test_channel_search_2/

### LINKED ISSUE #2435: test_remotedownload fails due to: 'no hits matching ubuntu + desktop'
One more example of a test that depends on the outside world.
```
Regression

Tribler.Test.test_remote_search.TestMixedRemoteSearch.test_remotedownload (from nosetests)
Failing for the past 1 build (Since Failed#2514 )
Took 42 sec.
Error Message

Test raised 1 unhandled exceptions, last one was: AssertionError('no hits matching ubuntu + desktop',)
```
https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/2514/testReport/junit/Tribler.Test.test_remote_search/TestMixedRemoteSearch/test_remotedownload/

### LINKED ISSUE #2486: test_remote_channel_search: timeout expired before end of test (120.000000 s.)
```
Tribler.Test.test_remote_search.TestRemoteChannelSearch.test_remote_channel_search (from nosetests)
Failing for the past 1 build (Since Failed#2866 )
Took 2 min 0 sec.
Error Message

timeout expired before end of test (120.000000 s.)
```
https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/2866/testReport/junit/Tribler.Test.test_remote_search/TestRemoteChannelSearch/test_remote_channel_search/

### PR DESCRIPTION
**Pull request by devos50**
This PR attempts to stabilise the unit tests on Linux, MacOS and Windows. There are various major changes to the way the tests are structured. This work also contains some fixes. The most impacting change is that the `setUp` and `tearDown` of the unit tests are asynchronous now and are returning deferreds.

I also completely refactored the search community tests that are now more local and are not using the live Dispersy network. This makes the search community tests way more stable.

Fixes #2390, fixes #2486, fixes #2435, fixes #2390, fixes #2345, fixes #2318, fixes #2307, fixes #2298, fixes #1938.

### CODE REVIEW

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please
Test Result (2 failures / +2)
[Tribler.Test.test_remote_torrent_handler.TestRemoteTorrentHandler.test_torrentdownload](https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/3416/testReport/junit/Tribler.Test.test_remote_torrent_handler/TestRemoteTorrentHandler/test_torrentdownload/)
[Tribler.Test.Core.test_unicode.TriblerCoreTestUnicode.test_unicode_dunno_2](https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/3416/testReport/junit/Tribler.Test.Core.test_unicode/TriblerCoreTestUnicode/test_unicode_dunno_2/)

**Comment by synctext** [comment]
[Test Result (2 failures / ±0)
Tribler.Test.Core.Libtorrent.test_libtorrent_download_impl.TestLibtorrentDownloadImpl.test_setup
Tribler.Test.Core.Libtorrent.test_libtorrent_download_impl.TestLibtorrentDownloadImplNoSession.test_torrent_checked_alert](https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/3413/testReport/)

**Comment by synctext** [comment]
Test Result (2 failures / +2)
[Tribler.Test.Core.Modules.RestApi.test_events_endpoint.TestEventsEndpoint.test_family_filter_search
Tribler.Test.Core.Modules.RestApi.test_events_endpoint.TestEventsEndpoint.test_family_filter_search](https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/3412/testReport/)

**Comment by devos50** [comment]
@synctext the errors you linked are already solved 👍

**Comment by devos50** [comment]
AllChannel succeeded with this code. I will clean up the commit history a bit more and merge the PRs I opened for Gumby, Dispersy and Tribler.

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
No major race conditions left. There might be some well-hidden race conditions but I will attempt to fix these in later PRs. Please keep in mind that the `setUp` and `tearDown` method in the tests are now returning a deferred.

**Pull request merged**
