### PR TITLE
First attempt at removing the ThreadPool and UCH

### PR DESCRIPTION
**Pull request by NielsZeilemaker**

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
It's clearly not ready, I'll have another go in a bit

**Comment by synctext** [comment]
Removing ThreadPool and UserCallbackHandler.py.. Nice stuff.
We're getting ready for an RC1 this Wednesday.

**Comment by NielsZeilemaker** [comment]
I wouldn't add this to RC1, its pretty unstable at the moment.

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
@NielsZeilemaker I'll pick up your work and continue from here it that's OK.

**Comment by NielsZeilemaker** [comment]
Sure np

**Comment by whirm** [comment]
Closing this one, work will be continued here: https://github.com/Tribler/tribler/pull/1461

**Pull request closed without merging**
