### PR TITLE
Put TriblerDownloads to Downloads/ instead of Desktop/ by default

### LINKED ISSUE #1014: TriblerDownloads should be in Downloads, not on Desktop
It is quite foreign to put ANYTHING on the desktop for Windows. On a Mac it may somehow be acceptable. Change the default directory to %userprofile%\Downloads for Windows.

### PR DESCRIPTION
**Pull request by whirm**
Closes #1014 
Closes #1017

Do not merge until tested on windows and mac

### CODE REVIEW

**Comment by whirm** [comment]
@LipuFei do you have a windows machine to test this at hand?

**Comment by LipuFei** [comment]
@whirm No, I will test it next Monday.

**Comment by LipuFei** [comment]
@whirm Tested on both Windows and Mac. All good. I will merge it.

**Comment by whirm** [comment]
great

**Pull request merged**
