### PR TITLE
Cleanup old metadata stuff 2

### PR DESCRIPTION
**Pull request by LipuFei**
Some more cleanup for old metadata.

After this one I will make a PR for the new metadata implementation.

### CODE REVIEW

**Comment by LipuFei** [comment]
@whirm @NielsZeilemaker Ready when it passes

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
@whirm Does the isolated cache have "ubuntu" torrent? It failed this test twice.

**Comment by LipuFei** [comment]
retest this please

**Comment by whirm** [comment]
If nobody modified it, it is :)

**Pull request merged**
