### PR TITLE
add unique infohash-pk constraints on DB

### PR DESCRIPTION
**Pull request by ichorid**
This adds Pony-level uniqueness constraints on the combination of infohash+public_key. Essentially, this prevents the creation of torrent entries with duplicate infohashes in a single channel.
EDIT:
I promoted the `infohash` field in `TorrentMetadata` from `Optional` to `Required` to be in line with the new constraints.

### CODE REVIEW

**Comment by ichorid** [comment]
@devos50 , please look at the GUI tests. I don't get why these fail.

**Comment by qstokkink** [comment]
You should still fix the C0301 Pylint error.

**Comment by devos50** [comment]
@ichorid I will look at the GUI tests. Please fix the flake8 errors too.

**Comment by devos50** [comment]
@ichorid The GUI tests should be fixed by #4260. Please rebase on the latest commit of devel.

**Pull request merged**
