### PR TITLE
Checkpoint downloads earlier for persistence between restarts

### LINKED ISSUE #3046: Missing torrent after crash
- [X] I have read CONTRIBUTING.rst

- [X] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
$ git status
On branch next
Your branch is up-to-date with 'origin/next'.
nothing to commit, working directory clean

##### Operating system and version: #####
Ubuntu 16.04

This morning I was cleaning up the finished torrents, I had only one torrent still downloading at ~5KB/s. After removing two torrents from the GUI, tribler crashed as mentioned in #3039 But after the restart the torrent that was still downloading is gone. Files still exists in the download folder but the torrent is not listed anymore.

Looking at the logs the only thing that is strange is that currently the log is filled with a lot of these messages. These messages are not showing before the crash, but after the crash they did.
```
WARNING:SearchCommunity:unable to find conversion to decode 0001fb04df93369587ec8fd9b74559186fa356cffda8f561f1730ce2b03f1ed74582504d684a078d0ece4700000000000000025ed0001e1e4f83b41b9b191783b41b9b1917c0a8010c1e4f4e2d7ace1e4f00611503623b515f7f125bc9748c39a3b2678d6c3092b7f6007831d126f308c63f242e549784a84ea16dc55932 in [<DefaultConversion 0000 [dispersy-dynamic-settings, dispersy-missing-identity, dispersy-missing-sequence, dispersy-missing-message, dispersy-puncture-request, dispersy-undo-other, dispersy-signature-response, dispersy-destroy-community, dispersy-introduction-response, dispersy-identity, dispersy-signature-request, dispersy-authorize, dispersy-puncture, dispersy-missing-proof, dispersy-revoke, dispersy-undo-own, dispersy-introduction-request]>, <SearchConversion 0002 [dispersy-missing-message, torrent-collect-request, dispersy-signature-response, search-response, dispersy-missing-identity, torrent-collect-response, dispersy-puncture-request, dispersy-undo-other, dispersy-dynamic-settings, dispersy-undo-own, dispersy-introduction-request, dispersy-missing-sequence, dispersy-destroy-community, dispersy-introduction-response, dispersy-identity, dispersy-signature-request, dispersy-revoke, dispersy-puncture, torrent-request, search-request, dispersy-authorize, dispersy-missing-proof, torrent]>]
```

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #3046 (again).

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
@devos50 this 1 line fix is ready for review (win 64 is unstable as you know).

**Comment by qstokkink** [comment]
retest this please

**Comment by devos50** [comment]
Hmm could that win32 error be caused this PR?

**Comment by qstokkink** [comment]
retest this please

**Pull request merged**
