### PR TITLE
Added "compensation payouts" to bandwidth crawler

### PR DESCRIPTION
**Pull request by devos50**
In this PR, I extended the bandwidth crawler to support "compensation payouts". These crawlers can payout some bandwidth to users, which helps us in reducing the effects of updating to Tribler 7.6 (which resets the token balance). Only users with a positive token balance are eligible for this compensation.

I also fixed two other, minor issues:
- Set the `target_peers` for the random walk strategy used by the bandwidth crawler to unlimited.
- Fixed an issue with fetching the latest transaction from the database.

### CODE REVIEW

**Review by grimadas — APPROVED** [review]
L G T M

**Comment by ichorid** [comment]
This is a crawler, so we're supposed to run it ourselves? Why do we have to put it on `release-7.6` then? I would argue that we indeed should not even merge it in devel, but just keep it in a separate branch and run it manually.

**Comment by devos50** [comment]
I deployed this crawler on a machine on our infrastructure.

Regarding code organization, we might choose to move all crawler code to a separate branch or repo. I'm fine with that but then we should move _all_ scripts (including the tunnel helper scripts) for consistency. For now, I've chosen to do it like this.

Should we create a separate issue for this?

**Comment by devos50** [comment]
> We should at least discuss it. I don't want the stuff to be in the same repo, or at least in the same Python package as the main stuff.

That's fair. I would be fine with moving these scripts in a separate repo, but then I argue we should treat experimental code (e.g., in the `experiments` directory) the same.

**Comment by synctext** [comment]
bit of a monorepo person. just browsing through all the fragmentation we have. So many Tribler/repoX fragments, I find it more messy..

**Comment by devos50** [comment]
> I don't want the stuff to be in the same repo

> bit of a monorepo person.

I think we already had this discussion a while ago and we decided to keep everything within one repository, right?

**Comment by synctext** [comment]
yes please

**Comment by ichorid** [comment]
I propose to create a separate `tribler-tools` package/dir then in our `src` directory for such stuff. We want to start doing proper package management eventually.

**Comment by devos50** [comment]
This is fixed by #5995.

**Pull request closed without merging**
