### PR TITLE
WIP: tunnel speedup

### PR DESCRIPTION
**Pull request by lfdversluis**

### CODE REVIEW

**Comment by lfdversluis** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by whirm** [comment]
https://jenkins.tribler.org/job/GH_Tribler_pull-request-tester/5366/artifact/output/test_runners_output/00000.err/*view*/

`
test_anon_download_without_relays (Tribler.Test.test_tunnel_community_negative.TestTunnelCommunityNegative) ... [xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:179: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
/home/jenkins/workspace/GH_Tribler_pull-request-tester/gumby/scripts/wrap_in_vnc.sh: line 79: 42321 Aborted                 $*
`

**Comment by lfdversluis** [comment]
@whirm this is branched of the latest devel branch. We had fixed this last month right?

**Comment by whirm** [comment]
It's weird that this happened just on the tunnel tests. Have a look and see if for some reason the xinit stuff is not called on those tests.

**Comment by whirm** [comment]
let's re-run it and see if it happens on the same place

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
Oh, I think I know what's going on.

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
I'm trying to trace where the segfault happens.

**Comment by lfdversluis** [comment]
Closing this one as current work is being focussed on other items.

**Pull request closed without merging**
