### PR TITLE
Refactoring: moving multiple is_frozen definitions to tribler_common

### LINKED ISSUE #5233: The is_frozen function is defined three times
The `is_frozen` function that returns a boolean whether we are operating in a frozen environment, is defined in three files: `tribler_gui/utilities.py`, `vlc.py` and `install_dir.py`. We should move this method to the `tribler_common` package and import it from there.

### PR DESCRIPTION
**Pull request by mrcruz**
This implements  #5233.

It was a simple issue, but I don't think I fully understand the is_frozen function. I did some basic testing and it appears nothing changed but I would like someone else's perspective.

Fixes #5233

### CODE REVIEW

**Comment by devos50** [comment]
ok to test

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
@mrcruz If you are interesting in fixing another (relatively easy) issue, please have a look at #4623. You can reproduce it by change the `triblerd.conf` file in your Tribler state directory.

**Comment by qstokkink** [comment]
> there is most likely no easier way to check if we are in a frozen environment.

Challenge accepted:

```python
def is_frozen():
    return hasattr(sys, "_MEIPASS")
```

**Comment by devos50** [comment]
@qstokkink Ok, there is definitely an easier way 👍 . However, I'm not completely sure if that would work for all frozen environments, given the magic inner workings of PyInstaller and custom logic for cross-platform support. At least we are confident that the current method functions correctly.

**Pull request merged**
