### PR TITLE
Trust graph pyqtgraph version

### PR DESCRIPTION
**Pull request by xoriole**

### CODE REVIEW

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by devos50** [comment]
Getting this message:

```
Warning: QApplication was created before pyqtgraph was imported; there may be problems (to avoid bugs, call QApplication.setGraphicsSystem("raster") before the QApplication is created).
```

**Comment by xoriole** [comment]
Checked pyqtgraph code, I think we can ignore this warning that happens in MacOS.

```python
if 'linux' in sys.platform:  ## linux has numerous bugs in opengl implementation
    useOpenGL = False
elif 'darwin' in sys.platform: ## openGL can have a major impact on mac, but also has serious bugs
    useOpenGL = False
    if QtGui.QApplication.instance() is not None:
        print('Warning: QApplication was created before pyqtgraph was imported; there may be problems (to avoid bugs, call QApplication.setGraphicsSystem("raster") before the QApplication is created).')
    if QtGui.QApplication.setGraphicsSystem:
        QtGui.QApplication.setGraphicsSystem('raster')  ## work around a variety of bugs in the native graphics system 
else:
    useOpenGL = False  ## on windows there's a more even performance / bugginess tradeoff. 

```
Reference: [pyqtgraph/pyqtgraph/__init__.py](https://github.com/mfitzp/pyqtgraph/blob/e0c22e27965bd6b44d7e07a175561d0b4b8ef164/pyqtgraph/__init__.py#L42)

Other than this I think PR is ready

**Comment by xoriole** [comment]
Screenshot of simplified Trust graph
trust-graph

**Comment by synctext** [comment]
Nice!
Can you make the red less scary?

**Comment by xoriole** [comment]
Lighter red version
trust-graph-less-scary

**Comment by devos50** [comment]
I personally would prefer it if the node color of selfish users is a bit more red.

**Pull request merged**
