### PR TITLE
Fix basestring and unichr in Tribler/Test

### PR DESCRIPTION
**Pull request by cclauss**
In Tribler/Test:
* __from six import unichr__
* Change __basestring__ --> __six.string_types__

### CODE REVIEW

**Comment by devos50** [comment]
ok to test

**Comment by cclauss** [comment]
Do we really gotta change every __xrange()__ --> __grange()__ and then a year from now change every __grange()__ --> __range()__??  Can't we just __from six.moves import xrange__ and then come back next year?

**Comment by qstokkink** [comment]
@cclauss I completely missed [the specification of `six.moves`](https://pythonhosted.org/six/#module-six.moves) when porting IPv8. You're right, we should use that instead of our own `grange`.

**Comment by cclauss** [comment]
Great news!

**Comment by devos50** [comment]
Really minor comment: could you please capitalise the `READY` prefix in your title? This makes it a bit more outstanding amongst the other issues 👍

**Comment by devos50** [comment]
Also, please rebase this PR on the latest `devel` commit 👍

**Comment by devos50** [comment]
@cclauss is this PR ready?

**Comment by cclauss** [comment]
READY

**Comment by devos50** [comment]
Thanks! 👍

**Pull request merged**
