### PR TITLE
Fixed #1907

### LINKED ISSUE #1907: Network graph backgrounds are pained gray instead of white
That's on `devel` I assume due to the switch to WX3?

See:

https://jenkins.tribler.org/job/GH_Tribler_pull-request-tester/5569/artifact/output//Screenshot-39.png

### PR DESCRIPTION
**Pull request by devos50**
The background color of the network graph is now white.

### CODE REVIEW

**Comment by whirm** [comment]
Amazing that all the tests passed! :D

**Comment by devos50** [comment]
Yeah lucky run :)

**Comment by lfdversluis** [comment]
Funny that yesterday nothing would pass and this one does. I will start investigating it, would be really helpful if I can reproduce it on my machine but only bbq has this issue (un)fortunately.

**Comment by whirm** [comment]
@lfdversluis I can reproduce it too on my debian SID

**Pull request merged**
