### PR TITLE
Fixed loading of config, added option to limit number of connections per download

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by devos50** [comment]
@dufernst See https://jenkins.tribler.org/job/Build_Tribler_devel/162/ for the experimental Tribler 7 binaries.

**Comment by dufernst** [comment]
Win 8.1 -> Start Tribler -> Open Settings -> Crash
crash16708

**Comment by devos50** [comment]
@dufernst this build should fix it: https://jenkins.tribler.org/job/Build_Tribler_devel/167/

**Comment by synctext** [comment]
@dufernst please let us know if this fixes or fails to fix things for you. We are trying to get rid of lot of bugs...

**Comment by dufernst** [comment]
Seems to work. If I come across anything else I'll let you know.

**Comment by devos50** [comment]
@dufernst great, thanks!

**Pull request merged**
