### PR TITLE
Allow simultaneously downloading using hidden services/exit nodes

### PR DESCRIPTION
**Pull request by egbertbouman**

### CODE REVIEW

**Comment by synctext** [comment]
922 deleted lines, impressive! btw, see my email reply...

**Comment by egbertbouman** [comment]
@synctext That's mostly due to old testing code being removed.

**Comment by rjruigrok** [comment]
Exactly. I removed most of the devriso tests from the codebase. :smile: 

@synctext Regarding the email reply: the circuit to the introduction point is not only subject to timing out, but there is also a risk of a relay in between going offline, breaking the circuit down. In the current setup it will not recreate a circuit to this introduction point, but the seeder should ideally always rebuild a new circuit to the same introduction point again and again. The only exception is when the introduction point itself goes offline.

**Comment by egbertbouman** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by egbertbouman** [comment]
@synctext It won't pass. I'll fix it in a bit.

**Comment by synctext** [comment]
Looking forward to testing this soon! Amazing amount of changes..
```
RuntimeError: Dispersy is not running
```

**Comment by rjruigrok** [comment]
Nice @egbertbouman ! :+1:

**Comment by synctext** [comment]
Yeah!   :+1:

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by rjruigrok** [comment]
retest this please

**Comment by synctext** [comment]
@egbertbouman Almost works.. Tried Ubuntu.iso downloading with my test network of 10 tunnel clients (including exit nodes, -x true)
```
env PYTHONPATH=. python -O Tribler/community/tunnel/main.py -x true
```
However, the peer discovery seems to fail. Some data is getting through the circuits
tribler_6 5pre_no_peers_found_in_ubuntu_swarm

**Comment by egbertbouman** [comment]
I don't think this is caused by this PR. If I've understood @rjruigrok correctly, selecting 1-hop tunnels is broken on current devel, so maybe that's the problem.

**Comment by rjruigrok** [comment]
I will have a look at these issues. :)

**Comment by synctext** [comment]
Wow, after 12 hours it worked a bit. It actually downloaded 97.7% of the Ubuntu 15.04 swarm! 1-hop anon download.. Lot of complains, warnings from this code, and my laptop CPU cooler fan is making ratling noises... 10 tunnel processes take 15% load on all 4 cores, not bad actually.
```
env PYTHONPATH=. python -O Tribler/community/tunnel/main.py -x true
ERROR   1433174314.91            main:34    Yappi not installed, profiling options won't be available
INFO    1433174314.91            main:366   Exit-node enabled
ERROR   1433174315.17   LibtorrentMgr:115   could not restore dht state, starting from scratch
INFO    1433174315.17            main:130   Using port 24742
ERROR   1433174784.08 tunnel_community:1115  Got destroy from {192.168.1.145:7759 130.161.211.97:7759} for circuit 844505126
ERROR   1433174784.09 tunnel_community:1115  Got destroy from {192.168.1.145:24103 130.161.211.97:24103} for circuit 3785300282
ERROR   1433174784.09 tunnel_community:1121  Got an exit socket 3785300282 ('192.168.1.145', 24103)
ERROR   1433178907.07 tunnel_community:894   Don't know how to decrypt incoming message for circuit_id 3658450464
ERROR   1433178920.79 tunnel_community:143   Failed to write data to transport: Invalid argument. Destination: ('202.215.122.160', 0)
ERROR   1433178920.79 tunnel_community:1189  Dropping data packets while EXITing
ERROR   1433199180.04 tunnel_community:143   Failed to write data to transport: Invalid argument. Destination: ('73.11.125.100', 0)
ERROR   1433199180.05 tunnel_community:1189  Dropping data packets while EXITing
ERROR   1433200707.35 tunnel_community:143   Failed to write data to transport: Invalid argument. Destination: ('202.215.122.160', 0)
ERROR   1433200707.35 tunnel_community:1189  Dropping data packets while EXITing
```
This took 1706018 data packets in the community, see below. That is 1.7 million times 1K-ish of data. Was is the default payload size of the data packets? Filesize is 1.07GByte. But *1.7* GByte of data was going over the tunnels, strange.
tribler_6 5pre_actual_data_going_through_tunnels

@rjruigrok @egbertbouman However, all 8 non-exit processes get asked to be exit in above committed code:
```
ERROR   1433232764.59 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232772.68 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232779.58 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232780.59 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232810.57 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232819.58 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232827.68 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232834.57 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232835.57 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232869.57 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232877.56 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232884.57 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232919.50 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232926.50 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232928.57 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232968.62 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232969.55 tunnel_community:1179  Dropping data packets, refusing to be an exit node
ERROR   1433232970.55 tunnel_community:1179  Dropping data packets, refusing to be an exit node
```

**Comment by rjruigrok** [comment]
@synctext The 8 non exit processes were failing because with yesterday devel code the 1 hop circuits were most not working at all, this was fixed by my PR merged by @egbertbouman at midnight. 

It's surprising that it actually reached 98% at all from the linux swarm! :smiley: 
With current devel this should be much faster.

**Pull request merged**
