### PR TITLE
Add missing Arch deps for devel

### PR DESCRIPTION
**Pull request by sum01**
Ran into multiple ImportError's while trying to use devel branch cddfbad065c9a1425e3889f2d45391d15da8480b, fixed with these deps.

### CODE REVIEW

**Comment by devos50** [comment]
Ok to test

**Comment by vandenheuvel** [comment]
I'm on Arch as well, I don't need `python2-libnacl`.

**Comment by devos50** [comment]
@vandenheuvel that's correct, libnacl is included as submodule of Dispersy (which is a submodule of Tribler). @sum01 did you really need that dependency? If not, please remove it and I will merge this PR 👍

**Comment by sum01** [comment]
Well I `sudo pacman -Rs tribler-git` to remove my pkg & deps, removed `python2-libnacl` from the pkgbuild deps, then reinstalled and got this
```
Traceback (most recent call last):
  File "run_tribler.py", line 9, in <module>
    from TriblerGUI.tribler_window import TriblerWindow
  File "/usr/share/tribler/TriblerGUI/tribler_window.py", line 18, in <module>
    from TriblerGUI.core_manager import CoreManager
  File "/usr/share/tribler/TriblerGUI/core_manager.py", line 26, in <module>
    from Tribler.Core.Session import Session
  File "/usr/share/tribler/Tribler/Core/Session.py", line 18, in <module>
    import Tribler.Core.permid as permid_module
  File "/usr/share/tribler/Tribler/Core/permid.py", line 10, in <module>
    from Tribler.dispersy.crypto import LibNaCLSK
  File "/usr/share/tribler/Tribler/dispersy/crypto.py", line 13, in <module>
    import libnacl.dual
ImportError: No module named libnacl.dual
```
So I'm pretty sure I need it. That's why I originally added it to my deps, as I already ran into a bunch of ImportError's trying to install from `devel`

**Comment by sum01** [comment]
and yes, submodules are updated. I saw https://github.com/Tribler/tribler/issues/3027 so I added
```
  git submodule init
  git submodule update
```
into [my pkgbuild](https://github.com/sum01/aur-packages/blob/master/tribler-git/PKGBUILD) before posting any issues/PR's.

**Comment by qstokkink** [comment]
@sum01 `libnacl` is a submodule of the `dispersy` submodule. Just to be sure, does:

 `git submodule update --init --recursive`

fix the libnacl issue?

**Comment by sum01** [comment]
@qstokkink That fixed it. I guess I'll remove libnacl from the commit then.

**Pull request merged**
