### PR TITLE
Use logging level instead of filter

### PR DESCRIPTION
**Pull request by ichorid**
Currently, we use Python logger in a wrong way: we setup `DEBUG` level logging for console, while using `info_filter` for sifting for `INFO` messages. The result is that `WARNING` and `ERROR` messages are not shown at the console. The correct way is to instead change the default console log handler to use `INFO` level by default, and stop using `info_filter` altogether.

### CODE REVIEW

**Comment by ichorid** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by devos50** [comment]
[This run](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_linux_pytest/2607/) probably triggered #6176:

```
fake_udp_socket_manager = <tribler_core.components.torrent_checker.torrent_checker.tests.test_torrentchecker_session.FakeUdpSocketManager object at 0x7f768516a040>

    def test_failed_unicode_udp(fake_udp_socket_manager):
>       session = UdpTrackerSession("localhost", ("localhost", 8475), "/announce", 0, None, fake_udp_socket_manager)

src/tribler-core/tribler_core/components/torrent_checker/torrent_checker/tests/test_torrentchecker_session.py:349: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/tribler-core/tribler_core/components/torrent_checker/torrent_checker/torrentchecker_session.py:258: in __init__
    super().__init__('udp', tracker_url, tracker_address, announce_page, timeout)
src/tribler-core/tribler_core/components/torrent_checker/torrent_checker/torrentchecker_session.py:53: in __init__
    super().__init__()
src/pyipv8/ipv8/taskmanager.py:57: in __init__
    self._checker = self.register_task('_check_tasks', self._check_tasks,
src/pyipv8/ipv8/taskmanager.py:110: in register_task
    task = ensure_future(interval_runner(delay, interval, task, *args))
/usr/lib/python3.8/asyncio/tasks.py:671: in ensure_future
    loop = events.get_event_loop()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <asyncio.unix_events._UnixDefaultEventLoopPolicy object at 0x7f768516a2e0>

    def get_event_loop(self):
        """Get the event loop for the current context.
    
        Returns an instance of EventLoop or raises an exception.
        """
        if (self._local._loop is None and
                not self._local._set_called and
                isinstance(threading.current_thread(), threading._MainThread)):
            self.set_event_loop(self.new_event_loop())
    
        if self._local._loop is None:
>           raise RuntimeError('There is no current event loop in thread %r.'
                               % threading.current_thread().name)
E           RuntimeError: There is no current event loop in thread 'Dummy-1'.

/usr/lib/python3.8/asyncio/events.py:639: RuntimeError
```

**Comment by kozlovsky** [comment]
The code in this PR does not completely fixes the issue. I discussed with @ichorid and we decided that I'll take this task in issue #6581 and propose more complete solution.

**Pull request closed without merging**
