### PR TITLE
Issue 2234 fix delete sqlitecachedb

### LINKED ISSUE #2234: Delete in sqlitecachedb is broken when passing a tuple.
It passes args.values() which is wrong. No test was written for this and luckily no code calls it, else it would've crashed.

### PR DESCRIPTION
**Pull request by lfdversluis**
Fixes **1** bug
Adds **2** tests

Fixes #2234

### CODE REVIEW

**Comment by lfdversluis** [comment]
@devos50 Can you review?

**Comment by devos50** [comment]
Looks fine, I have no comments

**Comment by lfdversluis** [comment]
`exceptions.AssertionError: [('<Candidate 193.35.51.107:33657>', "'A\\x00\\xfc6\\xc8\\xc3q\\x16\\x00\\x00\\x00\\x00\\x00\\x10\\x00\\x00\\x16\\xed\\x00\\x00'")]` in tunnel_community_negative

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
`TestLibtorrentDownload.test_downloadfromurl - no download progress - Condition was not satisfied in 10 seconds`

**Comment by lfdversluis** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by lfdversluis** [comment]
```
File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xf1 in position 62: invalid continuation byte
```

Which goes wrong here ` File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/APIImplementation/maketorrent.py", line 246, in pathlist2filename
    return fullpath.decode('utf-8')`. Will create an issue for this.

**Comment by lfdversluis** [comment]
retest this please

**Pull request merged**
