### PR TITLE
Fixed addtorrent

### LINKED ISSUE #1361: Can't insert https:// link to torrent file into Tribler
For example, `https://tails.boum.org/torrents/files/tails-i386-1.3.2.torrent`.

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
Now supporting
* http, https
* magnet
* emc
* file:

links from the AddDialog, searchBars, and commandline.
Fixes #1361

### CODE REVIEW

**Comment by whirm** [comment]
@NielsZeilemaker ready?

**Comment by NielsZeilemaker** [comment]
yes

**Comment by themusicgod1** [comment]
Why disable https valid certificate check?

**Comment by NielsZeilemaker** [comment]
The example url from the original issue actually didn't include a valid certificate. But you're right we should show a warning. 
Please create a new issue for this.

**Pull request merged**
