### PR TITLE
Fixes #5887: fix default search order for FTS queries

### LINKED ISSUE #5887: [UX] Search results are not relevant
Version: 7.6.1 (latest devel)

image

##### Steps to reproduce the behavior: #####

1. Run a Tribler instance
2. Search for "ubuntu"

##### Expected behavior: #####

Results, ranked by relevance and health

Note: maybe, folders should be more relevant than torrents (a discussion is needed)
##### Actual behavior: #####

Probably, I see the raw results of a Full-Text Search query execution from DB.

### PR DESCRIPTION
**Pull request by kozlovsky**
This PR sorts full-text search results by default in the following order:
1. Channels
2. Folders
3. Torrents with seeders
4. Other torrents

### CODE REVIEW

**Comment by kozlovsky** [comment]
retest this please

**Comment by kozlovsky** [comment]
retest this please

**Comment by kozlovsky** [comment]
retest this please

**Comment by kozlovsky** [comment]
retest this please

**Review by drew2a — APPROVED** [review]
Nice tests 👍

**Comment by kozlovsky** [comment]
retest this please

**Review by drew2a — APPROVED** [review]

**Pull request merged**
