### PR TITLE
Remove plyvel and plyvel related code

### LINKED ISSUE #2005: Plyvel support can be removed from Tribler
@brussee Fixed python-levedb and sent a recipe to python4android upstream's so Tribler can use the same bindings across all supported OSs.

@devos50 just to confirm: OSX is not using plyvel either, right?

### PR DESCRIPTION
**Pull request by lfdversluis**
Plyvel is no longer a dependency. Closes #2005

### CODE REVIEW

**Comment by lfdversluis** [comment]
@whirm I just noticed that the docs on arch linux were changed. Apparently leveldb is not on Pacman (Arch Linux), but is available [here](https://aur.archlinux.org/packages/python2-leveldb-svn/). I do not have any experience with Arch Linux, so what is the best practice here?

**Comment by whirm** [comment]
Is plyvel on arch?

**Comment by lfdversluis** [comment]
Yes, plyvel is available (on pacman).

**Comment by whirm** [comment]
Then let's not remove plyvel support then.

**Comment by whirm** [comment]
Thanks for noticing BTW, would have been a shitty move for them :D

**Comment by lfdversluis** [comment]
Yes, currently the only leveldb package is in the user repository. I'll close this PR

**Pull request closed without merging**
