### PR TITLE
Install pip dependencies during the build

### PR DESCRIPTION
**Pull request by xoriole**
Fixes https://github.com/Tribler/tribler/issues/6518

### CODE REVIEW

**Comment by drew2a** [comment]
I guess the target branch should be `release/7.11`?

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Review by kozlovsky — APPROVED** [review]

**Pull request merged**
