### PR TITLE
Bartercast4 unittests for statistics.py

### PR DESCRIPTION
**Pull request by corpaul**

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
The statistics database is never closed, extend the unload_community method as done in bartercast3 and close the statistics database.

**Comment by NielsZeilemaker** [comment]
Instead of starting Tribler to get a reference to dispersy, you could also instantiate a dispersy using:
```
dispersy = Dispersy(ManualEnpoint(0), u".", u":memory:")

**Comment by NielsZeilemaker** [comment]
You need to convince your statistics database to switch to memory as well, I seem to remember doing this but I cannot find it anywhere.
In the open method of the StatisticsDatabase, something like:
```
if dispersy.database.filepath == ':memory:' ->use memory as well, else use filename

**Comment by corpaul** [comment]
yes but I do not want to do this... for testing the persist functionality I need to check that it actually writes stuff to HD

**Comment by NielsZeilemaker** [comment]
makes sense :smile: but then remove the databasefilename argument from dispersy (":memory:") and create a new statedir using the getStateDir() method from testasaserver

**Comment by NielsZeilemaker** [comment]
Extend AbstractServer instead, and simply call self.getStateDir().
Moreover, call the super().setUp() from your setUp and remove you custom teardown.

**Comment by corpaul** [comment]
Thanks for the suggestions @NielsZeilemaker  , makes the code much clearer

**Comment by corpaul** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
retest this please

**Comment by corpaul** [comment]
@NielsZeilemaker any idea why this is failing? it doesn't like it's because of my code

**Comment by NielsZeilemaker** [comment]
It seems to deadlock/be stuck at the ff test, but why I have no clue. Does it run locally for you?

**Comment by corpaul** [comment]
Locally it fails as well : 
Tribler.Main.tribler_main: INFO: Client shutting down. Sleeping for a few seconds to allow other threads to finish
UnhandledExceptionCatcher: CRITICAL: The following unhandled exceptions where raised during this test's execution:
UnhandledExceptionCatcher: CRITICAL: Unhandled exception raised while running the test: <type 'exceptions.AssertionError'> AssertionError('could not find ChannelListItem',)
UnhandledExceptionCatcher: CRITICAL: Locals by frame, innermost last:
UnhandledExceptionCatcher: CRITICAL: /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_misc.py:1358 Notify:
UnhandledExceptionCatcher: CRITICAL: |         self = <wx._misc.PyTimer; proxy of <Swig Object of type 'wxPyTimer *' at 0x59e1500> >
UnhandledExceptionCatcher: CRITICAL: /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py:14767 Notify:
UnhandledExceptionCatcher: CRITICAL: |         self = <wx._core.CallLater instance at 0x59c7320>
UnhandledExceptionCatcher: CRITICAL: /home/corpaul/workspace/tribler/Tribler/Test/test_remote_search.py:56 do_doubleclick:
UnhandledExceptionCatcher: CRITICAL: |        items = {}
UnhandledExceptionCatcher: CRITICAL: |         self = <Tribler.Test.test_remote_search.TestRemoteQuery testMethod=test_channelsearch>
UnhandledExceptionCatcher: CRITICAL: |    do_assert = <function do_assert at 0x3bb77d0>
UnhandledExceptionCatcher: CRITICAL: /home/corpaul/workspace/tribler/Tribler/Test/test_as_server.py:296 assert_:
UnhandledExceptionCatcher: CRITICAL: |    do_assert = True
UnhandledExceptionCatcher: CRITICAL: |       reason = 'could not find ChannelListItem'
UnhandledExceptionCatcher: CRITICAL: |      boolean = False
UnhandledExceptionCatcher: CRITICAL: |         self = <Tribler.Test.test_remote_search.TestRemoteQuery testMethod=test_channelsearch>


however I can also not really relate this to my code..

**Comment by NielsZeilemaker** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
@corpaul I did you rebase devel into your branch locally? I'm guessing that's causting the error you're seeing.

**Comment by corpaul** [comment]
Hmm guess I rebased too long ago... locally I just rebased against devel and the test runs fine now.

**Comment by NielsZeilemaker** [comment]
rebase this please

**Comment by NielsZeilemaker** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
retest this please

**Comment by corpaul** [comment]
@NielsZeilemaker ready to merge

**Comment by NielsZeilemaker** [comment]
Completely forgot, sorry about that

**Pull request merged**
