### PR TITLE
Move remote torrent search code to Tribler Core

### PR DESCRIPTION
**Pull request by LipuFei**

### CODE REVIEW

**Comment by LipuFei** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by synctext** [comment]
@LipuFei @whirm Search community is broken in current devel for me.
After 4 minutes I only got 1 candidate.
Can you reproduce that? That would mean unit tests with remote search will fail often...

**Comment by LipuFei** [comment]
@synctext We have changed the master key of the SearchCommunity. That's why you only have 1 candidate.

**Comment by LipuFei** [comment]
@synctext You are only able to connect to the bots in the isolated tests, so we are now relying on the isolated tests before the next release.

**Comment by LipuFei** [comment]
@whirm ready

**Pull request merged**
