### PR TITLE
Changed check when fetching discovered channels in tests

### LINKED ISSUE #2333: Error in REST API when fetching all discovered channels on win32 tester
I got the following error on the Windows 32-bit tester:

```
======================================================================
FAIL: Testing whether the API returns inserted channels when fetching discovered channels
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Test\test_as_server.py", line 81, in check
    result = fun(*argv, **kwargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Core\Utilities\twisted_thread.py", line 151, in errback
    failure.raiseException()
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win32\tribler\Tribler\Test\Core\Modules\RestApi\test_channels_endpoints.py", line 79, in verify_channels
    self.assertEqual(channels_json['channels'][i]['name'], 'Test channel %d' % i)
AssertionError: u'Test channel 2' != 'Test channel 0'
-------------------- >> begin captured logging << --------------------
```

Apparently, we cannot make any assumptions on the order of incoming data. We should remove this check.

### PR DESCRIPTION
**Pull request by devos50**
This check can safely be removed since the check whether there are exactly 10 channels in the result JSON is enough.

Fixes #2333

### CODE REVIEW

**Comment by devos50** [comment]
@lfdversluis can you review?

**Comment by whirm** [comment]
Can't you just sort the channels when checking?

**Comment by devos50** [comment]
@whirm hmm yeah I can do that, will implement it.

**Comment by devos50** [comment]
```
ERROR
test_playdownload (Tribler.Test.test_libtorrent_download.TestLibtorrentDownload) ... Traceback (most recent call last):
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Main/tribler_main.py", line 151, in __init__
    session.start()
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Session.py", line 463, in start
    startup_deferred = self.lm.register(self, self.sesslock)
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 108, in register
    self.torrent_store = LevelDbStore(self.session.get_torrent_store_dir())
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/leveldbstore.py", line 84, in __init__
    self._db = self._leveldb(os.path.relpath(store_dir, os.getcwdu()))
LevelDBError: IO error: lock collected_torrents/LOCK: already held by process
```

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
@lfdversluis ready for review

**Comment by lfdversluis** [comment]
Looks good to me.

**Comment by devos50** [comment]
@whirm ready for your review

**Pull request merged**
