### PR TITLE
Fix xinithreads

### PR DESCRIPTION
**Pull request by whirm**

### CODE REVIEW

**Comment by whirm** [comment]
I'll run this a few times to make sure the bug is gone.

**Comment by whirm** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
meh, plyvel was removed, not an actual failure

**Comment by whirm** [comment]
retest this please

**Comment by lfdversluis** [comment]
1 test failed!

**Comment by synctext** [comment]
retest this please

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
2 runs successful now.

**Comment by lfdversluis** [comment]
retest this please

**Comment by whirm** [comment]
@lfdversluis no, plyvel install has been deleted by @brussee (I told him to do so, so it's my bad :D) and that test needs it.

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by lfdversluis** [comment]
no squash?

**Comment by whirm** [comment]
no, separate commits for separate concepts

**Pull request merged**
