### PR TITLE
Remove get_unicode_sys_argv() from hacks.py

### LINKED ISSUE #2827: get_unicode_sys_argv() of hacks.py is unused and should be removed
I think the function get_unicode_sys_argv() of hacks.py should be removed, as it is unused. I have already created a [commit on my forked repository](https://github.com/MaxVanDeursen/tribler/commit/cbc76bdcbc73331b69febb2117340dae72a0b125) for which I can create a PR.

### PR DESCRIPTION
**Pull request by MaxVanDeursen**
Fixes #2827

### CODE REVIEW

**Comment by egbertbouman** [comment]
ok to test

**Comment by devos50** [comment]
ok to test

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
@MaxVanDeursen please rebase this branch

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
@MaxVanDeursen are you finished with this?

**Comment by MaxVanDeursen** [comment]
@devos50 I sure am

**Pull request merged**
