### PR TITLE
Update development_on_linux.rst

### PR DESCRIPTION
**Pull request by cuileri**
With the help of #3770 as well as my own experience during installing Tribler on Ubuntu 18.04, instructions were updated.

### CODE REVIEW

**Comment by devos50** [comment]
ok to test

**Comment by devos50** [comment]
add to whitelist

**Comment by qstokkink** [comment]
I believe we can now also drop `python-apsw`, `python-keyring`, `python-keyrings.alt`, `python-m2crypto` and `python-pil`.

**Comment by devos50** [comment]
@qstokkink yes, they can be removed.

@cuileri please avoid creating branches on the "real" Tribler repository. Instead, you should fork the Tribler repository and make PRs to `Tribler/Tribler` with a source branch on your fork.

**Comment by cuileri** [comment]
I moved the changes to my fork accordingly.

**Pull request closed without merging**
