### PR TITLE
Add on_paste_event to handle pasting of magnet links

### PR DESCRIPTION
**Pull request by heldersepu**
A simple change to add magnet to the downloads with paste (`QKeySequence("Ctrl+v")`)
this speeds up the many click steps, ideally more options will be added in the future..

### CODE REVIEW

**Comment by drew2a** [comment]
Hi, @heldersepu!

Thank you for your improvement. I see a lot of errors in the checks for this PR. However, they are not related to the changes in this PR and are caused by something else.
I'll figure out the reasons for them, fix them, and then return to this PR.

**Comment by drew2a** [comment]
@heldersepu, could you please rebase your branch on `main`? The issues seem to be fixed.

**Comment by heldersepu** [comment]
@drew2a done

**Comment by drew2a** [comment]
Thank you, @heldersepu!

Two comments:
1. You merged the `main` branch into yours instead of rebasing your branch onto `main`. It's fine for now, but perhaps when the PR is ready, it would be nice to rebase it before merging (though it's not necessary).
[When do you use git rebase instead of git merge?](https://stackoverflow.com/questions/804115/when-do-you-use-git-rebase-instead-of-git-merge)
2. The test `test_clipboard` causes the GUI tests to fail. You should probably mock `QApplication` or some parts of it.

**Review by drew2a — CHANGES_REQUESTED** [review]
The test `test_clipboard` is causing the GUI tests to fail. It should be fixed.

There are two ways to address this, one proper but time-consuming, and the other quick but less desirable, which is to simply remove the test.

If you choose the proper method, here are a couple of options:
1. Keep the test as is but try to mock `QApplication` or some parts of it.
2. Move the test to `test_gui.py` and adapt it to the style used in that file.

To verify correctness, you can run the entire test suite for the GUI folder. Currently, it results in an error.

**Comment by heldersepu** [comment]
... but Merging is so much easier... github gives us a button they call [Sync fork]
on my branch is just one click an done, why will anyone still use rebase 

Looking into the failing tests, I noticed the `copy_to_clipboard` did not have any tests now I see why, I'm just going to remove that test, making sure copy/paste works is counter productive

**Comment by drew2a** [comment]
> why will anyone still use rebase

It gives you a cleaner commit history. If you spend a lot of time doing bug fixing and figuring out when and how an error was introduced, you start to appreciate the clarity of a well-maintained commit history :)

**Review by drew2a — APPROVED** [review]

**Comment by drew2a** [comment]
@heldersepu, thank you for your effort and cooperation.

**Comment by heldersepu** [comment]
It really is my pleasure @drew2a ...
I've been using Tribbler for a while and always found a few quirks that could be improved, but never put the time to read the code; I just ran into a bug with the http_port used for the api that I could not leave alone: https://github.com/Tribler/tribler/issues/8007 that one unfortunately I could not fix there seems to be much more discussion that we need to settle before a permanent code fix is applied

**Pull request merged**
