### PR TITLE
Check if port is either int or long

### LINKED ISSUE #1333: Remotetorrenthandler
ERROR   1426280548.55 RemoteTorrentHandler:615   failed to save data for download f907a77bdc515feb7e2701bf80d0094dbd1047cd.torrent: node port not int, but ```<type 'long'>```

### PR DESCRIPTION
**Pull request by LipuFei**
Closes #1333

### CODE REVIEW

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
@whirm ready

**Pull request merged**
