### PR TITLE
Fix for newer bitcoinlib versions

### LINKED ISSUE #4001: Tribler not starting with latest bitcoinlib version
When using bitcoinlib `0.4.1`:

```
ERROR   1541154665.35            tribler_window:83   (root)  Traceback (most recent call last):
  File "/home/quinten/Documents/tribler/TriblerGUI/core_manager.py", line 114, in on_received_state
    raise RuntimeError(state['last_exception'])
RuntimeError: Unhandled Error
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 434, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 322, in addCallback
    callbackKeywords=kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 447, in _continueFiring
    callable(*args, **kwargs)
  File "run_tribler.py", line 75, in start_tribler
    session.start()
  File "/home/quinten/Documents/tribler/Tribler/Core/Session.py", line 486, in start
    startup_deferred = self.lm.register(self, self.session_lock)
  File "/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 234, in register
    self.init()
  File "/home/quinten/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 418, in init
    btc_wallet = BitcoinWallet(wallet_path)
  File "/home/quinten/Documents/tribler/Tribler/Core/Modules/wallet/btc_wallet.py", line 28, in __init__
    from bitcoinlib.wallets import wallet_exists, HDWallet
  File "/home/quinten/.local/lib/python2.7/site-packages/bitcoinlib/__init__.py", line 21, in <module>
    import bitcoinlib.mnemonic
  File "/home/quinten/.local/lib/python2.7/site-packages/bitcoinlib/mnemonic.py", line 26, in <module>
    class Mnemonic:
  File "/home/quinten/.local/lib/python2.7/site-packages/bitcoinlib/mnemonic.py", line 35, in Mnemonic
    def __init__(self, language=DEFAULT_LANGUAGE):
exceptions.NameError: name 'DEFAULT_LANGUAGE' is not defined
```

After downgrading to `0.3.37` it works.

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #4001 .

### CODE REVIEW

**Comment by devos50** [comment]
Note to self: upgrade all `bitcoinlib` libraries installed to 0.4.1 (on Mac/Windows/Linux builders)

**Comment by qstokkink** [comment]
Will this not work on older version anymore?

**Comment by devos50** [comment]
Possibly, I have to check tomorrow.

**Comment by qstokkink** [comment]
Also, I think this should work in a frozen environment; but we should check.

**Comment by devos50** [comment]
Our override for the bitcoinlib main file is getting more and hackier. I think these changes now work but this is not a reliable approach if we want to further integrate bitcoin wallets in Tribler.

As discussed with @xoriole, I will work towards a PR on bitcoinlib itself to clean up the entangled `main.py` references. This should allow us to get rid of the code.

**Comment by devos50** [comment]
@qstokkink could you have a look at this? I can't request your review since it is your own PR.

**Comment by qstokkink** [comment]
Seems good, but does it work in frozen environments?

**Comment by devos50** [comment]
@qstokkink yes it does. Tested it on Windows and Mac.

**Comment by devos50** [comment]
I've also installed the `qrcode` library on the Windows machine; this dependency was absent and QR codes of Bitcoin wallets were not displayed :(

**Comment by qstokkink** [comment]
Alright 👍

**Pull request merged**
