### PR TITLE
WIP: Rewriting the DownloadConfigs

### PR DESCRIPTION
**Pull request by vandenheuvel**
This pull request restructures download configurations.

### CODE REVIEW

**Comment by MaxVanDeursen** [comment]
retest this please

**Comment by qstokkink** [comment]
@vandenheuvel Could you post the error you needed assistance with here?

**Comment by vandenheuvel** [comment]
Here the error is on [mac](https://jenkins.tribler.org/job/GH_Tribler_PR_tests_mac/4627/artifact/output/test_runners_output/4.err/*view*/), [win32](https://jenkins.tribler.org/job/GH_Tribler_PR_tests_win32/4496/artifact/output/test_runners_output/1.err/*view*/) and [linux](https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/4928/artifact/output/test_runners_output/00008.err/*view*/).

**Comment by vandenheuvel** [comment]
retest this please

**Pull request closed without merging**
