### PR TITLE
READY: Fix core not starting when running from binaries

### PR DESCRIPTION
**Pull request by egbertbouman**
Fixes https://github.com/Tribler/tribler/issues/5229.

I've only tested Windows 32/64 installers, as I don't have access to a Mac.

### CODE REVIEW

**Comment by ichorid** [comment]
Is it ready for review?

**Comment by egbertbouman** [comment]
@ichorid Let me quickly fix the videoplayer too, while I'm at it.

**Comment by egbertbouman** [comment]
@ichorid Oops! I was right the first time. The aiohttp_apispec fix should go into devel, the other one should go into release-7.5. Will fix tomorrow.

**Comment by egbertbouman** [comment]
@ichorid Should be OK now.

**Comment by devos50** [comment]
I guess the `aio_httpspec` bug fix should be included in the 7.5 release? Should cherry-pick this on the `release-7.5` branch after merge?

**Comment by ichorid** [comment]
> I guess the `aio_httpspec` bug fix should be included in the 7.5 release? Should cherry-pick this on the `release-7.5` branch after merge?

It should work the other way around: this change should be merged into `release-7.5` branch and then `release-7.5` branch should be merged into `devel`.

@egbertbouman , please rebase this PR to go into `release-7.5`. When RC2 is out we'll merge all the bugfixes from `release-7.5` into `devel`. The reason for this is to minimize the number of merge conflicts.

p.s.
Cherry-picking stuff is tolerable only for *really* important bugfixes that should go into *every* branch ASAP.

**Comment by ichorid** [comment]
To be clear: if this problem is affecting only release-7.5, it should go onto release-7.5. If it affects *only* devel, it should go into devel.

**Comment by egbertbouman** [comment]
@devos50 @ichorid The release branch does not use aiohttp_apispec, so this should go into devel.

**Comment by ichorid** [comment]
Is it fine that `aiohttp_apispect` is used in ipv8 and mentioned in our `requirements.txt`, `dependencies.py`, etc. on `release-7.5` branch? How Tribler is even able to start without it?

**Comment by egbertbouman** [comment]
Because of the IPv8 import, the `aiohttp_apispec` library is a dependency in both `release-7.5` and `devel`. No one is questioning that.

When you build an installer for 7.5 it does seems to include `aiohttp_apispec`, as it should. It's just not including the html/js files, which aren't needed in 7.5 anyway. We only started serving the Swagger UI after https://github.com/Tribler/tribler/pull/5222 got merged, and the `release-7.5` was created before that.

**Comment by ichorid** [comment]
@egbertbouman , thanks for the detailed explanation! Merging now.

**Pull request merged**
