### PR TITLE
Improved debug pane

### PR DESCRIPTION
**Pull request by devos50**
This PR extends the debug pane with more functionality and insights in the Tribler core process.

Features:
- Implemented a resource monitor that periodically polls CPU/memory usage and stores them. Settings for these resource monitor can be changed using the configuration file.
- Added endpoints to fetch information about threads/open sockets/open files/CPU history/memory history
- Added disk usage info to the debug pane

Screenshots:

debug_pane_1

debug_pane_2

debug_pane_3

debug_pane_4

debug_pane_5

debug_pane_6

### CODE REVIEW

**Comment by devos50** [comment]
retest this please

**Comment by qstokkink** [comment]
```
Traceback (most recent call last):
  File "/home/jenkins/workspace/GH_Tribler_PR_tests_GUI_linux/tribler/TriblerGUI/debug_window.py", line 274, in on_core_open_files
    core_item.setText(0, "Core (%d)" % len(data["open_files"]))
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by qstokkink** [comment]
The code itself looks good 👍

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
(network cable in Mac mini was not probably attached)

**Comment by devos50** [comment]
@qstokkink this PR is ready. Apparently, I can't get the Pylint issue fixed (whatever order I try) and the two remaining lines for the code coverage are hard to cover.

**Pull request merged**
