### PR TITLE
WIP: needs package python-psutil/python-meliae or it won't run

### PR DESCRIPTION
**Pull request by themusicgod1**

### CODE REVIEW

**Comment by devos50** [comment]
Also, it seems that we forgot to update these dependencies. We need a better way to keep track of all dependencies (like a script that automatically generates all dependencies we need).

**Comment by qstokkink** [comment]
@devos50 We can iterate all `.py` files in the source tree and run:

```python
import ast
node = ast.parse(file_contents)
for subnode in ast.walk(node):
    if isinstance(subnode, ast.Import):
        print "Found import", [alias.name for alias in subnode.names]
```

This will list all normally defined imports (so no `__import__()` or `imp.load_module()`).

**Comment by qstokkink** [comment]
Ok to test

**Comment by devos50** [comment]
This will be part of the next -> devel backport so I close this one in favor of the backport.

**Pull request closed without merging**
