### PR TITLE
No naked seeding after anonymous downloading

### PR DESCRIPTION
**Pull request by rjruigrok**
After an anonymous download, it will automatically change the torrent into an anonymous torrent.

### CODE REVIEW

**Comment by rjruigrok** [comment]
This PR also fixes a bug when circuit length is 1. This was not working, because the first_hop was not necessarily a valid exitnode.

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
Retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
Please also use a normal fully visible font for GUI text "Darknet mode: Hidden seeding, never seed naked in Bittorrent (can not be disabled)". plus add the text between brackets.
https://github.com/Tribler/tribler/blob/1f7ea57504cbb028a696059a08fad8f9f0b01624/Tribler/Main/vwxGUI/widgets.py#L2603

**Comment by rjruigrok** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
@rjruigrok @whirm strange outcome of this unit test failure. 
```
Test Result (1 failure / +1)
Tribler.Test.test_my_channel.TestMyChannel.test_add_torrents_playlists
```

**Comment by synctext** [comment]
retest this please

**Comment by LipuFei** [comment]
@rjruigrok Made another PR #1434 to fix the unit tests. Don't retest until we merge that one.

**Comment by LipuFei** [comment]
@rjruigrok Please do a rebase against the current devel. The unit tests should be fixed.

**Comment by rjruigrok** [comment]
retest this please

**Comment by rjruigrok** [comment]
@LipuFei All tests seem to hang somewhere in te beginning, do you have a clue why?

**Comment by rjruigrok** [comment]
@egbertbouman Should be ready for merge when test passes. I reverted this PR to the latest working commit that actually passed the tests, let's wait for it when test passed... :)

**Comment by rjruigrok** [comment]
Ah it actually passed! Just the isolated one hangs. :+1:

**Comment by whirm** [comment]
@rjruigrok it hangs on current devel on test_libtorrent_download.py too, I'm looking at it.

**Pull request closed without merging**
