### PR TITLE
Update IPv8 pointer

### PR DESCRIPTION
**Pull request by egbertbouman**
Fixes https://github.com/Tribler/tribler/issues/6070.

### CODE REVIEW

**Comment by ichorid** [comment]
Already updated :wink:

**Comment by ichorid** [comment]
Thanks for the fix, BTW :clap:

**Comment by egbertbouman** [comment]
@ichorid I see, the pointer update must have been needed for the GUI translation.

**Comment by ichorid** [comment]
> @ichorid I see, the pointer update must have been needed for the GUI translation.

Well, you never know in Tribler :wink: 

(Actually, I've just seen you fix the problem in ipv8, but to me it seemed you hesitated to update the pointer. So, I piggybacked it on top of my PR. If you don't like me doing this kind of thing, next time I will leave it to you.)

**Comment by egbertbouman** [comment]
I didn't hesitate, I was just waiting for someone to approve this PR.

If you look a the timestamp of this PR you'll see that it was opened (and marked "ready for review") way before you added the commit to your PR. So in this case, it wasn't particularly helpful.

**Comment by ichorid** [comment]
> I didn't hesitate, I was just waiting for someone to approve this PR.
> 
> If you look a the timestamp of this PR you'll see that it was opened (and marked "ready for review") way before you added the commit to your PR. So in this case, it wasn't particularly helpful.


:facepalm: 
You're right

**Pull request closed without merging**
