### PR TITLE
Remove Policies

### LINKED ISSUE #1405: set_max_desired_speed() in LibtorrentDownloadImpl
`set_max_desired_speed()` in `LibtorrentDownloadImpl` is never used. However, `RateManager` uses `LibtorrentDownloadImpl.get_max_desired_speed()` to set max speed, for example:
```
d.set_max_speed(dir, d.get_max_desired_speed(dir))
```
The `set_max_speed()` is defined in `DownloadConfig`.

@NielsZeilemaker Do you know if this is a bug or we are intended to do this?

### PR DESCRIPTION
**Pull request by LipuFei**
Closes #1405

### CODE REVIEW

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
@whirm @NielsZeilemaker Ready

**Comment by NielsZeilemaker** [comment]
@LipuFei nice one

**Pull request merged**
