### PR TITLE
Reference to sql file, fixes build issue on Ubuntu introduced in Trib…

### PR DESCRIPTION
**Pull request by NoNameForMee**
…ler/tribler@bc7b5771748f8d7ebc4ae85742675838e4d839f8

This should solve the build issue in: https://jenkins.tribler.org/job/Build-Tribler_Ubuntu-64_devel/649/consoleFull

### CODE REVIEW

**Comment by lfdversluis** [comment]
Hmmm this would go wrong if there are multiple dbs though I guess?

**Comment by synctext** [comment]
add to test

**Comment by devos50** [comment]
ok to test

**Comment by devos50** [comment]
@NoNameForMee thank you for your contribution. I created a separate PR to fix the other Tribler builders too (they also broke after the move of the Category package). I've cherry-picked your commit in #2552 and I will close this PR.

**Pull request closed without merging**
