### PR TITLE
Remove the byte-order-mark

### PR DESCRIPTION
**Pull request by da2x**
Fixes issue #3820.

### CODE REVIEW

**Comment by xoriole** [comment]
ok to test

**Comment by da2x** [comment]
So what exactly is failing in that test? There is no clear pass or fail criteria in the output.

I don’t really believe that removing the BOM from the license file should be causing any regressions.

**Comment by xoriole** [comment]
It seems Mac GUI test is failing
```
======================================================================
FAIL: test_add_download_url (Tribler.Test.GUI.test_gui.TriblerGUITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tribler/Documents/workspace2/workspace/GH_Tribler_PR_Tests/PR_GUI_mac/tribler/Tribler/Test/GUI/test_gui.py", line 464, in test_add_download_url
    self.assertEqual(window.downloads_list.topLevelItemCount(), old_count + 1)
AssertionError: 35 != 36
```
@da2x It is not related to your PR

**Comment by xoriole** [comment]
retest this please

**Comment by devos50** [comment]
Building a custom MacOS bundle to test whether the issue is resolved, see https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build-OSX/244

**Comment by devos50** [comment]
This PR successfully fixes it! @da2x thank you for your contribution 👍 

Schermafbeelding 2019-03-12 om 09 10 36

**Pull request merged**
