### PR TITLE
Tunnel refactoring

### PR DESCRIPTION
**Pull request by egbertbouman**
Fixes https://github.com/Tribler/tribler/issues/2765, https://github.com/Tribler/tribler/issues/2824.

### CODE REVIEW

**Comment by vandenheuvel** [comment]
retest this please

**Comment by devos50** [comment]
This PR should go to devel ;)

**Comment by qstokkink** [comment]
Why is the master member being changed? Are these changes no longer compatible with the old TunnelCommunity?

**Comment by egbertbouman** [comment]
@qstokkink Don't worry, everthing is still compatible. I changed the master member because we had the private key of our master member in the comments :astonished:

**Comment by qstokkink** [comment]
@egbertbouman ah. Yes, I would agreee that is a very valid reason to change it 😛 .

**Comment by devos50** [comment]
@egbertbouman can you cover the missing line with a unit test and fix the pylint errors? :)

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
@egbertbouman I think we should defer the changing of the community ID and do this just before we release Tribler 7 so I can change all the tunnel helpers at once.

**Comment by synctext** [comment]
would prefer we dont do a single big bang change of our PetaByte helper servers. 1 or more now. Rest later.

**Comment by devos50** [comment]
Ok then, I will change the tunnel helper restart script to account for our new community ID.

**Pull request merged**
