### PR TITLE
Fix wallet transfer endpoint, add error message for insufficient funds

### LINKED ISSUE #4142: An empty error when transfering BTC from Tribler wallet
##### Tribler version/branch+revision: #####
devel

##### Operating system and version: #####
Ubuntu 16.04

##### Steps to reproduce the behavior: #####
1. Transfer BTC (or TBTC) to Tribler wallet
2. Transfer BTC from Tribler wallet using the API endpoint:
```curl -X POST http://localhost:8085/wallets/TBTC/transfer --data "amount=1000&destination=mgsPyc1LHyAqhwmYnxgMv3jwdpGFZCLovQ"```

##### Expected behavior: #####
A transaction ID should be returned.

##### Actual behavior: #####
An error response is returned with the following content: ```{"error": "", "txid": ""}```

### PR DESCRIPTION
**Pull request by MattSkala**
Fixes #4142

### CODE REVIEW

**Comment by devos50** [comment]
ok to test

**Comment by devos50** [comment]
Looks good! One request: could you fix the flake8 import errors in a separate commit? Even though these errors are not introduced by your changes, we have adopted a policy that every PR needs to pass these flake8 tests to improve the code quality. Thanks 👍

**Comment by devos50** [comment]
@MattSkala I didn't mention it but ignoring the pylint error was fine. In fact, I prefer the old, more explicit, style of code (with the else statement). Could you revert that part? The import order seems fine now 👍

**Comment by MattSkala** [comment]
Ok, reverted. Should be ready to merge.

**Pull request merged**
