### PR TITLE
Fixes for post-renaming issues

### PR DESCRIPTION
**Pull request by xoriole**
- Fixed tribler.sh script. Supports running tribler from any directory.
- Fixed GUI tester
- Fixed documentation builder

### CODE REVIEW

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
Two failing tests in linux:
Screenshot from 2020-01-03 15-11-25
- [TestMetadataDownloadEndpoint.test_add_metadata_download](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_linux_py3_tester/677/testReport/junit/test_downloads_endpoint/TestMetadataDownloadEndpoint/test_add_metadata_download/)
- [TestMetadataDownloadEndpoint.test_add_metadata_download_already_added](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_linux_py3_tester/677/testReport/junit/test_downloads_endpoint/TestMetadataDownloadEndpoint/test_add_metadata_download_already_added/)
We should fix this separately.

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Pull request merged**
