### PR TITLE
Remove Main.metadata-injector and Core.Utilities.misc_utils

### PR DESCRIPTION
**Pull request by vandenheuvel**
Fixes https://github.com/Tribler/tribler/issues/2825.
I will also move the `twisted_thread` module to the test suite.

### CODE REVIEW

**Comment by egbertbouman** [comment]
ok to test

**Comment by vandenheuvel** [comment]
retest this please

**Comment by devos50** [comment]
There was a memory issue with Jenkins, however, I need physical access to some of the builders. I will reset them tomorrow.

**Comment by devos50** [comment]
retest this please

**Comment by vandenheuvel** [comment]
@devos50 Windows64 GUI tests are failing on this branch. Can you help me find why? [Jenkins logs](https://jenkins.tribler.org/job/GH_Tribler_PR_tests_GUI_win64/343/console) are quite clear, but I can't figure out how GUI tests are ran. Where is, for example, `FakeTriblerAPI`?

**Comment by vandenheuvel** [comment]
retest this please

**Comment by devos50** [comment]
@vandenheuvel we had some problems with the builders. The Fake Tribler API is used during the GUI tests and is available in my Github account (https://github.com/devos50/fake-tribler-api). It is basically a copy of the Tribler api but with fake data so we have more control over what we are showing during the GUI tests.

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
It seems to work now. Are you finished with this PR?

**Comment by vandenheuvel** [comment]
@devos50 I'm not, I'll put it on READY when I am.

**Pull request merged**
