### PR TITLE
DO NOT MERGE - Testing the tests

### PR DESCRIPTION
**Pull request by devos50**
Just some testing to investigate the hanging test_download tests

### CODE REVIEW

**Comment by devos50** [comment]
I suspect that the deferred returned by `network_create_engine_wrapper` is not fired somehow:

```
DEBUG   1461001488.04   SessionConfig:123   Get random port 48615 for [dispersy~dispersy_port]
DEBUG   1461001488.04   SessionConfig:123   Get random port 10103 for [mainline_dht~mainline_dht_port]
DEBUG   1461001488.04   SessionConfig:123   Get random port 37567 for [video~port]
DEBUG   1461001488.04   SessionConfig:123   Get random port 9018 for [libtorrent~anon_listen_port]
DEBUG   1461001488.04   SessionConfig:123   Get random port 24782 for [tunnel_community~socks5_listen_ports~0]
DEBUG   1461001488.04   SessionConfig:123   Get random port 26652 for [tunnel_community~socks5_listen_ports~1]
DEBUG   1461001488.04   SessionConfig:123   Get random port 38398 for [tunnel_community~socks5_listen_ports~2]
DEBUG   1461001488.04   SessionConfig:123   Get random port 47253 for [tunnel_community~socks5_listen_ports~3]
DEBUG   1461001488.04   SessionConfig:123   Get random port 46699 for [tunnel_community~socks5_listen_ports~4]
INFO    1461001488.04   sqlitecachedb:135   begin page_size upgrade...
INFO    1461001488.05   sqlitecachedb:139   ...end page_size upgrade
INFO    1461001488.05   sqlitecachedb:159   Initializing new database...
INFO    1461001488.07   sqlitecachedb:180   Reading database version...
INFO    1461001488.07   sqlitecachedb:184   Current database version is 28
INFO    1461001488.07   sqlitecachedb:202   Beginning the first transaction...
DEBUG   1461001488.07     mainlineDHT:29    DHT initialization True
DEBUG   1461001488.11     mainlineDHT:40    DHT running
INFO    1461001488.12   LibtorrentMgr:163   could not load libtorrent state, got exception: IOError(2, 'No such file or directory'). starting from scratch
DEBUG   1461001488.12   LibtorrentMgr:181   Started libtorrent session for 0 hops on port 18887
INFO    1461001488.13   LibtorrentMgr:307   uPnP port added : 10103 udp
DEBUG   1461001488.13   LibtorrentMgr:539   starting download: filename: /home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Test/data/ubuntu-15.04-desktop-amd64.iso.torrent, dest dir: None, torrent def: None
INFO    1461001488.13   LibtorrentMgr:588   start_download: Starting in VOD mode
INFO    1461001488.13  LaunchManyCore:456   fc8a15a2faf2734dbb1dc5f7afdc5c9beaeb1f59.state not found
DEBUG   1461001488.13 LibtorrentDownloadImpl:957   LibtorrentDownloadImpl: set_filepieceranges: []
DEBUG   1461001488.13 LibtorrentDownloadImpl:186   setup: initialdlstatus fc8a15a2faf2734dbb1dc5f7afdc5c9beaeb1f59 None
DEBUG   1461001488.13 LibtorrentDownloadImpl:214   Starting in can_create_engine_wrapper
DEBUG   1461001488.13 LibtorrentDownloadImpl:217   Starting in do_check
DEBUG   1461001488.13 LibtorrentDownloadImpl:220   NOT self.cew_scheduled
DEBUG   1461001488.13 LibtorrentDownloadImpl:189   At start of schedule_create_engine
```

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by lfdversluis** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by synctext** [comment]
retest this please

**Comment by lfdversluis** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
Fixed by #2128

**Pull request closed without merging**
