### PR TITLE
v8 headless

### LINKED ISSUE #8176: v8 headless
Something like this:

```
diff --git a/src/run_tribler.py b/src/run_tribler.py
index e485332..a020043 100644
--- a/src/run_tribler.py
+++ b/src/run_tribler.py
@@ -11,7 +11,6 @@ import typing
 import webbrowser
 from pathlib import Path
 
-import pystray
 from aiohttp import ClientSession
 from PIL import Image
 
@@ -102,12 +101,17 @@ async def main() -> None:
             torrent_uri = Path(torrent_uri).read_text()
     server_url = await session.find_api_server()
 
+    headless = parsed_args.get('headless')
+    if ! headless:
+        import pystray
+    
     if server_url:
         logger.info("Core already running at %s", server_url)
         if torrent_uri:
             logger.info("Starting torrent using existing core")
             await start_download(config, server_url, torrent_uri)
-        webbrowser.open_new_tab(server_url + f"?key={config.get('api/key')}")
+        if ! headless:
+            webbrowser.open_new_tab(server_url + f"?key={config.get('api/key')}")
         logger.info("Shutting down")
         return
 
@@ -117,19 +121,21 @@ async def main() -> None:
     if server_url and torrent_uri:
         await start_download(config, server_url, torrent_uri)
 
-    image_path = tribler.get_webui_root() / "public" / "tribler.png"
-    image = Image.open(image_path.resolve())
-    api_port = session.rest_manager.get_api_port()
-    url = f"http://{config.get('api/http_host')}:{api_port}/ui/#/downloads/all?key={config.get('api/key')}"
-    menu = (pystray.MenuItem('Open', lambda: webbrowser.open_new_tab(url)),
-            pystray.MenuItem('Quit', lambda: session.shutdown_event.set()))
-    icon = pystray.Icon("Tribler", icon=image, title="Tribler", menu=menu)
-    webbrowser.open_new_tab(url)
-    threading.Thread(target=icon.run).start()
+    if ! headless:
+        image_path = tribler.get_webui_root() / "public" / "tribler.png"
+        image = Image.open(image_path.resolve())
+        api_port = session.rest_manager.get_api_port()
+        url = f"http://{config.get('api/http_host')}:{api_port}/ui/#/downloads/all?key={config.get('api/key')}"
+        menu = (pystray.MenuItem('Open', lambda: webbrowser.open_new_tab(url)),
+                pystray.MenuItem('Quit', lambda: session.shutdown_event.set()))
+        icon = pystray.Icon("Tribler", icon=image, title="Tribler", menu=menu)
+        webbrowser.open_new_tab(url)
+        threading.Thread(target=icon.run).start()
 
     await session.shutdown_event.wait()
     await session.shutdown()
-    icon.stop()
+    if ! headless:
+        icon.stop()
     logger.info("Tribler shutdown completed")
```

### PR DESCRIPTION
**Pull request by Dmole**
Fixes #8176

This PR:

 - Fixes / re-adds the ability to operate in server/headless mode

### CODE REVIEW

**Comment by qstokkink** [comment]
validate

**Review by egbertbouman — COMMENTED** [review]
Thanks for the PR. It looks good to me, but maybe you could try and fix the ruff issues? If you move some blocks of code out of main and into separate functions, it will probably be OK (e.g. the config creation and torrent URI loading).

**Comment by egbertbouman** [comment]
validate

**Review by egbertbouman — APPROVED** [review]
Thanks!

**Pull request merged**
