### PR TITLE
Update IPv8 pointer

### PR DESCRIPTION
**Pull request by egbertbouman**
Fixes https://github.com/Tribler/tribler/issues/5850.

### CODE REVIEW

**Review by qstokkink — APPROVED** [review]

**Comment by qstokkink** [comment]
[Approval conditional: depending on whether or not we're releasing `7.6.2` or going straight for `7.7.0`]

**Review by qstokkink — CHANGES_REQUESTED** [review]
Apparently we're not doing `7.6.2`, please rebase onto `devel`.

**Comment by egbertbouman** [comment]
Apparently, we also need https://github.com/Tribler/tribler/pull/5819 in devel in order to update the pointer.

**Comment by qstokkink** [comment]
> 
> 
> Apparently, we also need #5819 in devel in order to update the pointer.

Who's in charge of backporting in the dev team nowadays?

**Comment by qstokkink** [comment]
Judging from the commit history, this should be resolved now.

**Review by qstokkink — APPROVED** [review]

**Comment by egbertbouman** [comment]
retest this please

**Pull request merged**
