### PR TITLE
Reordered sections in issue template

### PR DESCRIPTION
**Pull request by vi**
Move "Steps to reproduce the behavior" above "Expected/Actual behaviour", as the latter follows from the former.

### CODE REVIEW

**Comment by qstokkink** [comment]
ok to test

**Comment by devos50** [comment]
I just upgraded Jenkins and I had to restart the machine and forgot to reboot sonarqube. It should work now again.

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
@vi thank you for your contribution!

**Pull request merged**
