### PR TITLE
Merge check for 7.3.0

### PR DESCRIPTION
**Pull request by ichorid**

### CODE REVIEW

**Comment by xoriole** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by ichorid** [comment]
@xoriole, as all the tests pass, I consider it good enough for merging into `devel`. I'll squash the merge-specific commits before the merge, which will be done manually.

Remind that this is not the pull request to solve all of the Python3 problems. We'll fix them naturally along the way while using `devel` version of Tribler.

**Comment by xoriole** [comment]
Seems windows is offline so tests are pending there. We can merge it today if everything passes.

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
GUI tests are failing with the following stacktrace:
```python
Traceback (most recent call last):
  File "/home/tribler/tudelft/tribler/TriblerGUI/event_request_manager.py", line 102, in on_read_data
    json_dict = json.loads(event)
  File "/home/tribler/tudelft/tribler/Tribler/Core/Utilities/json_util.py", line 128, in loads
    return json.loads(s, *args, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ichorid** [comment]
Merged the branch manually into `devel`

**Pull request closed without merging**
