### PR TITLE
Fixed wrong exception for invalid received encryption

### LINKED ISSUE #2663: Error when decrypting circuit payload
We received this report in our crash reporter backend:

```
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 85, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/usr/share/tribler/TriblerGUI/core_manager.py", line 65, in start_tribler_core
reactor.run()
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
self.mainLoop()
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
self.runUntilCurrent()
--- <exception caught here> ---
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
f(*a, **kw)
File "/usr/share/tribler/Tribler/community/tunnel/tunnel_community.py", line 1158, in on_data
encrypted = self.crypto_in(circuit_id, encrypted, is_data=True)
File "/usr/share/tribler/Tribler/community/tunnel/tunnel_community.py", line 1299, in crypto_in
hop.session_keys[ORIGINATOR_SALT])
File "/usr/share/tribler/Tribler/community/tunnel/crypto/tunnelcrypto.py", line 76, in decrypt_str
salt_explicit, gcm_tag = struct.unpack_from('!q16s', content)
struct.error: unpack_from requires a buffer of at least 24 bytes
```

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #2663, contains:
 - Correction of exception thrown by `decrypt_str()`
 - Unit test for this case

### CODE REVIEW

**Comment by qstokkink** [comment]
@devos50 ready for review

**Comment by devos50** [comment]
Hmm the mac GUI test is failing, probably due to one of my changes recently...

**Comment by qstokkink** [comment]
@devos50 yeah, the agent went offline: this PR does absolutely nothing with the GUI though.

**Comment by devos50** [comment]
@qstokkink thanks for the PR! Yes, I restarted the Mac slave so that's probably the issue.

**Pull request merged**
