### PR TITLE
WIP: getChannel with no name option

### LINKED ISSUE #2517: Get MyChannel overview TypeError
Should check if my_channel is not None before accessing my_channel[1] and my_channel[2]:

```
8-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: ERROR:[Failure instance: Traceback: <type 'exceptions.TypeError'>: 'NoneType' object is not subscriptable
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/protocols/basic.py:571:dataReceived
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/http.py:1720:lineReceived
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/http.py:1799:allContentReceived
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/http.py:832:requestReceived
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: --- <exception caught here> ---
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/server.py:183:process
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/server.py:234:render
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/resource.py:250:render
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: /data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Modules/restapi/channels/my_channel_endpoint.py:49:render_GET
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: ]
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: Traceback (most recent call last):
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/server.py", line 183, in process
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:     self.render(resrc)
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/server.py", line 234, in render
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:     body = resrc.render(self)
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/twisted/web/resource.py", line 250, in render
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:     return m(request)
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Core/Modules/restapi/channels/my_channel_endpoint.py", line 49, in render_GET
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd:     return json.dumps({'mychannel': {'identifier': my_channel[1].encode('hex'), 'name': my_channel[2],
08-14 00:06:49.210 2376-2417/org.tribler.android:service_Triblerd I/Triblerd: TypeError: 'NoneType' object is not subscriptable
```

### PR DESCRIPTION
**Pull request by brussee**
Fixes #2517

### CODE REVIEW

**Comment by brussee** [comment]
@whirm Ready.

**Comment by brussee** [comment]
retest this please

**Comment by brussee** [comment]
retest this please

**Comment by synctext** [comment]
good catch that this triggers a bug! Browsing your code.. From a code simplicity I think we should simply drop NULL channelnames. No valid use-case for them.
So just declare them invalid from now on and drop at creation plus search results. Agree @whirm?

**Comment by lfdversluis** [comment]
I know you have bigger issues now, but could you create (an issue for) a test that covers this? So it will never happen again :+1:

**Comment by brussee** [comment]
@synctext "No valid use-case for them." Right now the behavior is like hidden files on your file system.
@lfdversluis #2519

**Comment by devos50** [comment]
@whirm what do you think about this? I agree with this solution.

**Comment by whirm** [comment]
What about simply updating the sql query so a null name becomes an empty string?

**Comment by whirm** [comment]
@devos50 also agrees. It's way cleaner and we don't permanently polute the API to deal with a fixed bug.

**Comment by devos50** [comment]
Addressed in https://github.com/Tribler/tribler/commit/ed6f7441b0929756cc0267f842af4ed9f73ee95c

**Pull request closed without merging**
