### PR TITLE
Refactored tunnelcommunity crypto

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
Now uses an handshake similar to ntor + AES_GCM to encrypt packets.
Hidden services are broken.

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
Btw, this pull request requires a change/fix in libnacl https://github.com/saltstack/libnacl/pull/39 to work

**Comment by synctext** [comment]
please retest this

**Comment by NielsZeilemaker** [comment]
This branch needs a new dispersy pointer to work

**Comment by whirm** [comment]
@NielsZeilemaker are you going to update the dispersy ref?

**Comment by NielsZeilemaker** [comment]
@whirm current dispersy devel is broken. I'll fix this branch in a while, but it still needs a lot of work as hidden services are completely broken.

**Comment by whirm** [comment]
Ah, i see, thanks!

**Pull request closed without merging**
