### PR TITLE
Removed duplicate IPv8 test code

### LINKED ISSUE #3604: Remove duplicate code for testing
The current unit test framework has duplicate code from the IPv8 test suite. This was a necessity as the test classes could not be imported before.

Now that the test classes can be imported from IPv8, the duplicate code should be removed from the Tribler test suite.

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #3604

### CODE REVIEW

**Comment by qstokkink** [comment]
Hmm.. there is something fishy going on with the Windows machine and temporary files:

```
======================================================================
ERROR: test_torrent_store_delete (Tribler.Test.Core.test_session.TestSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Test\test_as_server.py", line 58, in check
    result = fun(*argv, **kwargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Test\Core\test_session.py", line 36, in test_torrent_store_delete
    session.lm.torrent_store = LevelDbStore(session.config.get_torrent_store_dir())
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Core\leveldbstore.py", line 71, in __init__
    rmtree(self._store_dir)
  File "c:\python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "c:\python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'%APPDATA%\\.Tribler\\collected_torrents\\000005.ldb'
-------------------- >> begin captured logging << --------------------
```

I also noticed this when running some recent IPv8 tests.

**Comment by devos50** [comment]
@qstokkink maybe some Tribler instance is running on the Windows machine? Also, this test seems to access the `.Tribler` directory in the APPDATA on Windows which is bad (unit tests should never write to this).

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Pull request merged**
