### PR TITLE
READY: Use WAL journal mode for sqlite connections

### PR DESCRIPTION
**Pull request by ichorid**
Well, this _should_ help with DB performance...

### CODE REVIEW

**Comment by devos50** [comment]
Can you do a basic benchmark to verify that the performance has indeed increased?

**Comment by ichorid** [comment]
Yes, I've tested it. When processing channels, patched Tribler is 20% faster. Also, it is important to note that WAL is most useful by enabling reads concurrent with writes. So, it is good for e.g. improving the responsiveness of the GUI, especially on slower media.

Let's merge it and see how it fares on our PCs, shall we?

**Comment by kozlovsky** [comment]
Note that the SQLite documentation [says](https://www.sqlite.org/wal.html):

> The default strategy is to allow successive write transactions to grow the WAL until the WAL becomes about 1000 pages in size, then to run a checkpoint operation for each subsequent COMMIT until the WAL is reset to be smaller than 1000 pages. By default, the checkpoint will be run automatically by the same thread that does the COMMIT that pushes the WAL over its size limit. **This has the effect of causing most COMMIT operations to be very fast but an occasional COMMIT (those that trigger a checkpoint) to be much slower**. If that effect is undesirable, then the application can disable automatic checkpointing and run the periodic checkpoints in a separate thread, or separate process.

So, while in general WAL journaling mode should be faster than DELETE journaling mode, sometimes COMMIT might be very slow. If SQLite updates are performed directly from the event loop, it sometimes may lead to long pauses with the event loop processing.

I'm for using WAL mode, but ideally, it should be combined with performing all transactions which modify the database from a separate thread to execute them outside of the event loop. Or, at least, the should be a separate thread for periodic checkpointing.

**Review by devos50 — APPROVED** [review]

**Comment by ichorid** [comment]
@kozlovsky , good point! This PR is very far from a perfect solution, but at least it is a step in the right direction. Of course, we'll still have to implement #4320 to solve the problem for good.

**Pull request merged**
