### PR TITLE
READY: Ported Gumby's modular Community loading

### LINKED ISSUE #5593: Modularize IPv8 community loading
As the Tribler repository now features an `experiment/` folder, we are seeing the same staging procedures being implemented as already available in Gumby. One of these features is the staging of IPv8 communities. In order for both repositories to benefit, I propose moving this from Gumby into the Tribler experiment infrastructure.

Loading communities in the `Session` is currently one big line of `if .. else` statements, see https://github.com/Tribler/tribler/blob/devel/src/tribler-core/tribler_core/session.py#L146
Instead, in Gumby, this is completely modularized, see https://github.com/Tribler/gumby/blob/devel/gumby/modules/gumby_session.py

This modularization of loading communities improves the Tribler code in four ways:

 - It shortens the `Session` code (making it more of a manager and less of a god class).
 - Allows for isolation and staging of community loading.
 - Reduces the complexity of staging components.
 - Allows for declarative programming.

There is also a downside: a big `if .. else` construction is slightly faster than a modular loading system. But, considering the direction we are heading, that seems like an acceptable sacrifice.

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #5593

This is a straight port of Gumby's modular Community loading.

Community loading is now declarative, which inflates the codebase slightly. Session is now less of a god-class.

### CODE REVIEW

**Comment by devos50** [comment]
Nice! Will you also remove this code from Gumby then?

One consequence of removing the community loading code from Gumby is that we now have a hard requirement on Tribler for any experiment where we are using IPv8 and modular community loading. Specifically, AnyDex and Bami currently bypass the requirement for Tribler by making their own launcher. We would then require Tribler to run experiments since AnyDex and Bami are using modular community loading.

**Comment by qstokkink** [comment]
> Specifically, AnyDex and Bami currently bypass the requirement for Tribler by making their own launcher.

Ah, as far as I knew the `ipv8_provider` was always a `GumbySession` (which uses Tribler anyway). Could you link me to one of those?

**Comment by devos50** [comment]
@qstokkink see [here](https://github.com/Tribler/gumby/blob/devel/gumby/modules/anydex_module.py#L89)

**Comment by qstokkink** [comment]
@devos50 ah, sneaky 😄 In that case it makes sense to move this modular loading into a common base repo.. which I fear will be IPv8.

**Comment by devos50** [comment]
@qstokkink that would be nice, but if you think it is better to move it to Tribler, please go ahead. Having to clone/copy Tribler is a small sacrifice for preventing code duplication across many experiments 👍

**Comment by qstokkink** [comment]
@devos50 no, let's do this to our best ability immediately. You have presented a clear case for moving the launcher/loader base-classes into IPv8.

**Comment by qstokkink** [comment]
This PR will be "on hold" until these base classes are available in IPv8.

**Comment by qstokkink** [comment]
No longer "on hold", base classes are available in IPv8.

**Comment by qstokkink** [comment]
@devos50 I think pytest's timeout mechanism is broken.

**Comment by devos50** [comment]
That's weird. I would expect this to be stable, but it seems that again, we cannot trust external libraries...

**Comment by qstokkink** [comment]
retest this please

**Comment by devos50** [comment]
For now, I've added a hard timeout of three minutes to the tests. Still, I would have expected `pytest-timeout` to do its job.

**Comment by qstokkink** [comment]
👍 seems reasonable

**Comment by devos50** [comment]
@qstokkink any idea why the GUI test would fail with this PR?

**Comment by qstokkink** [comment]
@devos50 interesting.. they didn't fail before. Random timeouts?

**Comment by devos50** [comment]
@qstokkink  When running your branch on my computer, the core does not start with the following error:

```
[PID:44252] 2020-10-02 13:34:50,809 - INFO - IPv8CommunityLoader(181) - Finished loading communities!
[PID:44252] 2020-10-02 13:34:50,809 - ERROR <session:259> Session.unhandled_error_observer(): Unhandled exception occurred! 'NoneType' object has no attribute 'wait_for_socks_servers'
--LONG TEXT--
Traceback (most recent call last):
  File "/Users/martijndevos/Documents/tribler/src/run_tribler.py", line 81, in start_tribler
    await session.start()
  File "/Users/martijndevos/Documents/tribler/src/tribler-core/tribler_core/session.py", line 348, in start
    await self.tunnel_community.wait_for_socks_servers()
AttributeError: 'NoneType' object has no attribute 'wait_for_socks_servers'
```

**Comment by qstokkink** [comment]
Oops I might have screwed up the rebase, one moment.

**Comment by qstokkink** [comment]
Ah yes, pleasing the linters killed the PR 😄

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
🙏 the tunnel tests and metadata tests aligned and both passed this run.

**Review by devos50 — APPROVED** [review]

**Pull request merged**
