### PR TITLE
WIP: Remove locks

### PR DESCRIPTION
**Pull request by vandenheuvel**
Solves #1410.

### CODE REVIEW

**Comment by synctext** [comment]
Big change! This addresses the 'crazy chain of callbacks'?

**Comment by devos50** [comment]
@vandenheuvel first of all, thank you for making contributions. While it may be tempting to remove the (at first sight, useless) locks from the session/downloads, they actually need to be there if I remember correctly. I just had some discussion about it with others but we couldn't reach a consent. I suspect that the main reason is that we still call some methods from the thread pool. Please correct me if I'm wrong.

Also, before you decide to refactor some critical code or remove some functionalities (like the locks), please discuss it with us first so we can give our opinion. This might save you some time in the end.

**Comment by vandenheuvel** [comment]
@devos50 thanks for your response. Don't worry; this cost me very little time.

Could you point me to code managing the thread pool?

**Comment by vandenheuvel** [comment]
@qstokkink do you know which code @devos50 is referencing?

**Comment by qstokkink** [comment]
@vandenheuvel that is sadly not my area of expertise within Tribler (also I believe that part of the code is +- 10 years old)

**Comment by devos50** [comment]
@vandenheuvel https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py#L1053

**Comment by qstokkink** [comment]
Most of the changes in this PR are outdated and will naturally be fixed as we keep refactoring each component in Tribler. As such, I will close this PR.

**Pull request closed without merging**
