### PR TITLE
Showing individual overlay peers in the debug panel

### PR DESCRIPTION
**Pull request by devos50**
In this PR, I add a small QoL feature where I show the individual peers in an overlay in the debug panel. This is a feature that I heavily used in older Tribler versions for debugging community logic. For now, I mostly got the data on individual peers by making a `curl` request to the Tribler API, but now we can access this information directly from the GUI. When the overlays refresh, the peers in the panel below are also automatically updated.

For this to work, I had to slightly modify the rendering logic of the communities tree widget so the selection is not reset every time the overlays refresh.

I also extended the GUI tests to make a screenshot of the panel with peers. However, this panel is currently unfilled since we do not change the IPv8 overlay response in 'core test mode'.

Schermafbeelding 2021-06-30 om 12 43 15

### CODE REVIEW

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Review by ichorid — APPROVED** [review]

**Comment by devos50** [comment]
```
self = <test_eva_protocol.TestEVA testMethod=test_duplex>

    async def test_duplex(self):
        count = 100
        block_size = 10
    
        self.overlay(0).eva_protocol.block_size = block_size
        self.overlay(1).eva_protocol.block_size = block_size
    
        data0 = os.urandom(1), os.urandom(block_size * count), random.randrange(0, 256)
        data1 = os.urandom(1), os.urandom(block_size * count), random.randrange(0, 256)
    
        self.overlay(0).eva_send_binary(self.peer(1), *data0)
        self.overlay(1).eva_send_binary(self.peer(0), *data1)
    
        await drain_loop(asyncio.get_event_loop())
    
>       assert self.overlay(0).most_recent_received_data == data1
E       AssertionError: assert None == (b'N', b'\nN\...xcbw\xa8', 33)
E         +None
```

Encountered a stack trace during the tests on Mac. Is there already an issue for this?

**Comment by devos50** [comment]
retest this please

**Comment by ichorid** [comment]
> 
> Encountered a stack trace during the tests on Mac. Is there already an issue for this?

IDK. Created an issue just in case :shrug:

**Review by ichorid — APPROVED** [review]

**Pull request merged**
