### PR TITLE
Added two flags to twistd plugin

### PR DESCRIPTION
**Pull request by devos50**
Basically, these new flags allow the `twistd` plugin to act as channelcast and search supporter so these scripts can be removed now I guess.

### CODE REVIEW

**Comment by devos50** [comment]
```
  File "C:\Python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Test\test_as_server.py", line 59, in check
    result = fun(*argv, **kwargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Core\Utilities\twisted_thread.py", line 157, in g
    d = func(*args, **kargs)
  File "C:\workspace\jenkins\workspace\GH_Tribler_PR_tests_win64\tribler\Tribler\Test\Core\Modules\RestApi\test_events_endpoint.py", line 87, in test_search_results
    self.socket_open_deferred.addCallback(send_notifications)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 317, in addCallback
    callbackKeywords=kw)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 306, in addCallbacks
    self._runCallbacks()
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 564, in _runCallbacks
    isinstance(current.result, failure.Failure)]
"Deferred instance has no attribute 'result'\n
```

Never seen this before, let's see whether it always triggers on win64

**Comment by devos50** [comment]
retest this please

**Comment by lfdversluis** [comment]
I guess not

**Comment by devos50** [comment]
retest this please

**Pull request merged**
