### PR TITLE
Fix watchdog and tests

### PR DESCRIPTION
**Pull request by whirm**

### CODE REVIEW

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by devos50** [comment]
@whirm I'm investigating the issue, it seems to get stuck on the invocation of the `join` method in WatchDog.

**Comment by whirm** [comment]
@devos50 https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/381/artifact/output/test_runners_output/00001.err/*view*/

**Comment by devos50** [comment]
@whirm the `self.should_stop` attribute is not correctly set to `True`, preventing the while-loop in the `run` method of the WatchDog from stopping. Maybe we are calling the `join` method from the wrong thread?

**Comment by whirm** [comment]
If the should_stop wasn't properly set, how come it stops looping?

The join() is called from the TearDown() method on test_as_server, and it can be called from any thread even several times.

**Comment by devos50** [comment]
@whirm that's weird, I added a print statement in the while-loop and it keeps spamming that print statement when it gets stuck.

**Comment by whirm** [comment]
Look at the link I pasted, I enabled debugging and it stops printing the debug stuff

**Comment by whirm** [comment]
Well, it actually never starts

**Comment by whirm** [comment]
I guess the test ends too quickly

**Comment by whirm** [comment]
in any case, if it the bool wasn't being set properly, it should keep printing the debug info

**Comment by devos50** [comment]
@whirm yeah indeed, I now see the print in the while loop and it stops spamming. It also says `stopping watchdog` so the join is done.

**Comment by devos50** [comment]
@whirm I see you pushed a fix, I will checkout your branch and test whether it also works for me by running the particular test that is failing several times :)

**Comment by whirm** [comment]
The join is not done, if You saw "Stopped watchdog" it would be done

https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/384/testReport/junit/Tribler.Test.Core.test_utilities/TriblerCoreTestUtilities/test_valid_torrent_file_nodes_invalid_length/

**Comment by devos50** [comment]
@whirm lol confused stopped with stopping -.-

**Comment by whirm** [comment]
it's really weird, because the same thread that's setting the should_stop attr by calling join, still sees the value as false

**Comment by whirm** [comment]
I think I know what's going on

**Comment by devos50** [comment]
```
======================================================================
ERROR: test_a_decode_false (Tribler.Test.Core.test_encoding.TriblerCoreTestUnicode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/martijn/tribler/Tribler/Test/test_as_server.py", line 134, in tearDown
    self.watchdog.join(2)
  File "/home/martijn/tribler/Tribler/Core/Utilities/instrumentation.py", line 110, in join
    with self._synchronized_lock:
AttributeError: 'WatchDog' object has no attribute '_synchronized_lock'
```

**Comment by whirm** [comment]
I think I fixed it

**Comment by whirm** [comment]
Apparently there's a race between the thread actually starting and calling join() before that actually happens, so _reset_state() (first line of run()) was being called AFTER join() was called in the main thread.

**Comment by devos50** [comment]
@whirm that makes sense! I'm running the tests now on your branch and it seems to work very well. Had no failures yet.

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
yay

**Pull request merged**
