### PR TITLE
Issue 2183 fix update tracker

### LINKED ISSUE #2183: Torrent Checker updated tracker manager when Tribler is shutting down.
`File "/home/jenkins/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Modules/tracker_manager.py", line 98, in update_tracker_info tracker_info = self._tracker_dict[tracker_url] exceptions.TypeError: 'NoneType' object has no attribute '__getitem__` error from the tests.

When shutting down, Tribler is now cancelling attempts to connect to trackers. The tracker manager may already have shutdown (in the future we will see more of this when units shutdown asynchronously). The result is that it invokes a function after a cleanup has been done and objects are none.

### PR DESCRIPTION
**Pull request by lfdversluis**
Fixes #2183 - **1** bug.

### CODE REVIEW

**Comment by lfdversluis** [comment]
@devos50 Can you review (if test pass)?

**Comment by lfdversluis** [comment]
`Tribler.Test.Core.test_sqlitecachedbhandler_votecasts.TestVotecastDBHandler.test_get_latest_vote_dispersy_id (from nosetests)`

`timeout expired before end of test (5.000000 s.)`

**Comment by lfdversluis** [comment]
retest this please

**Comment by devos50** [comment]
Looks ok to me.

**Pull request merged**
