### PR TITLE
Fix large dir names in SelectRemotePath

### PR DESCRIPTION
**Pull request by egbertbouman**

### CODE REVIEW

**Comment by qstokkink** [comment]
validate

**Review by qstokkink — APPROVED** [review]

**Comment by qstokkink** [comment]
I can now add files with long names but the torrent creation screen still bleeds over the edge:

**Comment by egbertbouman** [comment]
In my defense, none of this is happening in `SelectRemotePath ` 😉

**Comment by qstokkink** [comment]
No offense intended. I could not even get to the first screen without the fix of this PR. It would be nice to get rid of all #8260-type errors in one fell swoop though.

**Pull request merged**
