### PR TITLE
Created Structural Diagram

### PR DESCRIPTION
**Pull request by JeffGoderie**
@synctext

As requested, I've created an architectural image, and added a table containing 1-line explanations of the packages (we were unsure of a few of the channels, hence the ???). I figured you'd want this inside the wiki, but I didn't want to adapt the wiki without permission, so I created a folder for now.

### CODE REVIEW

**Comment by synctext** [comment]
retest this please

**Comment by synctext** [comment]
ok to test

**Comment by synctext** [comment]
add to whitelist

**Comment by synctext** [comment]
@JeffGoderie 
That looks nice. A picture, a table with clickable links.. Exactly what we need.
please rename it to a simple "doc" directory in the root, then it conforms more to the naming convention.

**Comment by JeffGoderie** [comment]
@synctext 
Ok, I just renamed the folder to doc!

**Comment by synctext** [comment]
ok to test

**Comment by synctext** [comment]
@JeffGoderie 
Fighting with Jenkins to get this tested on Jenkins. (``OK to test``)
Invited you to the Tribler Team. That should give you hopefully the required permissions. Can you re-open a fresh pull request to see if it now finally works?

**Comment by synctext** [comment]
are you seeing my team invitation, sent through Github?

**Comment by JeffGoderie** [comment]
Yeah, I've just accepted it, sorry was busy with the Software Architecture
presentations.

2015-04-10 14:10 GMT+02:00 Johan Pouwelse <notifications@github.com>:

**Comment by JeffGoderie** [comment]
Closing this PR now, opening a new one to see whether that works.

**Pull request closed without merging**
