### PR TITLE
Refactored tunnel helper plugin + changed master peers

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
There is something very wrong with with this PR causing the `test_anon_download` to be highly unstable. Put I'm still not sure what is causing it.

**Comment by qstokkink** [comment]
This seems to work from a fresh checkout. The failure is probably due to the `Tribler/pyipv8` merge conflict.

**Comment by devos50** [comment]
@qstokkink thanks for all the work on this PR! I will fix the conflict today or tomorrow 👍

**Comment by qstokkink** [comment]
@devos50 Don't worry, rebasing it now already.

**Comment by qstokkink** [comment]
Although the `Tribler/pyipv8` conflict remains after rebase still 😕. I'm not sure what's going on there.

**Comment by qstokkink** [comment]
@devos50 Nevermind: I have no idea how to fix the submodule conflict 😄 .

In the meantime, check out the new `test_anon_download` output:
```
.
----------------------------------------------------------------------
Ran 1 test in 17.489s

OK
```

**Comment by devos50** [comment]
@qstokkink a rebase on the latest `devel` did the trick :)

**Comment by qstokkink** [comment]
I can explain the hidden services test finding too many peers:

https://github.com/Tribler/tribler/blob/57e45320d72609bdc1086da04457578fc028ab53/Tribler/Test/Community/Tunnel/FullSession/test_hidden_services.py#L21-L23

Should be:

```python
 for c in self.tunnel_communities: 
     self.assertEqual(7, len(c.get_peers())) 
self.assertEqual(7, len(self.tunnel_community_seeder.get_peers())) 
```

**Comment by devos50** [comment]
@qstokkink thanks. I fixed the other errors in the tests (besides the hidden services test) already. I will change the code according to your suggestion. 👍

**Comment by qstokkink** [comment]
@devos50 We should actually disable the DiscoveryCommunity completely for the hidden services test. When using the wild network `yield self.deliver_messages` may take a long time.

**Comment by devos50** [comment]
@qstokkink I prefer disabling the discovery community then. We should also disable it for the other tunnel tests then right? Is there an easier way to disable this community besides looping over the overlays and unloading it?

**Comment by qstokkink** [comment]
@devos50 It would have to be a Session config setting. Otherwise, it's just as you said.

**Comment by devos50** [comment]
@qstokkink I'm not in favour making it a config option right now since it would only serve purpose during the tests. I will 'manually' unload the community then.

**Comment by qstokkink** [comment]
@devos50 Besides `unload()`-ing the community and removing it from `strategies` and `overlays` it might also be a good idea to set `ipv8`'s `.network` to a new `Network` instance.

**Comment by devos50** [comment]
@qstokkink done, see https://github.com/Tribler/tribler/pull/3467/commits/3117a70e36abcdf5d4600ce6f51f77cc14de302f

**Comment by qstokkink** [comment]
🎉

**Comment by devos50** [comment]
@qstokkink did you by any chance test whether a Tribler instance with the code in this PR is able to find exit nodes and download some data?

**Comment by qstokkink** [comment]
@devos50 No, not yet.

**Pull request merged**
