### PR TITLE
Implemented a page that displays trust statistics in Tribler

### PR DESCRIPTION
**Pull request by devos50**
In this PR, I created a screen that displays some trust metrics to users in our new GUI. This data is based on the interactions stored in the Multichain and acts as the foundation for our future work on trust.

At the moment, it's very basic and only shows the totals of your interaction history, including a graph. The graph is rendered using matplotlib, a library which we can reuse to create more sophisticated graphs elsewhere in the user interface. Overall, I think it's a very powerful library to include, especially if we want to visualise networks or graphs like download speed or your web of trust.

When our multichain credits vs Bitcoin market goes live, this screen will feature a 'trade' button to open the order book.

Related to #2803

### CODE REVIEW

**Comment by devos50** [comment]
The screen currently looks like this:

[trust_screen_values.pdf](https://github.com/Tribler/tribler/files/785973/trust_screen_values.pdf)

By clicking on the 'show ratios' button, you see this:

[trust_screen_ratios.pdf](https://github.com/Tribler/tribler/files/785974/trust_screen_ratios.pdf)

@synctext do you think this screen is complete enough or are we missing some information?

**Comment by devos50** [comment]
Only the mac GUI tests are failing since there is no matplotlib installed on this machine yet. Will fix this tomorrow.

**Comment by synctext** [comment]
Number of people you helped:
Number of people that helped you:
Amount of records on blockchain:
 (the details of content are NEVER shared)
Largest amount you got from somebody:

**Comment by devos50** [comment]
@synctext thanks! Was also thinking about the unique number of people that helped you/you have helped already. I will think about a nice table-like layout to present these values 👍

**Comment by devos50** [comment]
I was not happy with the current design of the screen so I redesigned it while taking the comments of @synctext in mind:

trust_screen_1

trust_screen_2

@synctext can you approve these screens?

**Comment by devos50** [comment]
Windows builder got stuck...

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
Issue #2795 occurred, thinking about disabling it...

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
@egbertbouman ready for review!

**Comment by devos50** [comment]
https://www.google.nl/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwic79b1x6HSAhXE7xQKHY8nC6sQjRwIBw&url=http%3A%2F%2Fmaterialdesignblog.com%2Fmonsteradmin-template-with-a-touch-of-material-design%2F&bvm=bv.147448319,d.d24&psig=AFQjCNGXOZVbZ72h5uhmLnueHOEmsC6qRA&ust=1487779292793214

Example page

**Comment by devos50** [comment]
New design (note that the settings/trust buttons have been moved to the upper right corner):

trust_screen

**Comment by devos50** [comment]
retest this please (GUI tests should pass now)

**Pull request merged**
