### PR TITLE
Fix Unicode decode error in socks conversion

### PR DESCRIPTION
**Pull request by xoriole**
Fixes Unicode decode error in socks conversion.

### CODE REVIEW

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
Retry DeepCode

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
Retry DeepCode

**Comment by ichorid** [comment]
@xoriole , please, don't merge fixes into `devel` directly. Instead, these should go into `release-7.4.0` branch, so we can merge them into `devel` later, as we did with 7.3.0. Otherwise, revision control becomes a mess.

**Pull request merged**
