### PR TITLE
WIP: Handle resources with "with" statements

### PR DESCRIPTION
**Pull request by Solomon1732**
Resources (files, sockets, and database connections) in relatively old files in both the Tribler application and its testing files were handled manually or handled with "finally". This is due to them being written before "with" statements were added to python (per @devos50 's comment in issue #4890 )

They have been rewritten to be handled with "with" statements to handle them correctly in case of exceptions, avoid doubly closing them (some were closed manually after being handled with "with" block), and make the code more concise, readable, and less brittle.

### CODE REVIEW

**Comment by Solomon1732** [comment]
There's one place which I didn't switch to use to a "with" statement:

https://github.com/Tribler/tribler/blob/887bd0499b27b8850ea890ff49fe09a4a592e354/Tribler/Test/Core/Modules/test_resource_monitor.py#L121

This is because the file is created/trunketed and then immediately closed. I felt that switching it to use "with" will reduce readability while adding nothing.

**Comment by Solomon1732** [comment]
Regarding my comment above, there's apparently a way to do that without an open-close pair according to [this stackoverflow](https://stackoverflow.com/questions/12654772/create-empty-file-using-python#12654798) question. It's basically to use `os.mknod`.

There are 2 problems with this approach, however:

1. The [top answer](https://stackoverflow.com/a/12654798) itself states that it "*requires root privileges on OSX*" [italics in source]. I lack OSX to test it, and if it's true it's a lot of hassle to go for a one-liner in a testing module. And even if that weren't an issue there's
2. The fact that both the [py 2](https://docs.python.org/2/library/os.html#os.mknod) docs and [py 3](https://docs.python.org/3/library/os.html#os.mknod) docs mention it being unix specific, meaning that the current code will still remain for non-unix OSs (Windows), but on top of that there will be additional code for unix OSs (Specifically OSX and Linux distros), which is a *lot* of trouble with a one-liner.

**Comment by Solomon1732** [comment]
This pull request concerns issue  #4890

**Comment by devos50** [comment]
ok to test

**Comment by devos50** [comment]
> There's one place which I didn't switch to use to a "with" statement:

That's fine. We usually do not compromise on readability, only if it is really necessary.

As you see, we have various PR checks in place. The pylint and flake8 lint checkers raise warnings about cosmetic issues, which should be relatively easy for you to fix. It also seems that our unit tests (which runs on all major platforms) is not happy with the code changes:

```
======================================================================
ERROR: If no C{methodName} argument is passed to the constructor, L{run} will
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_Tests/PR_linux/tribler/Tribler/Test/Core/Modules/RestApi/base_api_test.py", line 72, in setUp
    yield super(AbstractBaseApiTest, self).setUp()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_Tests/PR_linux/tribler/Tribler/Test/test_as_server.py", line 281, in setUp
    self.setUpPreSession()
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_Tests/PR_linux/tribler/Tribler/Test/Core/Modules/RestApi/base_api_test.py", line 91, in setUpPreSession
    self.config.set_http_api_port(self.get_port())
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_Tests/PR_linux/tribler/Tribler/Test/test_as_server.py", line 123, in get_port
    return self.get_ports(1)[0]
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_Tests/PR_linux/tribler/Tribler/Test/test_as_server.py", line 115, in get_ports
    selected_port = get_random_port(min_port=min_base_port, max_port=max_base_port)
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_Tests/PR_linux/tribler/Tribler/Core/Utilities/network_utils.py", line 32, in get_random_port
    if check_random_port(try_port, socket_type):
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_Tests/PR_linux/tribler/Tribler/Core/Utilities/network_utils.py", line 68, in check_random_port
    if _test_port(_family, socket.SOCK_DGRAM, port):
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_Tests/PR_linux/tribler/Tribler/Core/Utilities/network_utils.py", line 89, in _test_port
    with socket.socket(family, sock_type) as s:
AttributeError: __exit__
```

Could you please address this?

**Comment by devos50** [comment]
@Solomon1732 also, please prefix your PRs with WIP if it is work in progress, and with READY if it is ready for a review 👍

**Comment by Solomon1732** [comment]
> Could you please address this?

On it
 
> @Solomon1732 also, please prefix your PRs with WIP if it is work in progress, and with READY if it is ready for a review 👍

Sorry. Will do from now on

**Comment by Solomon1732** [comment]
There are a couple of failed pylint checks which are the result of a couple of exception catches that do not specify any type:

https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Upgrade/db72_to_pony.py#L132

https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Upgrade/db72_to_pony.py#L405

What do I do with those?

**Comment by Solomon1732** [comment]
I'm running into some socket errors.

https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_win64_py3/246/artifact/output/test_runners_output/0.err/*view*/
https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_win64_py3/246/artifact/output/test_runners_output/2.err/*view*/

Since (after all the changes I made in this pull request) I can't find any changes between the failing tests and the upstream ones, I'm thinking of closing this pull request and opening an alternative (draft) one with a cleaner commit history. What do you think @devos50 ?

Won't close this pull request without you or any one of the other devs saying so.

**Comment by Solomon1732** [comment]
Alternatively I could undo all the changes to the branch locally, then push to remote (meaning my github repo) when it's ready on the local (which is what I *should* have done from the start -_-. Sorry about the mess...). This way history will be kept and you'll see one request here. It will also make it easier to see the conversation's history instead of jumping to a prior PR.

**Comment by ichorid** [comment]
> Alternatively I could undo all the changes to the branch locally, then push to remote (meaning my github repo) when it's ready on the local (which is what I _should_ have done from the start -_-. Sorry about the mess...). This way history will be kept and you'll see one request here. It will also make it easier to see the conversation's history instead of jumping to a prior PR.

The way to handle this kind of situations (i.e. a branching/commit mess):
0) Checkout `devel` and make sure that your local `devel` is in sync with your remote `devel` and with the upstream `devel` (that is, primary Tribler repo `devel);
1) Locally, checkout the commit that is prior to your unfortunate `devel` merge;
2) Force push your local branch to you remote `git -f branch_name`
3) After your local repo is in sync with your remote repo, rebase your changes interactively on top of your `devel`: `git rebase -i devel`. That is a good opportunity to squash the commits, BTW.
4) Resolve any conflicts and when you're done, force-push the feature branch to your repo again: `git -f`. This will rewrite the history of *your* feature branch, but rewriting history in a feature branch is fine as long as only you work on it.
5) Proceed with the PR as usual. Github will notice the changes and re-test the thing.

**Comment by ichorid** [comment]
@Solomon1732 , when you're done rebasing, you can retest the thing a couple of times to see if the socket errors persist. I see `twisted.trial.util.DirtyReactorAggregateError: Reactor was unclean.` there. This typically means that some background thread is stuck doing stuff, making Twisted unable to shutdown the reactor cleanly. This could have happened because of your `with`-locks-related changes. Alternatively, the problem could be in our :hankey:-ey tests suite that is not entirely compatible with Python3. Try to prove that the problem is not yours, and we'll probably fix it :wink:

**Comment by Solomon1732** [comment]
> The way to handle this kind of situations (i.e. a branching/commit mess):

Lucky for me I've been handling all this mess on a branch rather than on `devel`, so the main branch is clean, which *should* make it somewhat easier... Will still have to untangle this mess, tho.

> when you're done rebasing, you can retest the thing a couple of times to see if the socket errors persist.

Is there a way to test it that doesn't involve pushing changes here? I'm sure there's a way written in the [docs](https://tribler.readthedocs.io/en/devel/index.html) but I can't seem to find it... 😅

**Comment by ichorid** [comment]
retest this please

**Comment by Solomon1732** [comment]
> retest this please

How do I rerun tests? 😅 Why didn't I ask this earlier...

> There are a couple of failed pylint checks which are the result of a couple of exception catches that do not specify any type:
https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Upgrade/db72_to_pony.py#L132
https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Upgrade/db72_to_pony.py#L405
What do I do with those?

I tried looking at [get_uniformed_tracker_url](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Utilities/tracker_utils.py#L28) and I can't really tell what exceptions might be raised so I can't specify the exceptions. I'd appreciate help disentangling the method because when I look at the source code nothing obvious jumps up 😅 

As can be seen here the blank exceptions have existed prior to me working on the files.
https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Upgrade/db72_to_pony.py#L132
https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Upgrade/db72_to_pony.py#L227

**Comment by Solomon1732** [comment]
Also please note that I disentangled the git mess I made. And I thank you *very much* for your guidance @ichorid, it has aided me greatly.

**Comment by ichorid** [comment]
retest this please

**Comment by ichorid** [comment]
@Solomon1732 , thanks for contributing! :+1: 

> As can be seen here the blank exceptions have existed prior to me working on the files.
> https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Upgrade/db72_to_pony.py#L132
> https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Upgrade/db72_to_pony.py#L227

The reason for these bare exceptions exist is that the converter procedure is *opportunistic*. It should just silently skip non-convertible entries. Of course, it would be more correct to list all possible non-fatal exceptions that the SQLite wrapper can raise while reading an entry from the old database. However, it is hard to imagine that we want some kind of an exception to be able to crash Tribler in this case. Thus, I used the catch-all exception. Nonetheless, adding a warning there is a good idea.

Also, why did you added the "revert" commit for the change from another branch? When you rebase and squash, you should remove this stuff.

**Comment by Solomon1732** [comment]
> @Solomon1732 , thanks for contributing! 👍
Thanks for accepting my contributions 😄 

> The reason for these bare exceptions exist is that[...]

👍 

> Also, why did you added the "revert" commit for the change from another branch? When you rebase and squash, you should remove this stuff.

Ah. Sorry. Thought that it might be relevant for the git history. But in retrospect for a pull request it's indeed noise and doesn't help. Will remove

**Comment by Solomon1732** [comment]
A previous build (last one before git history rebasing): https://jenkins-ci.tribler.org/job/GH_Tribler_PR/2985/
Latest build (after git rebasing): https://jenkins-ci.tribler.org/job/GH_Tribler_PR/2987/

Latest build has tests passing which have previously failed. The two failed tests have the following lines:
> ERROR: Step ‘Publish xUnit test result report’ failed: [JUnit] - No test report file(s) were found with the pattern '**/*nosetests.xml' relative to 'C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64' for the testing framework 'JUnit'.
Did you enter a pattern relative to (and within) the workspace directory?
Did you generate the result report(s) for 'JUnit'?"

The 2 tests for reference:
https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_win64_py3/254/console
https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_win64/2930/console

**Comment by Solomon1732** [comment]
> > Also, why did you added the "revert" commit for the change from another branch? When you rebase and squash, you should remove this stuff.
> Ah. Sorry. Thought that it might be relevant for the git history. But in retrospect for a pull request it's indeed noise and doesn't help. Will remove

Done. Latest push is removing the commit in question

**Comment by Solomon1732** [comment]
> The reason for these bare exceptions exist is that the converter procedure is opportunistic. It should just silently skip non-convertible entries. Of course, it would be more correct to list all possible non-fatal exceptions that the SQLite wrapper can raise while reading an entry from the old database. However, it is hard to imagine that we want some kind of an exception to be able to crash Tribler in this case. Thus, I used the catch-all exception. Nonetheless, adding a warning there is a good idea.

Added warnings. I also changed it from catching *all* exceptions to catching only `Exception` and derivatives. Catching them all blindly catches exceptions such as `SystemExit`, which might result in unexpected behavior.

**Comment by ichorid** [comment]
retest this please

**Comment by ichorid** [comment]
```
======================================================================
ERROR: test_cleanup_pony_experimental_db
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "c:\python27\lib\site-packages\twisted\internet\utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "c:\python27\lib\site-packages\twisted\internet\utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\Tribler\Test\test_as_server.py", line 66, in check
    result = fun(*argv, **kwargs)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\Tribler\Test\Core\Upgrade\test_db72_to_pony.py", line 145, in test_cleanup_pony_experimental_db
    cleanup_pony_experimental_db(pony_db)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\Tribler\Core\Upgrade\db72_to_pony.py", line 473, in cleanup_pony_experimental_db
    os.unlink(new_database_path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\workspace\\jenkins2\\workspace\\GH_Tribler_PR_Tests\\PR_win64\\tribler\\Tribler\\Test\\temp\\TestUpgradePreconditionChecker_tribler_test_session_DRVEQJ\\pony.db'

======================================================================
ERROR: test_cleanup_pony_experimental_db
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\Tribler\Test\test_as_server.py", line 237, in tearDown
    super(AbstractServer, self).tearDown()
  File "C:\workspace\jenkins2\workspace\GH_Tribler_PR_Tests\PR_win64\tribler\Tribler\Test\test_as_server.py", line 82, in tearDown
    shutil.rmtree(six.text_type(temp_dir), ignore_errors=False)
  File "c:\python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "c:\python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\workspace\\jenkins2\\workspace\\GH_Tribler_PR_Tests\\PR_win64\\tribler\\Tribler\\Test\\temp\\TestUpgradePreconditionChecker_tribler_test_session_DRVEQJ\\pony.db'
```
https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_win64/2941/artifact/output/test_runners_output/2.err/*view*/

This is a really annoying kind of error that arises from Windows file access semantics being different from Unix one. It is hard to debug for us because almost none of us run Windows :smile:

**Comment by Solomon1732** [comment]
> This is a really annoying kind of error that arises from Windows file access semantics being different from Unix one.

Ah.
>  It is hard to debug for us because almost none of us run Windows 😄

Rip. Good thing I do, then? 😆 
> Still, you have to fix it if you want this PR to be merged.

And so I will. Time to roll up my sleeves and get in the debugging muck 😆 Will take some time, tho 😄

**Comment by Solomon1732** [comment]
#4908 might be relevant here.

Regarding another matter - while trying to sent the environment for `devel` branch I run into an error setting up the environment. I cannot install scrypt on windows 10. Seems to be a known problem.
https://bitbucket.org/mhallin/py-scrypt/issues/18/scrypt-is-not-pip-installable-on-windows
I'm not the only one with the problem
https://github.com/Codaone/DEXBot/issues/25

**Comment by Solomon1732** [comment]
I decided to split the logging of the bare exceptions to another pull request [#5011](https://github.com/Tribler/tribler/pull/5011). Separation of concerns and all that.

**Comment by ichorid** [comment]
@Solomon1732 , please rebase on the latest `devel`. A lot have changed since, we move to `asyncio` for instance.

**Comment by Solomon1732** [comment]
Closing pull request and starting from scratch

**Pull request closed without merging**
