### PR TITLE
Now packing and installing windows c++ redistributable 2008 and 2010

### LINKED ISSUE #2049: Tribler breaks with: OSError: Unable to obtain adapter information.
- [x ] I have read CONTRIBUTING.md

- [x ] I have tried with the latest pre-release version and I still can reproduce the issue.

Tribler version/branch+revision: 6.5.1

Operating system and version: windows 8.1 x64

Expected behavior: Download a file via magnet link or torrent file and clean exit.

Actual behavior: After adding a magnet link or torrent file all that happens is: "Building circuits" and port status unknown. At exit an error is created and a logfile is written.

Steps to reproduce the behavior: See above.

Relevant log file output: 
```
ERROR   1458515290.56        dispersy:214   failed to check network interfaces.
Traceback (most recent call last):
  File "Tribler\dispersy\dispersy.pyo", line 195, in _get_interface_addresses
OSError: Unable to obtain adapter information.
ERROR   1458515290.56        dispersy:238   Unable to find our public interface!
```

### PR DESCRIPTION
**Pull request by lfdversluis**
@whirm Can you give this build script a go on the builder? Or can I do it?

Fixes #2049

Fixes **1** bug.

### CODE REVIEW

**Comment by lfdversluis** [comment]
| Library   |      Dependency      |
|----------|:-------------:|
| Python | MSVCR90.dll |
| M2Crypto |  MSVCR90.dll |
| LevelDB |    MSVCR100.dll   |
| LibTorrent | MSVCP90.dll & MSVCR90.dll |
| netifaces | MSVCR90.dll |
| apsw | MSVCR90.dll |

I sometimes see the `MSVCR110_WIN.dll` file. But little is known about this. It doesn't seem to be the `MSVCR110.dll` file, but I am not sure what it is exactly.

**Comment by lfdversluis** [comment]
@whirm ready for merge

**Comment by lfdversluis** [comment]
https://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_laurens/ packs and installs both versions just fine.

**Comment by whirm** [comment]
Nice

**Pull request merged**
