### PR TITLE
Add missing notifier topic observers based on enum values

### PR DESCRIPTION
**Pull request by xoriole**
Fixes https://github.com/Tribler/tribler/issues/6751

### CODE REVIEW

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
```
==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
/Users/tribler/Library/Python/3.8/lib/python/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
src/tribler-core/tribler_core/conftest.py:14: in <module>
    from tribler_common.network_utils import default_network_utils
E   ModuleNotFoundError: No module named 'tribler_common'
```
Seems different PR sources are getting mixed on Jenkins

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by drew2a** [comment]
@xoriole 
> Seems different PR sources are getting mixed on Jenkins

I guess it is coming from #6755.
But I don't understand how it is possible.

**Comment by kozlovsky** [comment]
It seems that when Jenkins job clones the Tribler repo, it sometimes clones a previous state of Tribler repo that was intended for the previous instance of this job.

**Comment by xoriole** [comment]
retest this please

**Pull request merged**
