### PR TITLE
WIP: use setuptools and update setup.py with readme and license

### PR DESCRIPTION
**Pull request by brussee**
Nose now runs the Tribler tests on Android.

### CODE REVIEW

**Comment by brussee** [comment]
```
I: Run user program, change dir and execute entrypoint
I: test_download_torrent_from_file (Tribler.Test.API.test_download.TestDownload) ... ok
I: test_download_torrent_from_magnet (Tribler.Test.API.test_download.TestDownload) ... ok
I: test_download_torrent_from_url (Tribler.Test.API.test_download.TestDownload) ... ok
I: test_normal_torrent (Tribler.Test.API.test_seeding.TestSeeding) ... ERROR
I: 2016-06-30 20:43:07,725 [ERROR] Resume data cancelled
I: ======================================================================
I: ERROR: test_normal_torrent (Tribler.Test.API.test_seeding.TestSeeding)
I: ----------------------------------------------------------------------
I: Traceback (most recent call last):
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/test_as_server.py", line 73, in check
I:     result = fun(*argv, **kwargs)
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/API/test_seeding.py", line 96, in test_normal_torrent
I:     self.subtest_is_seeding()
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/API/test_seeding.py", line 102, in subtest_is_seeding
I:     s.read_handshake_medium_rare()
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/btconn.py", line 100, in read_handshake_medium_rare
I:     data = self._readn(68)
I:   File "/data/data/org.tribler.android/files/lib/python2.7/site-packages/Tribler/Test/btconn.py", line 149, in _readn
I:     raise ex
I: error: [Errno 104] Connection reset by peer
I: ----------------------------------------------------------------------
I: Ran 4 tests in 12.222s
I: FAILED (errors=1)
I: Python for android ended.
```

**Comment by brussee** [comment]
retest this please

**Comment by brussee** [comment]
retest this please

**Comment by brussee** [comment]
@whirm Ready.

**Comment by whirm** [comment]
@devos50 Could you see if it works on OSX?

**Comment by devos50** [comment]
@whirm what do you want me to test exactly?

**Comment by whirm** [comment]
Isn't the package builder using setup.py?

**Comment by devos50** [comment]
@whirm not that I know, the OS X builders are using this: https://github.com/Tribler/tribler/blob/devel/Tribler/Main/Build/Mac/setuptriblermac_64bit.py.

**Pull request merged**
