### PR TITLE
Move to newest TunnelCommunity

### PR DESCRIPTION
**Pull request by egbertbouman**

### CODE REVIEW

**Comment by qstokkink** [comment]
This might just be a case of having to run `pip install aead` on the Mac machine.

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
Nope, that wasn't it.

**Comment by egbertbouman** [comment]
retest this please

**Comment by egbertbouman** [comment]
retest this please

**Comment by qstokkink** [comment]
Have you tried to run `python -c "import cryptography.hazmat.primitives.ciphers.aead"` on the Mac?

**Comment by egbertbouman** [comment]
@qstokkink Yes, and that seems to work now. However, the tests still fail.

**Comment by egbertbouman** [comment]
retest this please

**Comment by synctext** [comment]
@Qstokkink: could we create a stress experiment with Gumby for PEX-communities? Plus realistic load for our donated servers with 10k communities ?

**Comment by qstokkink** [comment]
@synctext we have the infrastructure in place to do that relatively easily: yes.

**Comment by xoriole** [comment]
retest this please

**Pull request merged**
