### PR TITLE
Added German translation of README.md

### PR DESCRIPTION
**Pull request by Anth0rx**
I added the German translation of the README.md within the /doc directory and also created a new directory structure where I put the English versions in /doc/english and the German ones in /doc/german. I have also fixed the referece paths of the image accordingly.

### CODE REVIEW

**Comment by synctext** [comment]
OK to test

**Comment by whirm** [comment]
@Anth0rx I'd rather keep the english docs on its current place and create a german subdir, also, don't forget to add a reference to the german docs in /README.md or people will never find it :)

**Comment by Anth0rx** [comment]
Okay, I'm on it.

**Comment by Anth0rx** [comment]
Okay, I have placed the English versions in the original directory and added a link to the German translation in the /README.md.

**Comment by whirm** [comment]
Nice!
Could you squash both commits together?

**Comment by Anth0rx** [comment]
@whirm How do I squash both commits?

**Comment by whirm** [comment]
@Anth0rx with `git rebase -i`, but if you don't know how to do it, i'll do it myself, don't worry.

**Comment by Anth0rx** [comment]
Let me try first please ;)

**Comment by whirm** [comment]
@Anth0rx sure :D

**Comment by Anth0rx** [comment]
I find guides where they rebase master only but the commits should remain within the translation-german branch right?

**Comment by Anth0rx** [comment]
I think I've got it.

**Comment by whirm** [comment]
Great!, merging!

**Comment by Anth0rx** [comment]
Nice, why did you want just one commit? Or rather as I am proceeding translating some documentation related stuff when should I do commits? After every file translated or one commit when I have finished?

**Comment by whirm** [comment]
You can do all the commits you want but, once you are done, you should join all the changes that belong together into single commits. For instance if you refactor some python code and update some documentation, but you make some typos and make 4 commits fixing those, your python refactor should stay in a separate commit and the doc updates and following fixes should get squashed together.

We do it like this to make it easier for others to follow the change history (for instance the usage of git blame and suchlike).

**Comment by Anth0rx** [comment]
Okay nice.

**Comment by whirm** [comment]
BTW, as the wiki is a git repo too, if you want to do many changes you can also clone the thing and modify it locally with your favorite editor.

**Comment by Anth0rx** [comment]
Yes, I knew that already but thanks.

**Pull request merged**
