### PR TITLE
Apply MockIPv8 key injection

### LINKED ISSUE #6273: [main] Use `MockIPv8` key injection
The current version of IPv8 on the `main` branch supports key injection for `MockIPv8`. The following workarounds are no longer necessary:

https://github.com/Tribler/tribler/blob/a15533049ec73a48727e8c784180d9affe2357bb/src/tribler-core/tribler_core/modules/tests/bandwidth_accounting/test_bandwidth_endpoint.py#L26-L27

https://github.com/Tribler/tribler/blob/a15533049ec73a48727e8c784180d9affe2357bb/src/tribler-core/tribler_core/modules/tests/bandwidth_accounting/test_community.py#L26-L27

### PR DESCRIPTION
**Pull request by drew2a**
This PR fixes #6273

### CODE REVIEW

**Comment by xoriole** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by drew2a** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by kozlovsky** [comment]
retest this please

**Review by kozlovsky — APPROVED** [review]

**Pull request merged**
