### PR TITLE
Fixed issue with loading unicode torrents

### LINKED ISSUE #4974: Opening a torrent from browser crashes Tribler on Windows
Tribler 7.4.0-exp1, Win10.
Tribler crashes when clicking on a torrent with Cyrillic characters in its name (in the torrent contents, *not* the torrent filename).
Reporter: http://reporter.tribler.org/stacktrace/29428

```python
File "TriblerGUI\dialogs\startdownloaddialog.py", line 218, in on_received_metainfo
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 213: invalid start byte
```

### PR DESCRIPTION
**Pull request by xoriole**
Fixed issue of loading torrents with Unicode name by clicking it.

Fixes #4974

### CODE REVIEW

**Comment by ichorid** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Pull request merged**
