### PR TITLE
GUI HTTP request queue

### LINKED ISSUE #3303: Too many open files: 'peercache.txt'
Platform: Linux-4.10.0-42-generic-x86_64-with-Ubuntu-16.04-xenial 
Report: [(#11881)](http://reporter.tribler.org/stacktrace/11881)
```python
Traceback (most recent call last):
File "/usr/share/tribler/TriblerGUI/event_request_manager.py", line 99, in on_read_data
raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <type 'exceptions.IOError'>: [Errno 24] Too many open files: u'/home/dsk/.Tribler/peercache.txt'
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1194:run
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1203:mainLoop
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:825:runUntilCurrent
/usr/lib/python2.7/dist-packages/twisted/internet/task.py:239:__call__
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:150:maybeDeferred
/usr/share/tribler/Tribler/dispersy/discovery/community.py:801:clean_and_save
]
```

### LINKED ISSUE #3319: Continuous request to /downloads leads to higher CPU usage
In the GUI, we perform a request to `/downloads` every second, even when the downloads are not visible. This leads to higher CPU usage since libtorrent has to be queried and statistics have to be gathered and parsed. Additionally, this leads to additional file descriptors and 'pollutes' the history of requests in the crash reporter.

I propose to only perform a request to fetch downloads when the user actually has the page with downloads open. While this adds a small delay before users are able to see what they are downloading, I think it significantly saves resources in the long run. Also, this is quite easy to implement, requiring changing only a few lines of code.

@qstokkink @egbertbouman @xoriole @synctext what do you think?

### PR DESCRIPTION
**Pull request by qstokkink**
This PR adds a priority-based request queue for the GUI's HTTP requests to the core.
This PR also immediately lowers the maximum amount of (non-critical) outstanding requests to 200 and assigns health requests a low priority.

The code is done, but this PR still requires some stress testing on different machines before merging.

Fixes #3303.
Fixes #3319.

### CODE REVIEW

**Comment by devos50** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
@qstokkink I guess another Tribler instance is running on the mac, leading to the GUI tests failure.

**Comment by qstokkink** [comment]
@devos50 probably, yes. I still want to do some manual testing on different platforms with this code though, even though the unit tests pass.

**Comment by devos50** [comment]
@qstokkink I will also test it out today.

**Comment by qstokkink** [comment]
@devos50 thanks 👍

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
Seems to work fine on Windows. We might want to lower the cap on the maximum number of outstanding requests though.

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by devos50** [comment]
@qstokkink want to merge this one or do you want another review from @xoriole?

**Comment by qstokkink** [comment]
@devos50 Do you think we should lower the cap? It's at a window size of 200 requests right now. If you think it's fine, please merge it 👍 .

**Comment by devos50** [comment]
@qstokkink this requires a lot of file descriptors. I would propose to lower it to 50. If you agree, could you make this change and merge this PR then? 👍

**Comment by qstokkink** [comment]
@devos50 Uhh.. the failing Linux tests were expected right?

**Comment by qstokkink** [comment]
@devos50 while doing some stress testing with a low request limit, I noticed that torrents that got their request dropped were stuck in their health checking phase. I remedied this in 6a6027aca9670531af6845d9ac1df1ca8d6d811d, could you review this commit?

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
@qstokkink looks fine, I will merge it after the unit tests pass.

**Pull request merged**
