### PR TITLE
Fix issues with large paths

### PR DESCRIPTION
**Pull request by egbertbouman**

### CODE REVIEW

**Comment by egbertbouman** [comment]
validate

**Comment by egbertbouman** [comment]
validate

**Comment by qstokkink** [comment]
@egbertbouman is it time for a new pre-release after this?

**Comment by egbertbouman** [comment]
I can't think of anything that's needed for v8. So yes, I guess it's time for another (hopefully last) prerelease.

**Comment by qstokkink** [comment]
Nice 👌 I'll start the building.

**Pull request merged**
