### PR TITLE
Remove hashtype stuff as we dropped swift support.

### PR DESCRIPTION
**Pull request by whirm**

### CODE REVIEW

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
@LipuFei ready to merge

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
Well, turns out it's already at version 2

https://github.com/Tribler/tribler/pull/1210/files#diff-16455a6c4fa171a2985b82b57547dbe2R16

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by LipuFei** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by LipuFei** [comment]
@whirm ready?

**Comment by whirm** [comment]
nope, it's using the old key now

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
We need to have in mind that once this is merged, the non-isolated test runner will always fail, so we will have to migrate to the isolated one.

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
ready

**Pull request merged**
