### PR TITLE
Updated IPv8 pointer

### LINKED ISSUE #3861: Defining and implementing scalable policies for TrustChain record collection
After discussion, we decided that we have to define basic policies for TrustChain record (block) dissemination and collection. This issue will document the discussed policies.

**Infinite database growth**: when we deployed TrustChain, we noticed a quick growth in the total number of records. At the time of writing, the total number of blocks exceeds 1.25 million. _Proposed solution_: prune the total number of (irrelevant) blocks in the database when it has over 1 million blocks.
**Global record collection policy**: right now, we send out 10 blocks when receiving a crawl request. Crawl requests are initiated when receiving introduction requests and responses. _Proposed solution_: cap the global collection rate to 6 edges per minute.
**Individual node collection policy**: we do not distinguish between different nodes when collecting blocks. Every node is treated the same. _Proposed solution_: if we have a total of 1000 blocks of an individual node, disregard the upcoming crawl request with a probability of 90%.

In addition, we can speed up synchronization of knowledge by adding the length of an individuals chain to an introduction request.

### PR DESCRIPTION
**Pull request by devos50**
This includes the major TrustChain changes.

Fixes #3861

### CODE REVIEW

**Comment by qstokkink** [comment]
Oops, forgot to tell you: https://github.com/Tribler/py-ipv8/pull/287 has a critical fix in it.

**Comment by devos50** [comment]
@qstokkink I'm getting 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 197, in process
    self.render(resrc)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 257, in render
    body = resrc.render(self)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Modules/restapi/torrents_endpoint.py", line 284, in render_GET
    self.session.check_torrent_health(self.infohash.decode('hex'), timeout=timeout, scrape_now=refresh)\
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/Session.py", line 764, in check_torrent_health
    return self.lm.torrent_checker.add_gui_request(infohash, timeout=timeout, scrape_now=scrape_now)
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/pyipv8/ipv8/util.py", line 49, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/pyipv8/ipv8/util.py", line 61, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/TorrentChecker/torrent_checker.py", line 247, in add_gui_request
    deferred_list.append(session.connect_to_tracker().
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/Core/TorrentChecker/session.py", line 230, in connect_to_tracker
    {"info_hash": self._infohash_list})
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/pyipv8/ipv8/messaging/deprecated/encoding.py", line 356, in add_url_params
    url = urllib_future.unquote(url)
TypeError: unbound method unquote() must be called with  instance as first argument (got unicode instance instead)
```

Any idea why?

**Comment by qstokkink** [comment]
https://github.com/Tribler/py-ipv8/pull/287/files#diff-37daf94c89243f607eabe2ae45ee4e41R43

**Comment by devos50** [comment]
@qstokkink ready for review 👍

**Pull request merged**
