### PR TITLE
WIP - Fix tunnel test not having enough circuits

### PR DESCRIPTION
**Pull request by rjruigrok**

### CODE REVIEW

**Comment by rjruigrok** [comment]
retest this please

**Comment by rjruigrok** [comment]
@whirm I tried to make improve the test stability after the splitting up, but it's not working as expected. First tried to disable the dispersy walker and add the candidates manually, but the tunnel community stopped working. As a last resort tried to modify the community identifier, but dispersy drops all the messages because it considers the thing as an unknown community, and it still does not build tunnels. I worked for hours on this without getting any progress.

For the time being, I would restore the tunneltest as it was before splitting up. It takes 5 minutes more for executing the tests, but this splitted testing issue is a bit out of scope for me to solve. I thought it was just  a small change for me, not knowing it would break up everything. :wink: Or let me know if you can have a look at this thing?

**Comment by synctext** [comment]
@rjruigrok Having unit tests that are well understood, fast and stable is essential.
Currently the unit tests are not atomic and seem to require special ordering. Please try working on it another 1-2 days. The output graphs can directly feed into thesis.tex. On Friday plus Monday Egbert is probably available for comments in this space or a meeting at the 7th floor.

**Comment by rjruigrok** [comment]
No problem. Will try some more to fix this, hopefully no more hidden
elephants in there. :-)

Op donderdag 11 juni 2015 heeft Johan Pouwelse <notifications@github.com>
het volgende geschreven:

**Comment by whirm** [comment]
@rjruigrok are you changing the community ID before loading the community?

**Comment by rjruigrok** [comment]
@whirm Yep - I made a TestHiddenTunnelCommunity class, extending the HiddenTunnelCommunity class its `get_master_members` method, assigning it a master key that is generated once each time a test is executed (because each test creates multiple hidddentunnelcommunity's, all sharing the same masterkey). 
You can have a look at my changes in the code, they're quite straightforward, but causing dispersy to not find any candidate.

**Comment by rjruigrok** [comment]
I think I found the cause, because the tests run a full tribler instance, but it's still creating another HiddenTunnelCommunity without overriden masterkey in tribler_main:470. @whirm What do you suggest, monkeypatching this thing?

**Comment by synctext** [comment]
Glad you found the issue in a single day! Can you describe the key clash in an extra line or two please?

**Comment by whirm** [comment]
@rjruigrok Yeah, this should be a list so they can be easily overriden...

**Comment by synctext** [comment]
retest this please

**Comment by rjruigrok** [comment]
@synctext not finished yet, but getting closer! :)

Op vrijdag 12 juni 2015 heeft Johan Pouwelse <notifications@github.com> het
volgende geschreven:

**Comment by synctext** [comment]
Morning Rob,  http://jenkins.tribler.org//job/GH_Tribler_pull-request-tester-turbo_devel/130/artifact/output//Screenshot-30.png
@rjruigrok  Do we understand why there is a mix of 2-hop and a single 3-hop circuit build?

**Comment by rjruigrok** [comment]
Yep - the current tunnel tests use 3 hops for the hidden services. After
downloading over 2 hops, it automatically switches to anon seeding over
hidden seeding, building the introduction circuits etc. and they seem
to have a different length than the ordinary downloading circuits. Nothing
to worry about. :-)

Op vrijdag 12 juni 2015 heeft Johan Pouwelse <notifications@github.com> het
volgende geschreven:

**Pull request closed without merging**
