### PR TITLE
Merge additional commits from 7.7 branch

### PR DESCRIPTION
**Pull request by Shidouuu**
It seems for some reason commits were added *after* the 7.7 branch was first merged into devel. These commits also include a fix to on_reload_torrent_info()

It's missing all (4) commits from January 1st, and "Fix database upgrade fixes" from December 23rd, but it should be fine since it can merge automatically

Edit: I checked each of the commits missing and it appears to be completely fine to merge

### CODE REVIEW

**Comment by devos50** [comment]
ok to test

**Comment by ichorid** [comment]
Please don't use the "merge" button in GitHub - it will create an additional "pseudo-branch" if you do. All in-repository branches must be merged by hand in console Git to circumvent this problem.

I'll do it now.

**Comment by ichorid** [comment]
Done

**Comment by Shidouuu** [comment]
> Please don't use the "merge" button in GitHub - it will create an additional "pseudo-branch" if you do. All in-repository branches must be merged by hand in console Git to circumvent this problem.

Source? Just curious since I've never had a problem with this before

**Comment by ichorid** [comment]
See https://github.com/Tribler/tribler/pull/5427 for instance.

Now, I realize this is probably the result of merging from a *personal* fork. However, in the past, we often had to merge from personal branches because of hand-resolved conflicts.

**Pull request closed without merging**
