### PR TITLE
Fixed build on macOS

### PR DESCRIPTION
**Pull request by xoriole**
- Fixes pyinstaller script for building on macOS.
- Removes Tk as dependency

### CODE REVIEW

**Comment by devos50** [comment]
@xoriole could it be that the `cryptography` package is installed to the home dir of the `tribler` user on Mac? If so, the error that `cryptography` cannot be found is explained by the fact that we are overwriting the `HOME` env variable when running the nosetests in parallel.

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
retest this please

**Comment by xoriole** [comment]
Finally, tests are stable again

**Comment by xoriole** [comment]
PyInstaller bundling is working fine but there seems to be an issue with creating the dmg file.

```bash
+ mkdir -p dist/temp
+ hdiutil create -srcfolder dist/installdir -format UDRW -scrub -volname Tribler dist/Tribler.dmg
...................................................................
created: /Users/tribler/Documents/sandip/tribler/dist/Tribler.dmg
+ hdiutil attach -readwrite -noverify -noautoopen dist/Tribler.dmg -mountpoint dist/temp/mnt
/dev/disk2              GUID_partition_scheme              
/dev/disk2s1            Apple_APFS                         
/dev/disk3              EF57347C-0000-11AA-AA11-0030654    
/dev/disk3s1            41504653-0000-11AA-AA11-0030654    /Users/tribler/Documents/sandip/tribler/dist/temp/mnt
+ bless --folder dist/temp/mnt --openfolder dist/temp/mnt
Couldn't bless the APFS preboot volume for volume mounted at /Users/tribler/Documents/sandip/tribler/dist/temp/mnt: No such file or directory
```

**Comment by xoriole** [comment]
It seems that the latest version of Xcode has removed the macOS_SDK_headers_for_macOS_10.14.pkg file so carbon framework headers are missing.

```bash
Ts-Mac-mini:tribler tribler$ eulagise --license LICENSE --target dist/Tribler.dmg
mktemp -d dist/pkg-dmg.12956.XXXXXXXX
dist/pkg-dmg.12956.QyIoellF
hdiutil unflatten dist/Tribler.dmg
hdiutil: unflatten: unflattening "Tribler.dmg"...
/usr/bin/Rez Carbon.r dist/pkg-dmg.12956.QyIoellF/license.r -a -o dist/Tribler.dmg
failed to find Carbon/Carbon.r
### Rez - noErr (0) during open of "Carbon.r".
Fatal Error!
### Rez - Fatal Error, can't recover.
Carbon.r: ### Rez - Since errors occurred, dist/Tribler.dmg's resource fork was not completely updated.
/usr/local/bin/eulagise: Rez failed (cleaning up)
```

**Comment by xoriole** [comment]
The solution seems to be force re-install the header files:
```shell
$ sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
```
Xcode command line tools should be installed if not already available
```shell
$ xcode-select --install
```

**Pull request merged**
