### PR TITLE
Fix TorrentDefNoMetainfo.get_name_utf8() to return string

### PR DESCRIPTION
**Pull request by xoriole**
Fixes https://github.com/Tribler/tribler/issues/7836

The downloads response was not JSON serializable because the name was still being returned as bytes in case of serialization of name from torrent def of instance `TorrentDefNoMetainfo`. This PR fixes the issue.

### CODE REVIEW

**Review by drew2a — APPROVED** [review]
Looks good to me, despite the fact that in `TorrentDefNoMetainfo` there is a violation of the Liskov Substitution Principle, at least in the constructor. However, this is not your fault, but rather a design issue from the author of the class.

**Comment by qstokkink** [comment]
> there is a violation of the Liskov Substitution Principle, at least in the constructor.

@drew2a could you provide more details on this violation? AFAIK the substitution principle does not apply to constructors.

**Comment by drew2a** [comment]
@qstokkink, you are right; the Liskov Substitution Principle is not applicable to constructors. It was a false alarm.

**Comment by drew2a** [comment]
I apologize to the unknown author of this class 🙏

**Pull request merged**
