### PR TITLE
Removed some unused variables in the ABCApp class

### PR DESCRIPTION
**Pull request by devos50**
It appears that some variables in the ABCApp class are not used anymore and are probably safe to remove.

### CODE REVIEW

**Comment by whirm** [comment]
ok to test

**Comment by whirm** [comment]
@devos50 oh,  you should send this to `devel` instead. `next` is frozen for release.

**Comment by devos50** [comment]
@whirm ok I will send it to the devel branch!

**Comment by whirm** [comment]
Great, thx!

**Pull request closed without merging**
