### PR TITLE
Removed my channel GUI tests

### PR DESCRIPTION
**Pull request by devos50**
The stuff I removed here is already tested by the API endpoints tests/unit tests

The code coverage might drop a bit, I will write some tests to counter this.

### CODE REVIEW

**Comment by devos50** [comment]
The drop in coverage was minimal. I've written some small additional tests to stabilize the drop in coverage.

**Comment by whirm** [comment]
retest this please

**Comment by devos50** [comment]
@lfdversluis can you review?

**Comment by lfdversluis** [comment]
Looks ok. Does these test really cover all that you just deleted?

**Comment by devos50** [comment]
@lfdversluis there are probably a few lines of code that are now missing but these are hard to track. This is due to the fact that these big session tests are hard to control. For instance, in a specific run of the tests, it might be that some error handling code is triggered while this is not the case in some other (more successful) run.

I've tried my best to identify what's different between these old tests and the new refactored tests (which is also not easy since the coverage metric settings are slightly different between the `test_tribler_devel` and `GH_Tribler_PR` jobs) and I've added some additional tests to hopefully stabilize the code coverage.

Anyway, if you can identify some missing lines of code, I will gladly create some unit tests for these.

**Comment by lfdversluis** [comment]
I would flag it as READY. It is more important to get rid of wx at this stage so devel can move forward. If we find uncovered lines with nose and coverage, we can always add tests.

**Comment by lfdversluis** [comment]
(Of course critical code should be covered, we always must have a basis to build on)

**Comment by devos50** [comment]
@lfdversluis I agree, other people are dependent on the wx removal at the moment and writing unit tests can always be done (but should be done in the long run lol).

**Comment by devos50** [comment]
@whirm ready for you review

**Pull request merged**
