### PR TITLE
Fixes for GUI emit interface mismatches

### LINKED ISSUE #5824: [7.6.0] TypeError: TriblerNetworkRequest.received_json[object] signal has 1 argument(s) but 2 provided
Sentry Issue: [TRIBLER-3P](https://sentry.tribler.org/organizations/tribler/issues/272/?referrer=github_integration)

```
TypeError: TriblerNetworkRequest.received_json[object] signal has 1 argument(s) but 2 provided
```

```
  File "src\tribler-gui\tribler_gui\tribler_request_manager.py", line 203, in on_finished, 
  File "src\tribler-core\tribler_core\utilities\json_util.py", line 112, in loads, 
  File "lib\json\__init__.py", line 357, in loads, 
  File "lib\json\decoder.py", line 337, in decode, 
  File "lib\json\decoder.py", line 355, in raw_decode, 
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0), 
During handling of the above exception, another exception occurred:, 
Traceback (most recent call last):, 
  File "src\tribler-gui\tribler_gui\tribler_request_manager.py", line 120, in <lambda>, 
  File "src\tribler-gui\tribler_gui\tribler_request_manager.py", line 213, in on_finished, 
TypeError: TriblerNetworkRequest.received_json[object] signal has 1 argument(s) but 2 provided
]
```

### LINKED ISSUE #5840: TypeError: on_close() takes 0 positional arguments but 1 was given
Sentry Issue: [TRIBLER-3X](https://sentry.tribler.org/organizations/tribler/issues/281/?referrer=github_integration)

```python
 Traceback (most recent call last):,
   File "/home/<user>/src/tribler/src/run_tribler.py", line 154, in <module>,
     sys.exit(app.exec_()),
   File "/home/<user>/src/tribler/src/tribler-gui/tribler_gui/utilities.py", line 382, in trackback_wrapper,
     callback(*args, **kwargs),
   File "/home/<user>/src/tribler/src/tribler-gui/tribler_gui/tribler_request_manager.py", line 121, in <lambda>,
     connect(request.reply.finished, lambda: request.on_finished(request)),
   File "/home/<user>/src/tribler/src/tribler-gui/tribler_gui/tribler_request_manager.py", line 210, in on_finished,
     request_manager.show_error(TriblerRequestManager.get_message_from_error(json_result)),
   File "/home/<user>/src/tribler/src/tribler-gui/tribler_gui/tribler_request_manager.py", line 86, in show_error,
     connect(error_dialog.button_clicked, on_close),
 tribler_gui.utilities.CreationTraceback,
 
 The above exception was the direct cause of the following exception:,
 
 Traceback (most recent call last):,
   File "/home/<user>/src/tribler/src/tribler-gui/tribler_gui/utilities.py", line 385, in trackback_wrapper,
     raise exc from source_exc,
   File "/home/<user>/src/tribler/src/tribler-gui/tribler_gui/utilities.py", line 382, in trackback_wrapper,
     callback(*args, **kwargs),
 TypeError: on_close() takes 0 positional arguments but 1 was given
```

Both this definition (in `src/tribler-gui/tribler_gui/tribler_request_manager.py`) and the one in `src/tribler-gui/tribler_gui/dialogs/confirmationdialog.py` feature an `on_close()` function that should take a `checked` argument, as follows:

```python
def on_close(checked):
```

### LINKED ISSUE #5841: TypeError: stop_discovering() takes 1 positional argument but 2 were given
Sentry Issue: [TRIBLER-3W](https://sentry.tribler.org/organizations/tribler/issues/280/?referrer=github_integration)

```
 Traceback (most recent call last):,
   File "/home/<user>/tribler/src/run_tribler.py", line 154, in <module>,
     sys.exit(app.exec_()),
   File "/home/<user>/tribler/src/tribler-gui/tribler_gui/utilities.py", line 382, in trackback_wrapper,
     callback(*args, **kwargs),
   File "/home/<user>/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 104, in on_read_data,
     reaction(event),
   File "/home/<user>/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 62, in <lambda>,
     NTFY.TRIBLER_STARTED.value: lambda data: self.tribler_started.emit(data["version"]),,
   File "/home/<user>/tribler/src/tribler-gui/tribler_gui/utilities.py", line 382, in trackback_wrapper,
     callback(*args, **kwargs),
   File "/home/<user>/tribler/src/tribler-gui/tribler_gui/tribler_window.py", line 476, in on_tribler_started,
     connect(self.core_manager.events_manager.discovered_channel, self.stop_discovering),
     tribler_gui.utilities.CreationTraceback,
     
 The above exception was the direct cause of the following exception:,
 
 Traceback (most recent call last):,
   File "/home/<user>/tribler/src/tribler-gui/tribler_gui/utilities.py", line 385, in trackback_wrapper,
     raise exc from source_exc,
   File "/home/<user>/tribler/src/tribler-gui/tribler_gui/utilities.py", line 382, in trackback_wrapper,
     callback(*args, **kwargs),
 TypeError: stop_discovering() takes 1 positional argument but 2 were given
```

The `stop_discovering()` in `src/tribler-gui/tribler_gui/tribler_window.py` should accept a `response` argument, as follows:

```python
stop_discovering(self, response)
```

### LINKED ISSUE #5859: [7.6.0] TypeError: ClickableLineEdit.clicked[] signal has 0 argument(s) but 1 provided
User comment: "Happens when I click search"
```
Traceback (most recent call last):, 
  File "/home/<user>/src/tribler/src/tribler-gui/tribler_gui/widgets/clickable_line_edit.py", line 12, in mousePressEvent, 
    self.clicked.emit(False), 
TypeError: ClickableLineEdit.clicked[] signal has 0 argument(s) but 1 provided
```

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #5824 
Fixes #5840 
Fixes #5841 
Fixes #5859

### CODE REVIEW

**Comment by qstokkink** [comment]
🤔 did our TorrentChecker just find wild peers through DHT in `test_on_health_check_completed`?

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
More core failures while I didn't touch the core 😃 

```python
================================== FAILURES ===================================
_________________________ test_download_load_corrupt __________________________
[gw5] win32 -- Python 3.8.4 c:\users\tribler\appdata\local\programs\python\python38\python.exe

download_config = <tribler_core.modules.libtorrent.download_config.DownloadConfig object at 0x00000000295CA310>

    def test_download_load_corrupt(download_config):
        with pytest.raises(ConfigObjError):
>           download_config.load(CONFIG_FILES_DIR / "corrupt_download_config.conf")
E           TypeError: load() takes from 0 to 1 positional arguments but 2 were given

src\tribler-core\tribler_core\modules\libtorrent\tests\test_download_config.py:53: TypeError
___________________________ test_download_save_load ___________________________
[gw5] win32 -- Python 3.8.4 c:\users\tribler\appdata\local\programs\python\python38\python.exe

download_config = <tribler_core.modules.libtorrent.download_config.DownloadConfig object at 0x0000000029321070>
tmpdir = local('C:\\Users\\tribler\\AppData\\Local\\Temp\\pytest-of-tribler\\pytest-1911\\popen-gw5\\test_download_save_load0')

    def test_download_save_load(download_config, tmpdir):
        file_path = tmpdir / "downloadconfig.conf"
        download_config.write(file_path)
>       assert download_config.load(file_path)
E       TypeError: load() takes from 0 to 1 positional arguments but 2 were given
```

I can probably resolve this in this PR.

**Comment by qstokkink** [comment]
I don't know what arcane sorcery caused https://github.com/Tribler/tribler/pull/5861#issuecomment-745990577, but it seems like some ultra-rare intermittent failure in the tests, so I'll ignore that.

**Comment by qstokkink** [comment]
After its tumultuous start, this PR is now ready for review. The remaining Pylint violation is due to a callback function (at some point we should refactor our codebase such that all callback methods comply with Pylints callback naming standards - not in this PR though).

**Review by drew2a — DISMISSED** [review]

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
@drew2a thanks for reviewing, I invalidated your review by rebasing on the latest `devel`. Could you rereview?

**Review by drew2a — APPROVED** [review]

**Pull request merged**
