### PR TITLE
WIP: Added heartbeat mechanism to check aliveness of the core

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by devos50** [comment]
Didn't see comment of @synctext in #2842, I will postpone this PR until we need it for better debugging.

**Comment by synctext** [comment]
Logging any missing heartbeat and slow response time of the core would be great debug material in future.

**Comment by devos50** [comment]
Actually, I was thinking about creating a visual plot of request latency in the debug panel for this endpoint but a bit low priority for now.

**Comment by synctext** [comment]
We want more deeper awareness then just responsiveness I fear. e.g. What is the core doing for this 42% CPU usage?

**Pull request closed without merging**
