### PR TITLE
Fix #6271

### LINKED ISSUE #6271: [main] GUI errors when running with `[resource_monitor] enabled = False`
Using this config (http_port and key removed):

```
[api]
    http_enabled = True
    http_port = <redacted>
    key = <redacted>
[resource_monitor]
enabled = False
```

The GUI shows the following two errors when clicking through the debug tab:

err1
err2

### PR DESCRIPTION
**Pull request by ichorid**
Fixes #6271 by splitting Debug endpoint initialization and disabling Profiler button in Debug window when Profiler is disabled in the Core

### CODE REVIEW

**Comment by ichorid** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Review by xoriole — APPROVED** [review]

**Comment by ichorid** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Pull request merged**
