### PR TITLE
Fix libtorrent 1.2.4+ compatibility

### PR DESCRIPTION
**Pull request by egbertbouman**
Fixes https://github.com/Tribler/tribler/issues/5474.

### CODE REVIEW

**Comment by egbertbouman** [comment]
retest this please

**Comment by devos50** [comment]
It looks like the `test_hidden_service` is still failing under libtorrent 1.2.4 and 1.2.5: https://jenkins-ci.tribler.org/job/validation_experiments/job/validation_experiment_libtorrent_compatibility/581/console. @egbertbouman do you want to fix this one?

**Comment by egbertbouman** [comment]
While hunting for the bug I only tried it with the latest version (1.2.7).

It seems there are 2 completely different issues at play here:
* In libtorrent 1.2.6/1.2.7 `listen_port()` returns 0 when used with a SOCKS5 proxy on Windows. That's fixed.
* In libtorrent 1.2.4/1.2.5 there are known issues with SOCKS5 proxies. I'm not sure what we can do about this. I think we may have to accept that this isn't going to work.

**Comment by devos50** [comment]
Ok, I'm fine with deeming libtorrent 1.2.4/1.2.5 incompatible with Tribler them and removed them from the validation experiment 👍

**Pull request merged**
