### PR TITLE
Fix #6289

### LINKED ISSUE #6289: [main] Stolen code without attribution
https://github.com/Tribler/tribler/blob/3343308ff7aacb184b84255a8eb7c6eb1714ebda/src/tribler-core/tribler_core/utilities/utilities.py#L22-L42

This code is copied from this SO post: https://stackoverflow.com/a/29368642

One of the conditions of using this code from SO is attribution (`CC BY-SA 3.0`, see https://creativecommons.org/licenses/by-sa/3.0/). We should add a comment here that shows where this code comes from and who made it.

### PR DESCRIPTION
**Pull request by ichorid**
fixes #6289

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Review by xoriole — APPROVED** [review]

**Pull request merged**
