### PR TITLE
Update Tribler development on OS X.md

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by whirm** [comment]
Looking great!
Could you squash the thing into one commit if you are done updating it?

**Comment by devos50** [comment]
Yeah I will, have one issue left regarding `libsodium.dylib` which cannot be found by `ctypes`. Think this is due to to SIP (https://support.apple.com/nl-nl/HT204899) but I do not want to disable it so I should think about a good solution for this. For now I have a very bad workaround place but this should be changed (see the open .txt file on the Mac Mini).

**Comment by devos50** [comment]
As discussed with @whirm I will file a bug report for this at Apple.

**Comment by devos50** [comment]
Apparently, it is not a bug but a security feature, see https://forums.developer.apple.com/thread/13161 for more information about it. I've added a dedicated section about this to the guide with two solutions: either symlink the `libsodium.dylib` file into the Tribler root directory or disable System Integrity Protection (not recommended).

**Comment by devos50** [comment]
@whirm I'm done with this PR.

**Comment by whirm** [comment]
@devos50 what about the packaged version of Tribler?

**Pull request merged**
