### PR TITLE
Refactored credit mining to Core

### LINKED ISSUE #2515: The policies directory should be moved inside the Core package
I fail to see the benefits of having the `Policies` package inside the root directory of `Tribler`. We also have a cyclic dependency now between the `Core` and `Policies` package.

Since the `Policies` package is part of the credit mining mechanism (which is essentially part of libtribler), I think it makes more sense if we move this directory inside the `Core`.

@ardhipoetra any thoughts on this?

### PR DESCRIPTION
**Pull request by ardhipoetra**
As discussed in #2515.

The module is available, but currently there is no GUI to access that. I haven't create Qt interface for this. Should I create it in separate pull request later?

Fixes #2515

### CODE REVIEW

**Comment by devos50** [comment]
@ardhipoetra if you are planning on integrating credit mining in the GUI, you should create a separate PR for that.

Also, these pylint issues are quite easy to fix. Can you do that in a separate commit?

**Comment by ardhipoetra** [comment]
@devos50, ready

**Comment by devos50** [comment]
@ardhipoetra looks fine! Please squash and I'll merge :)

**Comment by ardhipoetra** [comment]
Squashed and ready to merge!

**Comment by devos50** [comment]
Fixes #2515

**Pull request merged**
