### PR TITLE
Various fixes

### LINKED ISSUE #5250: TriblerTunnelCommunity.remove_circuit(): Task was destroyed but it is pending!
The following error got caught by the application tester (Windows 7, 64-bit):

```
[PID:2956] 2020-03-26 13:38:13,599 - ERROR <tribler_window:107> root.on_exception(): Traceback (most recent call last):
  File "src\tribler-gui\tribler_gui\event_request_manager.py", line 114, in on_read_data
RuntimeError: Task was destroyed but it is pending!
--CONTEXT--
{'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<TriblerTunnelCommunity.remove_circuit() running at src\tribler-core\tribler_core\modules\tunnel\community\triblertunnel_community.py:407> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x000000001617A6D8>()]> cb=[TaskManager.register_task.<locals>.done_cb() at ipv8\taskmanager.py:105]>}

ERROR:Executor:********** TRIBLER CRASHED **********
ERROR:Executor:Tribler crashed after uptime of 1562.634765625 sec! Stack trace: Traceback (most recent call last):
  File "src\tribler-gui\tribler_gui\event_request_manager.py", line 114, in on_read_data
RuntimeError: Task was destroyed but it is pending!
--CONTEXT--
{'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<TriblerTunnelCommunity.remove_circuit() running at src\tribler-core\tribler_core\modules\tunnel\community\triblertunnel_community.py:407> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x000000001617A6D8>()]> cb=[TaskManager.register_task.<locals>.done_cb() at ipv8\taskmanager.py:105]>}
```

### PR DESCRIPTION
**Pull request by egbertbouman**
fixes #5250

### CODE REVIEW

**Comment by ichorid** [comment]
There are lots of `re-adding peer` messages now! Never seen these before.
:+1:

**Comment by egbertbouman** [comment]
@ichorid While debugging other issues, I noticed a recurring dip in download speed, and discovered that the readd peers feature has been broken for quite some time. This dip is still there, but this fix seems to help.

**Comment by ichorid** [comment]
After applying the fixes, `mem_top` looks like this:
```
14766   <class 'dict'> {('77.40.89.100', 23387): <ipv8.messaging.anonymization.tunnel.Circuit object at 0x7ff85e167e48>
5294    <class 'dict'> {('125.139.153.167', 8999): <ipv8.messaging.anonymization.tunnel.Circuit object at 0x7ff85c1b9a5
7744    <class 'dict'> {('95.158.244.77', 50111): <ipv8.messaging.anonymization.tunnel.Circuit object at 0x7ff8565e0da0
12382   <class 'dict'> {('37.48.77.233', 32837): <ipv8.messaging.anonymization.tunnel.Circuit object at 0x7ff8303cc828>
7518    <class 'dict'> {('223.187.139.200', 7479): <ipv8.messaging.anonymization.tunnel.Circuit object at 0x7ff8544c524
9842    <class 'dict'> {('2.94.118.137', 63116): <ipv8.messaging.anonymization.tunnel.Circuit object at 0x7ff8209df3c8>
9908    <class 'dict'> {('37.191.7.246', 6881): <ipv8.messaging.anonymization.tunnel.Circuit object at 0x7ff83068fa90>,
17248   <class 'dict'> {('172.58.236.203', 23350): <ipv8.messaging.anonymization.tunnel.Circuit object at 0x7ff83050290
8568    <class 'dict'> {('37.48.77.235', 54665): <ipv8.messaging.anonymization.tunnel.Circuit object at 0x7ff820c3c7f0>
10842   <class 'dict'> {('188.153.166.236', 6889): <ipv8.messaging.anonymization.tunnel.Circuit object at 0x7ff85c3d871
10272   <class 'dict'> {('2.51.154.42', 56150): <ipv8.messaging.anonymization.tunnel.Circuit object at 0x7ff85e335f28>,
11020   <class 'dict'> {('81.171.8.20', 46526): <ipv8.messaging.anonymization.tunnel.Circuit object at 0x7ff854691ac8>,
```


The references count is still high. However the first object in the dict seems to be rotating, meaning that it is no longer stuck. Congrats! :clap:

**Comment by egbertbouman** [comment]
I haven't really looked for the cause of these high ref counts yet, but I'll start debugging this now. Looking at the dictionaries, it could be related to the dispatcher.

**Comment by egbertbouman** [comment]
@ichorid The dictionary that you're seeing lists of all IP,circuit combinations that we've used. The list is cleaned up every time a circuit is closed. It looks like this is working as expected.

**Pull request merged**
