### PR TITLE
READY: Add GUI notifications to personal channel conversion process

### PR DESCRIPTION
**Pull request by ichorid**
This adds progress notifications to the personal channel conversion process, the same as we use for converting legacy torrents to FFA entries.

### CODE REVIEW

**Comment by ichorid** [comment]
retest this please

**Comment by ichorid** [comment]
retest this please

**Comment by qstokkink** [comment]
Depends on #4573

**Comment by qstokkink** [comment]
Merged, please rebase onto the latest head.

**Pull request merged**
