### PR TITLE
Revert "Don't raise the assert exceptions at tearDown"

### PR DESCRIPTION
**Pull request by whirm**
This reverts commit ebe98d61da5bb1aeea880264751d672c4ac99516.

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
Doesn't look great, it hanging on the first test.

**Comment by whirm** [comment]
I can't reproduce it locally. I'm rebooting the gorillas and will start investigating from there.

**Comment by NielsZeilemaker** [comment]
It's really strange, it seems to be blocking. But the userdownloadchoice doesn't do anything which can lock tribler.
Maybe add the new dispersy pointer to see what is causing the isolated test to drop the packet.

**Comment by NielsZeilemaker** [comment]
@LipuFei was this one known already?
```
17:54:09 [-] [isolated_tribler_net...] ERR:   File "/home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel/tribler/Tribler/TrackerChecking/TrackerSession.py", line 408, in _processScrapeResponse
17:54:09 [-] [isolated_tribler_net...] ERR:     for infohash in response_dict['files']:
17:54:09 [-] [isolated_tribler_net...] ERR: TypeError: string indices must be integers, not str

**Comment by NielsZeilemaker** [comment]
@whirm as for the other test, at least its asserting again :smile: I guess there's a problem with the refresh of the channels tab + something is up with the download tests.

**Comment by whirm** [comment]
Should we merge this then?

**Comment by whirm** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
@whirm I would, and I would merge a couple other smaller pull requests as well. Afterwards, have a look at how many tests are still failing.

**Comment by whirm** [comment]
Ok, my theory is that there's some racy stuff in Tribler because I disabled the isolated test runner which generates a lot of IO and the next test run only had a single failure.

**Comment by LipuFei** [comment]
@NielsZeilemaker I've refactored the whole TorrentChecking thing. This problem is gone now.

**Comment by whirm** [comment]
Well, I guess I talked too soon

**Comment by NielsZeilemaker** [comment]
The download from url test cannot work as the fedora torrent gives a 404 (obviously silently swallowed by torrentdef.load_from_url). 
Maybe update to http://torrent.fedoraproject.org/torrents/Fedora-Live-Workstation-x86_64-21.torrent

**Comment by NielsZeilemaker** [comment]
Same url is used by the download stop start delete, so that one needs fixing as well.

**Comment by LipuFei** [comment]
@whirm needs a rebase

**Comment by NielsZeilemaker** [comment]
@LipuFei @whirm the my channel tests are broken because of the family filter, the torrents have a category which is Compressed, but the enabled categories are lowercase only.
Have a look why the category has a captial.

**Comment by NielsZeilemaker** [comment]
Afterwards, disable the family fliter in the manage channel thing by add this method to the managechannelfileslist class
```
def MatchFFilter(self, item):
        return True

**Comment by NielsZeilemaker** [comment]
@whirm I think the other tests were just unlucky. The vodo search simply does not get any results from its connected peers, which might be worrying I don't know, the other tests are somewhat slow.

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
@whirm the family filter is still broken right?

**Comment by LipuFei** [comment]
@NielsZeilemaker I've disabled the family filter for all those tests except `ff_search`, so I think the family filter should not do any harm. I will check this again to make sure.

**Comment by NielsZeilemaker** [comment]
When I created the post it was still happening. Moreover, the capital thing should be fixed.

**Comment by whirm** [comment]
I'm busy with other stuff, @LipuFei could you take care of the capitalization thing?

**Comment by LipuFei** [comment]
@whirm I will work on it.

**Comment by whirm** [comment]
@LipuFei feel free to fork of this branch and work on it while I'm out.

**Comment by LipuFei** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
@LipuFei the community statistics don't really make sense, I'm seeing votecast messages being received in previewchannelcommunities. Those are only received by allchannel.
Can you have a look what's happening there?

**Comment by LipuFei** [comment]
@NielsZeilemaker I will. I am fixing the Mac at the moment, I will fix the search tests after that.

**Comment by NielsZeilemaker** [comment]
For the search, I'm hoping that https://github.com/Tribler/dispersy/pull/415 will fix it a bit.

**Comment by LipuFei** [comment]
@NielsZeilemaker I've updated the dispersy pointer and made another PR #1352. It includes every commit in this PR.

**Comment by NielsZeilemaker** [comment]
Great, I'm closing this one then.

**Pull request closed without merging**
