### PR TITLE
Added renamed dependency to docs for newer Ubuntu version.

### PR DESCRIPTION
**Pull request by jellelicht**
I am currently running a fresh install of Ubuntu 17.04, and had some issues getting the CI-generated debfile to install properly. It seems that from Ubuntu 16.10 onwards, the python-pysocks package has been renamed to python-socks. This PR mentions this for future reference in the docs.

### CODE REVIEW

**Comment by devos50** [comment]
Ok to test

**Comment by devos50** [comment]
@jellelicht thanks! Is it possible to do a fallback in the `debian/control` file to this other package?

**Comment by jellelicht** [comment]
@devos50 No clue how that would work, sorry ;-).

**Comment by jellelicht** [comment]
I added the python-socks dep to the debian control if the python-pysocks does not resolve. 
I verified it to install on 17.04, so if this works on the LTS it might be a good idea to add this fix.

I do think there are still quite some deps and settings missing in the current snapshot deb currently.

**Comment by devos50** [comment]
@jellelicht thanks! That was indeed the solution where I was hinting at but due to time constraints from my side (article writing) I didn't have time to dive into this. Good to see that it's solve now. Please squash your commits, rebase this branch onto `devel` again and I will merge it 👍

**Comment by jellelicht** [comment]
@devos50 done.

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by jellelicht** [comment]
@devos50 : Are you talking to me, or your integrated CI system ❓

**Comment by devos50** [comment]
@jellelicht that was an indicator to retest the current PR (I've changed a small setting in Jenkins).

**Comment by devos50** [comment]
@jellelicht thanks for your contribution!

**Pull request merged**
