### PR TITLE
Fix general except community

### PR DESCRIPTION
**Pull request by lfdversluis**

### CODE REVIEW

**Comment by lfdversluis** [comment]
`test_anon_download_exitnode_changeofmind (Tribler.Test.test_tunnel_community_negative.TestTunnelCommunityNegative) ... nosetests: Fatal IO error 11 (Resource temporarily unavailable) on X server :4494.`

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
```
Regression

Tribler.Test.test_my_channel.TestMyChannel.test_add_torrents_playlists (from nosetests)
Failing for the past 1 build (Since Failed#2303 )
Took 37 sec.
Error Message

The reactor was dirty when tearing down the test
```

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
@devos50 @whirm I thought you disabled the creditmining?
```
Tribler.Test.Core.CreditMining.test_creditmining_sys.TestBoostingManagerSysRSS.test_rss (from nosetests)
Failing for the past 4 builds (Since Failed#2360 )
Took 15 sec.
Error Message

timeout expired before end of test (15.000000 s.)
```

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
retest this please

**Comment by lfdversluis** [comment]
Oh the previous passed.. oh well!

**Comment by lfdversluis** [comment]
@devos50 can you review?

**Comment by devos50** [comment]
Look good.

**Pull request merged**
