### PR TITLE
Stricter signature for ErrorHandler.gui_error()

### PR DESCRIPTION
**Pull request by kozlovsky**
The current signature of the `gui_error` function is not strict enough. In practice, the function is always called with three arguments. Because of insufficient checks, inside the `gui_eror` function, PyCharm shows warnings "local variable might be referenced before assignment". This PR fixes PyCharm warnings and makes variable names for the exception and the exception type more "traditional".

Also, the PR uses the `caplog` pytest fixture to check log messages in tests.

### CODE REVIEW

**Comment by kozlovsky** [comment]
retest this please

**Comment by kozlovsky** [comment]
retest this please

**Comment by kozlovsky** [comment]
retest this please

**Comment by kozlovsky** [comment]
retest this please

**Comment by kozlovsky** [comment]
retest this please

**Review by drew2a — APPROVED** [review]

**Pull request merged**
