### PR TITLE
Removed unused statements, changed comments

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by whirm** [comment]
have you checked if prctlimported is used at all in gumby & co.?

**Comment by devos50** [comment]
Yes, it is not used by Gumby.

Verstuurd vanaf mijn iPhone

**Comment by whirm** [comment]
Also, that statement about the httplib bug is also fixed?

**Comment by devos50** [comment]
That bug was part of M2Crypto 0.16 which is pretty old. Moreover, we are not using the https part of M2Crypto since it was used by the version check system.

**Comment by whirm** [comment]
ok

**Pull request merged**
