### PR TITLE
Converted bandwidth amount to BIGINT type

### LINKED ISSUE #5703: [devel] RuntimeError: Value 2555318358 of attr BandwidthTransaction.amount is greater than the maximum allowed value 2147483647
As reported in our Slack channel:

```
File "tribler_gui/event_request_manager.py", line 102, in on_read_data
RuntimeError: Value 2555318358 of attr BandwidthTransaction.amount is greater than the maximum allowed value 2147483647
```

### PR DESCRIPTION
**Pull request by devos50**
Fixes #5703

### CODE REVIEW

**Comment by devos50** [comment]
Mac tests timed out for no reason...

**Comment by devos50** [comment]
retest this please

**Comment by ichorid** [comment]
Should this go to `devel` instead of `release-7.5`?

**Comment by devos50** [comment]
@ichorid the target branch is set to `devel` right?

**Comment by ichorid** [comment]
Oops, I meant the opposite :face_with_head_bandage: 

I expected it on `release-7.5`

**Review by ichorid — APPROVED** [review]

**Pull request merged**
