### PR TITLE
Add `_safe_log`

### PR DESCRIPTION
**Pull request by drew2a**
This PR fixes https://github.com/Tribler/tribler/issues/7406 i by introducing the `_safe_log` function.

### CODE REVIEW

**Review by kozlovsky — CHANGES_REQUESTED** [review]
The PR solves the problem by introducing a new method of the `Download` class that should be used instead of standard logging methods. It catches possible exceptions that arise during the log message formatting.

Although the proposed change solves the problem, the chosen solution has some drawbacks:
* The original essence of the problem has nothing to do with logging. It is related to the fact that converting an alert to a string can lead to an error. At the same time, the proposed solution is explicitly tied to logging, replacing standard logging methods with a new non-standard method.
* The proposed new logging method assumes a rigid message structure when the only possible format is given inside a helper function. It looks inflexible and not versatile enough.

I would suggest considering alternative solutions:

Instead of the `_safe_log` method of the `Download` class, we could use the more generic `safe_repr` function, applying it to alert objects. With this approach, the developers:
* will be able to continue to use the usual methods for logging
* will not be limited in the structure of the message used when logging
* will be able to apply `safe_repr` to alert objects in other situations not related to logging.
* the meaning of the code will look clearer for readers since the reader will see that the original problem is not in logging as such but in the string display of the alert.
* The `safe_repr` function can be made generic and applicable not only to alerts but also to other types of objects - by catching all exceptions thrown when calling `repr(obj)`, it can output some safe alternative result, for example, including the object type and its id.

**Comment by drew2a** [comment]
I think the solution proposed in the PR is good enough. It solves the problem. It is simple. It is straightforward. The format with `f'{message}: {alert}'` is flexible enough to cover all calls in the whole almost 1k file.

**Comment by xoriole** [comment]
In my opinion, it is possible that the error `tracker_error_alert` is only raising the exception.
Here is an old ticket (also fixed): https://github.com/arvidn/libtorrent/issues/143
Also, the error is reported for Windows only. So, it would be great if the issue could be actually reproduced.

PS. The link on the issue ticket is wrong. It should be #7406 instead of #7404

**Review by xoriole — CHANGES_REQUESTED** [review]
I'd agree with @kozlovsky's idea of `safe_repr` applying to alert objects instead of `_safe_log`.

**Pull request closed without merging**
