### PR TITLE
Fixed NoneType GUI bug again

### LINKED ISSUE #3807: TypeError: 'NoneType' object in home recommended items
From reporter - Tribler 7.1.0 -beta
```python
Traceback (most recent call last):
File "TriblerGUI\widgets\home_recommended_item.py", line 73, in on_download_button_clicked
TypeError: 'NoneType' object has no attribute '__getitem__'
```

### PR DESCRIPTION
**Pull request by xoriole**
Fixes #3807

### CODE REVIEW

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
retest this please

**Comment by qstokkink** [comment]
```python
ERROR   1534933716       community:MarketCommunity:397  Exception occurred while handling packet!
Traceback (most recent call last):
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/pyipv8/ipv8/deprecated/community.py", line 394, in on_packet
    self.decode_map[data[22]](source_address, data)
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/pyipv8/ipv8/deprecated/community.py", line 84, in wrapper
    return func(self, Peer(auth.public_key_bin, source_address), *output)
  File "/home/jenkins/ci/workspace/GH_Tribler_PR_tests_linux/tribler/Tribler/community/market/community.py", line 1303, in received_start_transaction
    match_payload = self.incoming_match_messages[request.match_id]
KeyError: '82c071409871f9fbe69a'
```

**Comment by xoriole** [comment]
retest this please

**Pull request merged**
